---
title: "NCT04305054 Change History"
---

| Timestamp                   | Before                                                                          | After                                                                    |
|:----------------------------|:--------------------------------------------------------------------------------|:-------------------------------------------------------------------------|
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;45&#93;city**: Napoli                  | **contactsLocationsModule.locations.&#91;45&#93;city**: Naples           |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;45&#93;geoPoint.lat**: 40.87618        | **contactsLocationsModule.locations.&#91;45&#93;geoPoint.lat**: 40.85216 |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;45&#93;geoPoint.lon**: 14.5195         | **contactsLocationsModule.locations.&#91;45&#93;geoPoint.lon**: 14.26811 |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;46&#93;city**: Padua                   | **contactsLocationsModule.locations.&#91;46&#93;city**: Padova           |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;46&#93;geoPoint.lat**: 45.40797        | **contactsLocationsModule.locations.&#91;46&#93;geoPoint.lat**: 44.38225 |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;46&#93;geoPoint.lon**: 11.88586        | **contactsLocationsModule.locations.&#91;46&#93;geoPoint.lon**: 11.14261 |
| 2026-04-09 02&#58;28&#58;32 | **statusModule.statusVerifiedDate**: 2025-08                                    | **statusModule.statusVerifiedDate**: 2026-03                             |
| 2026-04-09 02&#58;28&#58;32 | **statusModule.primaryCompletionDateStruct.date**: 2026-04-20                   | **statusModule.primaryCompletionDateStruct.date**: 2026-05-20            |
| 2026-04-09 02&#58;28&#58;32 | **statusModule.completionDateStruct.date**: 2026-04-20                          | **statusModule.completionDateStruct.date**: 2026-05-20                   |
| 2026-04-09 02&#58;28&#58;32 | **statusModule.lastUpdateSubmitDate**: 2025-08-28                               | **statusModule.lastUpdateSubmitDate**: 2026-04-07                        |
| 2026-04-09 02&#58;28&#58;32 | **statusModule.lastUpdatePostDateStruct.date**: 2025-08-29                      | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-08               |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;26&#93;state**: Región de la Araucanía | **contactsLocationsModule.locations.&#91;26&#93;state**: Araucania       |
| 2026-05-29 03&#58;42&#58;24 | **statusModule.statusVerifiedDate**: 2026-03                                    | **statusModule.statusVerifiedDate**: 2026-05                             |
| 2026-05-29 03&#58;42&#58;24 | **statusModule.overallStatus**: ACTIVE_NOT_RECRUITING                           | **statusModule.overallStatus**: COMPLETED                                |
| 2026-05-29 03&#58;42&#58;24 | **statusModule.primaryCompletionDateStruct.date**: 2026-05-20                   | **statusModule.primaryCompletionDateStruct.date**: 2026-05-18            |
| 2026-05-29 03&#58;42&#58;24 | **statusModule.primaryCompletionDateStruct.type**: ESTIMATED                    | **statusModule.primaryCompletionDateStruct.type**: ACTUAL                |
| 2026-05-29 03&#58;42&#58;24 | **statusModule.completionDateStruct.date**: 2026-05-20                          | **statusModule.completionDateStruct.date**: 2026-05-18                   |
| 2026-05-29 03&#58;42&#58;24 | **statusModule.completionDateStruct.type**: ESTIMATED                           | **statusModule.completionDateStruct.type**: ACTUAL                       |
| 2026-05-29 03&#58;42&#58;24 | **statusModule.lastUpdateSubmitDate**: 2026-04-07                               | **statusModule.lastUpdateSubmitDate**: 2026-05-27                        |
| 2026-05-29 03&#58;42&#58;24 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-08                      | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-28               |
| 2026-05-29 03&#58;42&#58;24 | **designModule.enrollmentInfo.count**: 315                                      | **designModule.enrollmentInfo.count**: 335                               |
| 2026-05-29 03&#58;42&#58;24 | **designModule.enrollmentInfo.type**: ESTIMATED                                 | **designModule.enrollmentInfo.type**: ACTUAL                             |
