---
title: "NCT06346197 Change History"
---

| Timestamp                   | Before                                                                                              | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|:----------------------------|:----------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-03-03 00&#58;59&#58;13 | **statusModule.statusVerifiedDate**: 2025-12                                                        | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-03 00&#58;59&#58;13 | **statusModule.lastUpdateSubmitDate**: 2025-12-19                                                   | **statusModule.lastUpdateSubmitDate**: 2026-02-27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-03 00&#58;59&#58;13 | **statusModule.lastUpdatePostDateStruct.date**: 2025-12-26                                          | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-26 02&#58;29&#58;47 | **statusModule.statusVerifiedDate**: 2026-02                                                        | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-26 02&#58;29&#58;47 | **statusModule.lastUpdateSubmitDate**: 2026-02-27                                                   | **statusModule.lastUpdateSubmitDate**: 2026-03-23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-26 02&#58;29&#58;47 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-02                                          | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | **statusModule.statusVerifiedDate**: 2026-03                                                        | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-04-09 02&#58;28&#58;32 | **statusModule.lastUpdateSubmitDate**: 2026-03-23                                                   | **statusModule.lastUpdateSubmitDate**: 2026-04-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-04-09 02&#58;28&#58;32 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-25                                          | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Male or female patient ≥18 years of age at time of informed consent form signature.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with MSI-H/dMMR, HER2 negativeadvanced or metastatic gastric, gastro-oesophageal junction or oesophageal adenocarcinoma whose tumours express PD-L1 with a combined positive score (CPS) ≥ 5.                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient to be treated with a first line therapy for locally advanced/metastatic disease.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * No prior treatment with chemotherapy for locally advanced/metastatic disease.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | o Note - adjuvant or neoadjuvant chemotherapy is allowed providing that 6 months have relapsed between completion of adjuvant chemotherapy and recurrence.                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Measurable disease (outside any previous irradiated field within the past 6 months) defined as at least one unidimensional lesion that can be accurately measured as ≥ 10 mm with CT scan according to RECIST V1.1 (Appendix 01).                                                                                                                                                                                                                                                                                                                                          |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Note&#58; Lesions intended to be biopsied should not be defined as target lesions.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Note&#58; previously irradiated lesions can be selected as target lesion only if recurrence/PD is documented after RT.                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with PS ECOG 0 or 1 (Appendix 02).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Adequate hematologic and end-organ function, defined by the following laboratory test results&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | Absolute neutrophil count ≥ 1.5 109/L (without growth factor support within 14 d) Platelets ≥ 100 109/L (without transfusion for platelets within 7 d) Hemoglobin ≥ 9 g/dL (without transfusion within 7 d) Creatinine clearance according to CKD-EPI ≥ 30 mL/min/1.73 m2 Serum total bilirubin ≤ 1.5 x ULN (except for patients with Gilbert disease for whom a total serum bilirubin ≤ 3 x ULN is acceptable) ASAT and ALAT ≤ 3 x ULN (or up to 5 x ULN in case of liver metastasis or hepatic infiltration)                                                               |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Availability of a representative formalin-fixed paraffin-embedded (FFPE) sample of the primary or metastatic tumor tissue (resection or biopsy) with an associated pathology report must be available. This tumor sample must meet the following quality/quantity control criteria&#58; ≥30 % of tumor cells and a tumor surface area ≥ 5mm2 or biopsiable disease (see next inclusion criteria).                                                                                                                                                                          |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Tumor lesion visible by medical imaging and accessible to repeatable percutaneous or endoscopic sampling that permits core needle biopsy without unacceptable risk of a significant procedural complications, and suitable for retrieval of a minimum of 4 cores with a needle minimum diameter &#58;16-gauge.                                                                                                                                                                                                                                                             |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Note 1&#58; Fine needle aspirates, bone biopsies do not satisfy the requirement for tumor tissue.                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Note 2&#58; Tumor lesions used for biopsy should not be lesions used as RECIST 1.1 target lesions unless there are no other lesions suitable for biopsy. If a RECIST target lesion is used for biopsy, the lesion must be ≥ 2 cm in longest diameter.                                                                                                                                                                                                                                                                                                                      |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Women of childbearing potential (WOCBP) must have a negative serum pregnancy test at the Screening Visit (within 72 hours of first dose of study drugs) and must agree to use highly effective contraceptive measures starting with the Screening Visit through                                                                                                                                                                                                                                                                                                            |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * 9 months after the end of the treatment with oxaliplatin                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * 6 months after the end of the treatment with fluorouracil                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * 5 months after the end of the treatment with nivolumab or botensilimab or Balstilimab                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * 6 months for capecitabine                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Highly effective contraception is defined in Appendix 03.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | Note Non-childbearing potential is defined as&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | 1. ≥ 50 years of age and has not had menses for greater than 1 year.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | 2. Amenorrheic for ≥ 2 years without a hysterectomy and bilateral oophorectomy and a follicle-stimulating hormone value in the postmenopausal range upon pre-study (screening) evaluation.                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | 3. Status is post-hysterectomy, bilateral oophorectomy, or tubal ligation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Male patients with a female partner(s) of childbearing potential must agree to use highly effective contraceptive measures throughout the study starting with the screening visit through 6 months after the end of the treatment with oxaliplatine or 3 months after the last dose for other study treatments is received. Males with pregnant partners must agree to use a condom; no additional method of contraception is required for the pregnant partner.                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient should understand, sign, and date the written voluntary informed consent form prior to any protocol-specific procedures performed and should be able and willing to comply with study visits and procedures as per protocol.                                                                                                                                                                                                                                                                                                                                       |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients must be covered by a medical insurance.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Oesogastric cancer eligible to treatment with curative intent                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients previously treated by anti-PD-1, anti-PD-L1, or anti-CTLA-4 or any other immunotherapy                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with surgery or radiotherapy within less than 4 weeks before C1D1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with persistent AE Grade &#92;&gt;1 related to previous anti-cancer treatment, except alopecia (all grades), laboratory value according to criteria I7.                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with&#58; hypokalemia, hypomagnesemia, hypocalcemia less than normal                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with known prolongation QT/QTc interval i.e. QT/QTc interval longer than 450 msec for men and longer than 470 msec for women according to the inclusion ECG.                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Symptomatic, untreated, or actively progressing central nervous system (CNS) metastases.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | Note&#58; Asymptomatic patients with treated CNS lesions are eligible, provided that all of the following criteria are met&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Measurable disease, per RECIST v1.1, must be present outside the CNS.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * The patient has no history of intracranial hemorrhage or spinal cord hemorrhage.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Metastases are limited to the cerebellum or the supratentorial region (i.e., no metastases to the midbrain, pons, medulla, or spinal cord).                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * There is no evidence of interim progression between completion of CNS-directed therapy and initiation of study treatment.                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * The patient has not undergone stereotactic radiotherapy within 7 days prior to initiation of study treatment, whole-brain radiotherapy within 14 days prior to initiation of study treatment, neurosurgical resection within 21 days prior to initiation of study treatment.                                                                                                                                                                                                                                                                                               |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * The patient has no ongoing requirement for corticosteroids as therapy for CNS disease. Anticonvulsant therapy at a stable dose is permitted. A minimal wash-out period of 10days for corticosteroids is required.                                                                                                                                                                                                                                                                                                                                                          |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with other malignancy unless this malignancy is not expected to interfere with the evaluation of study endpoints (basal or squamous cell carcinoma of the skin, in-situ carcinoma of the cervix, localized prostate cancer), or with no evidence of disease for ≥ 2 years.                                                                                                                                                                                                                                                                                        |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Known allergy or hypersensitivity to any of the study drugs or any of the study drug excipients.                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * of ILD or non-infectious pneumonitis requiring glucocorticoids.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * History of allogeneic organ transplant.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Psychiatric or substance abuse disorders that would interfere with cooperation with the requirements of the study.                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with peripheral sensory neuropathy with functional impairment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with clinically significant active heart disease or myocardial infarction within 6 months, history of uncontrolled or symptomatic cardiac disease.                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with recent (within 7d before C1D1) or concomitant treatment with brivudine.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with complete absence of dihydropyrimidine dehydrogenase (DPD) activity (blood uracil level ≥ 150 ng/mL) or partial deficit in DPD (i.e. blood uracil level between ≥ 16 ng/ml and &#92;&lt; 150 ng/mL)                                                                                                                                                                                                                                                                                                                                                            |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with a condition requiring systemic treatment with either corticosteroids (&#92;&gt; 10 mg daily prednisone equivalent) within 14 days or another immunosuppressive medication within 30 days of the first dose of study treatment. Inhaled or topical steroids, and adrenal replacement steroid doses (≤ 10 mg daily prednisone equivalent) are permitted in the absence of active autoimmune disease.                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with Live vaccines injection within 4 weeks before C1D1. Examples of live vaccines include, but are not limited to, the following&#58; measles, mumps, rubella, chicken pox, yellow fever and BCG. Seasonal influenza vaccines for injection are generally killed virus vaccines and are allowed; however intranasal influenza vaccines (e.g. Flu-Mist®) are live attenuated vaccines, and are not allowed.                                                                                                                                                        |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Active autoimmune disease or history of autoimmune disease that required systemic treatment within 2 years of the start of study treatment (i.e., with use of disease-modifying agents or immunosuppressive drugs).                                                                                                                                                                                                                                                                                                                                                        |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * History or current evidence of any condition, co-morbidity, therapy, any active infections, or laboratory abnormality that might confound the results of the study, interfere with the patient&#x27;s participation for the full duration of the study, or is not in the best interest of the patient to participate, in the opinion of the treating Investigator.                                                                                                                                                                                                         |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with documented&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Active hepatitis B (chronic or acute; defined as having a positive hepatitis B surface antigen &#92;&#91;HBsAg&#92;&#93; test at screening) unless their HBV is stably controlled on nucleoside analogs (eg entecavir or tenofovir) which will be continued for the duration of the study. Note&#58; Patients with past hepatitis B virus (HBV) infection or resolved HBV infection (defined as the presence of hepatitis B core antibody &#92;&#91;anti-HBc&#92;&#93; and absence of HBsAg) are eligible. HBV DNA test must be performed in these patients prior to C1D1. |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Active hepatitis C. Patients positive for hepatitis C virus (HCV) antibody are eligible only if PCR is negative for HCV RNA, or                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * HIV infection                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Prior organ or bone marrow transplant.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Pregnant or lactating women.&#96; to &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Male or female patient ≥18 years of age at time of informed consent form signature.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with MSI-H/dMMR, HER2 negativeadvanced or metastatic gastric, gastro-oesophageal junction or oesophageal adenocarcinoma whose tumours express PD-L1 with a combined positive score (CPS) ≥ 5. Note &#58;The claudin 18.2 status must be known and documented before inclusion.                                                                                                                                                                                                                                                                                     |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient to be treated with a first line therapy for locally advanced/metastatic disease.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * No prior treatment with chemotherapy for locally advanced/metastatic disease.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | o Note - adjuvant or neoadjuvant chemotherapy is allowed providing that 6 months have relapsed between completion of adjuvant chemotherapy and recurrence.                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Measurable disease (outside any previous irradiated field within the past 6 months) defined as at least one unidimensional lesion that can be accurately measured as ≥ 10 mm with CT scan according to RECIST V1.1 (Appendix 01).                                                                                                                                                                                                                                                                                                                                          |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Note&#58; Lesions intended to be biopsied should not be defined as target lesions.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Note&#58; previously irradiated lesions can be selected as target lesion only if recurrence/PD is documented after RT.                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with PS ECOG 0 or 1 (Appendix 02).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Adequate hematologic and end-organ function, defined by the following laboratory test results&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | Absolute neutrophil count ≥ 1.5 109/L (without growth factor support within 14 d) Platelets ≥ 100 109/L (without transfusion for platelets within 7 d) Hemoglobin ≥ 9 g/dL (without transfusion within 7 d) Creatinine clearance according to CKD-EPI ≥ 30 mL/min/1.73 m2 Serum total bilirubin ≤ 1.5 x ULN (except for patients with Gilbert disease for whom a total serum bilirubin ≤ 3 x ULN is acceptable) ASAT and ALAT ≤ 3 x ULN (or up to 5 x ULN in case of liver metastasis or hepatic infiltration)                                                               |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Availability of a representative formalin-fixed paraffin-embedded (FFPE) sample of the primary or metastatic tumor tissue (resection or biopsy) with an associated pathology report must be available. This tumor sample must meet the following quality/quantity control criteria&#58; ≥30 % of tumor cells and a tumor surface area ≥ 5mm2 or biopsiable disease (see next inclusion criteria).                                                                                                                                                                          |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Tumor lesion visible by medical imaging and accessible to repeatable percutaneous or endoscopic sampling that permits core needle biopsy without unacceptable risk of a significant procedural complications, and suitable for retrieval of a minimum of 4 cores with a needle minimum diameter &#58;16-gauge.                                                                                                                                                                                                                                                             |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Note 1&#58; Fine needle aspirates, bone biopsies do not satisfy the requirement for tumor tissue.                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Note 2&#58; Tumor lesions used for biopsy should not be lesions used as RECIST 1.1 target lesions unless there are no other lesions suitable for biopsy. If a RECIST target lesion is used for biopsy, the lesion must be ≥ 2 cm in longest diameter.                                                                                                                                                                                                                                                                                                                      |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Women of childbearing potential (WOCBP) must have a negative serum pregnancy test at the Screening Visit (within 72 hours of first dose of study drugs) and must agree to use highly effective contraceptive measures starting with the Screening Visit through                                                                                                                                                                                                                                                                                                            |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * 9 months after the end of the treatment with oxaliplatin                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * 6 months after the end of the treatment with fluorouracil                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * 5 months after the end of the treatment with nivolumab or botensilimab or Balstilimab                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * 6 months for capecitabine                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Highly effective contraception is defined in Appendix 03.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | Note Non-childbearing potential is defined as&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | 1. ≥ 50 years of age and has not had menses for greater than 1 year.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | 2. Amenorrheic for ≥ 2 years without a hysterectomy and bilateral oophorectomy and a follicle-stimulating hormone value in the postmenopausal range upon pre-study (screening) evaluation.                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | 3. Status is post-hysterectomy, bilateral oophorectomy, or tubal ligation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Male patients with a female partner(s) of childbearing potential must agree to use highly effective contraceptive measures throughout the study starting with the screening visit through 6 months after the end of the treatment with oxaliplatine or 3 months after the last dose for other study treatments is received. Males with pregnant partners must agree to use a condom; no additional method of contraception is required for the pregnant partner.                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient should understand, sign, and date the written voluntary informed consent form prior to any protocol-specific procedures performed and should be able and willing to comply with study visits and procedures as per protocol.                                                                                                                                                                                                                                                                                                                                       |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients must be covered by a medical insurance.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Oesogastric cancer eligible to treatment with curative intent                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients previously treated by anti-PD-1, anti-PD-L1, or anti-CTLA-4 or any other immunotherapy                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with surgery or radiotherapy within less than 4 weeks before C1D1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with persistent AE Grade &#92;&gt;1 related to previous anti-cancer treatment, except alopecia (all grades), laboratory value according to criteria I7.                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with&#58; hypokalemia, hypomagnesemia, hypocalcemia less than normal                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with known prolongation QT/QTc interval i.e. QT/QTc interval longer than 450 msec for men and longer than 470 msec for women according to the inclusion ECG.                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Symptomatic, untreated, or actively progressing central nervous system (CNS) metastases.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | Note&#58; Asymptomatic patients with treated CNS lesions are eligible, provided that all of the following criteria are met&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Measurable disease, per RECIST v1.1, must be present outside the CNS.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * The patient has no history of intracranial hemorrhage or spinal cord hemorrhage.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Metastases are limited to the cerebellum or the supratentorial region (i.e., no metastases to the midbrain, pons, medulla, or spinal cord).                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * There is no evidence of interim progression between completion of CNS-directed therapy and initiation of study treatment.                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * The patient has not undergone stereotactic radiotherapy within 7 days prior to initiation of study treatment, whole-brain radiotherapy within 14 days prior to initiation of study treatment, neurosurgical resection within 21 days prior to initiation of study treatment.                                                                                                                                                                                                                                                                                               |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * The patient has no ongoing requirement for corticosteroids as therapy for CNS disease. Anticonvulsant therapy at a stable dose is permitted. A minimal wash-out period of 10days for corticosteroids is required.                                                                                                                                                                                                                                                                                                                                                          |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with other malignancy unless this malignancy is not expected to interfere with the evaluation of study endpoints (basal or squamous cell carcinoma of the skin, in-situ carcinoma of the cervix, localized prostate cancer), or with no evidence of disease for ≥ 2 years.                                                                                                                                                                                                                                                                                        |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Known allergy or hypersensitivity to any of the study drugs or any of the study drug excipients.                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * of ILD or non-infectious pneumonitis requiring glucocorticoids.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * History of allogeneic organ transplant.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Psychiatric or substance abuse disorders that would interfere with cooperation with the requirements of the study.                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with peripheral sensory neuropathy with functional impairment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with clinically significant active heart disease or myocardial infarction within 6 months, history of uncontrolled or symptomatic cardiac disease.                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with recent (within 7d before C1D1) or concomitant treatment with brivudine.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with complete absence of dihydropyrimidine dehydrogenase (DPD) activity (blood uracil level ≥ 150 ng/mL) or partial deficit in DPD (i.e. blood uracil level between ≥ 16 ng/ml and &#92;&lt; 150 ng/mL)                                                                                                                                                                                                                                                                                                                                                            |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with a condition requiring systemic treatment with either corticosteroids (&#92;&gt; 10 mg daily prednisone equivalent) within 14 days or another immunosuppressive medication within 30 days of the first dose of study treatment. Inhaled or topical steroids, and adrenal replacement steroid doses (≤ 10 mg daily prednisone equivalent) are permitted in the absence of active autoimmune disease.                                                                                                                                                           |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patient with Live vaccines injection within 4 weeks before C1D1. Examples of live vaccines include, but are not limited to, the following&#58; measles, mumps, rubella, chicken pox, yellow fever and BCG. Seasonal influenza vaccines for injection are generally killed virus vaccines and are allowed; however intranasal influenza vaccines (e.g. Flu-Mist®) are live attenuated vaccines, and are not allowed.                                                                                                                                                        |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Active autoimmune disease or history of autoimmune disease that required systemic treatment within 2 years of the start of study treatment (i.e., with use of disease-modifying agents or immunosuppressive drugs).                                                                                                                                                                                                                                                                                                                                                        |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * History or current evidence of any condition, co-morbidity, therapy, any active infections, or laboratory abnormality that might confound the results of the study, interfere with the patient&#x27;s participation for the full duration of the study, or is not in the best interest of the patient to participate, in the opinion of the treating Investigator.                                                                                                                                                                                                         |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Patients with documented&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Active hepatitis B (chronic or acute; defined as having a positive hepatitis B surface antigen &#92;&#91;HBsAg&#92;&#93; test at screening) unless their HBV is stably controlled on nucleoside analogs (eg entecavir or tenofovir) which will be continued for the duration of the study. Note&#58; Patients with past hepatitis B virus (HBV) infection or resolved HBV infection (defined as the presence of hepatitis B core antibody &#92;&#91;anti-HBc&#92;&#93; and absence of HBsAg) are eligible. HBV DNA test must be performed in these patients prior to C1D1. |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Active hepatitis C. Patients positive for hepatitis C virus (HCV) antibody are eligible only if PCR is negative for HCV RNA, or                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * HIV infection                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Prior organ or bone marrow transplant.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | * Pregnant or lactating women.&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;0&#93;contacts.&#91;0&#93;email**: chloe.verner2@gmail.com | **contactsLocationsModule.locations.&#91;0&#93;contacts.&#91;0&#93;email**: chloe.vernet2@gmail.com                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;1&#93;&#91;&#x27;zip&#x27;&#93;** (Added)                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                   | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;2&#93;&#91;&#x27;zip&#x27;&#93;** (Added)                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2026-04-02                                                   | **statusModule.lastUpdateSubmitDate**: 2026-04-16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-08                                          | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
