---
title: "NCT07115043 Change History"
---

| Timestamp                   | Before                                                                      | After                                                               |
|:----------------------------|:----------------------------------------------------------------------------|:--------------------------------------------------------------------|
| 2026-02-10 07&#58;03&#58;45 | **statusModule.statusVerifiedDate**: 2025-12                                | **statusModule.statusVerifiedDate**: 2026-02                        |
| 2026-02-10 07&#58;03&#58;45 | **statusModule.lastUpdateSubmitDate**: 2025-12-18                           | **statusModule.lastUpdateSubmitDate**: 2026-02-04                   |
| 2026-02-10 07&#58;03&#58;45 | **statusModule.lastUpdatePostDateStruct.date**: 2025-12-19                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-05          |
| 2026-02-10 07&#58;03&#58;45 | **contactsLocationsModule.locations.&#91;1&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;1&#93;status**: RECRUITING |
| 2026-02-10 07&#58;03&#58;45 | **contactsLocationsModule.locations.&#91;3&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;3&#93;status**: RECRUITING |
| 2026-03-18 02&#58;24&#58;04 | **statusModule.statusVerifiedDate**: 2026-02                                | **statusModule.statusVerifiedDate**: 2026-03                        |
| 2026-03-18 02&#58;24&#58;04 | **statusModule.lastUpdateSubmitDate**: 2026-02-04                           | **statusModule.lastUpdateSubmitDate**: 2026-03-16                   |
| 2026-03-18 02&#58;24&#58;04 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-05                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-17          |
| 2026-03-18 02&#58;24&#58;04 | **contactsLocationsModule.locations.&#91;2&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;2&#93;status**: RECRUITING |
| 2026-03-18 02&#58;24&#58;04 | **contactsLocationsModule.locations.&#91;5&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;5&#93;status**: RECRUITING |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2026-03                                | **statusModule.statusVerifiedDate**: 2026-04                        |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2026-03-16                           | **statusModule.lastUpdateSubmitDate**: 2026-04-22                   |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-17                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-23          |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;9&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;9&#93;status**: RECRUITING |
| 2026-06-12 04&#58;04&#58;21 | **statusModule.statusVerifiedDate**: 2026-04                                | **statusModule.statusVerifiedDate**: 2026-06                        |
| 2026-06-12 04&#58;04&#58;21 | **statusModule.lastUpdateSubmitDate**: 2026-04-22                           | **statusModule.lastUpdateSubmitDate**: 2026-06-10                   |
| 2026-06-12 04&#58;04&#58;21 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-23                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-11          |
