---
title: "NCT05101070 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|:----------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-03-19 02&#58;24&#58;59 | **statusModule.statusVerifiedDate**: 2025-04                                                                                                                                                                                                                                                                                                                                                                                                                                       | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-19 02&#58;24&#58;59 | **statusModule.primaryCompletionDateStruct.date**: 2027-04-16                                                                                                                                                                                                                                                                                                                                                                                                                      | **statusModule.primaryCompletionDateStruct.date**: 2028-05-31                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | **statusModule.completionDateStruct.date**: 2027-04-16                                                                                                                                                                                                                                                                                                                                                                                                                             | **statusModule.completionDateStruct.date**: 2028-05-31                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | **statusModule.lastUpdateSubmitDate**: 2025-05-22                                                                                                                                                                                                                                                                                                                                                                                                                                  | **statusModule.lastUpdateSubmitDate**: 2026-03-16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | **statusModule.lastUpdatePostDateStruct.date**: 2025-05-28                                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Field &#96;descriptionModule.briefSummary&#96; changed from &#96;The primary objective of Part A is to evaluate the safety and tolerability of S-531011 and to determine the maximum tolerated dose (MTD) and/or recommended Phase 2 dose (RP2D) of S-531011.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | The primary objective of Parts B and C is to evaluate the antitumor activity of S-531011 at the RP2D.&#96; to &#96;The primary objective of Part A is to evaluate the safety and tolerability of S-531011 and to determine the maximum tolerated dose (MTD) and/or recommended Phase 2 dose (RP2D) of S-531011 with or without pembrolizumab.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | The primary objective of Parts B and C is to evaluate the antitumor activity of S-531011 at the RP2D with or without pembrolizumab.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | The primary objective of Parts D and E is to evaluate the antitumor activity of S-531011 at the RP2D in combination with bevacizumab with our without pembrolizumab.&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-19 02&#58;24&#58;59 | **designModule.enrollmentInfo.count**: 274                                                                                                                                                                                                                                                                                                                                                                                                                                         | **designModule.enrollmentInfo.count**: 282                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-19 02&#58;24&#58;59 | **outcomesModule.secondaryOutcomes.&#91;0&#93;timeFrame**: Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part A-1&#93;; Approximately 24 months &#91;Part A-2&#93;)                                                                                                                                                                                                                                   | **outcomesModule.secondaryOutcomes.&#91;0&#93;timeFrame**: Every 6 weeks for the ﬁrst 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part A-1&#93;; Approximately 24 months &#91;Part A-2&#93;)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | **outcomesModule.secondaryOutcomes.&#91;5&#93;measure**: Serum concentrations of S-531011                                                                                                                                                                                                                                                                                                                                                                                          | **outcomesModule.secondaryOutcomes.&#91;5&#93;measure**: Parts B, C, D, E&#58; Number of Participants with Treatment-emergent Adverse Events (TEAEs)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-19 02&#58;24&#58;59 | **outcomesModule.secondaryOutcomes.&#91;5&#93;timeFrame**: Part A&#58; Cycle 1, Days 8 and 15 (4 hours post infusion); Cycles 2-9, Day 1 (pre- and end-of-infusion); Safety Follow-up Visit. Parts B and C&#58; Day 1 of Cycles 1-9 (pre- and end-of-infusion); Safety Follow-up Visit. (each cycle is 21 days)                                                                                                                                                                    | **outcomesModule.secondaryOutcomes.&#91;5&#93;timeFrame**: Approximately 12 months (Part B); Approximately 24 months (Parts C, D, E)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Key Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1. Male or female participant must be at least 18 years of age inclusive (or complies with country-specific regulatory requirements), at the time of signing the informed consent.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 2. Participants with histologically or cytologically confirmed advanced (locoregionally recurrent, not amenable to curative therapy) or metastatic solid tumors who have no standard therapies with a proven clinical benefit, or who are intolerant to or unwilling to receive these therapies for any reasons.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 3. Measurable disease by Response Evaluation Criteria in Solid Tumors version 1.1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 4. (Part A only) Participants should have 1 of the following tumor types&#58; malignant melanoma, head and neck squamous cell carcinoma, renal cell carcinoma, urothelial carcinoma, non-small cell lung cancer, or triple-negative breast cancer, esophageal cancer (esophageal squamous cell carcinoma and adenocarcinoma), or gastric cancer (gastric and gastroesophageal junction adenocarcinoma). Participants with colorectal cancer (CRC), pancreatic cancer, cervical cancer, epithelial ovarian cancer, and other types of solid tumors may also be enrolled upon discussion with and approval by the sponsor. For the backfill cohorts only, specific tumor types may be selected.                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 5. (Part B CRC cohorts only) Participants must have histologically or cytologically confirmed adenocarcinoma of the colon or rectum, who had disease progression on or after receiving all of the following standard of care systemic therapies for advanced or metastatic disease or who were intolerant to&#58; fluoropyrimidine, oxaliplatin, and irinotecan; anti-epidermal growth factor receptor (EGFR) therapy if rat sarcoma virus (RAS) (Kirsten RAS/neuroblastoma RAS &#92;&#91;KRAS/NRAS&#92;&#93;) wild-type; V-raf murine sarcoma viral oncogene homolog B (BRAF) inhibitor if BRAF V600E mutation. In addition, participants who received up to 2 additional lines of therapy for advanced or metastatic disease of the following therapies are also eligible&#58; trifluridine/tipiracil, regorafenib, fruquintinib, other drugs approved in the country, or investigational drugs.                                    |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 6. (Part C CRC cohorts only) Participants must have histologically or cytologically confirmed adenocarcinoma of the colon or rectum, who had disease progression on or after receiving all of the following standard of care systemic therapies for advanced or metastatic disease or who were intolerant to&#58; fluoropyrimidine, oxaliplatin, and irinotecan; anti-EGFR therapy if RAS (KRAS/NRAS) wild-type; BRAF inhibitor if BRAF V600E mutation. In addition, participants who received up to 2 additional lines of therapy for advanced or metastatic disease of the following therapies are also eligible&#58; trifluridine/tipiracil, regorafenib, fruquintinib, other drugs approved in the country, or investigational drugs.                                                                                                                                                                                             |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 7. Participants should be willing and able to provide permission to access archival formalin-fixed paraffin-embedded tumor tissues (as block or unstained slides) for this study.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 8. Participants should be willing and able to provide both pre-treatment and on-treatment paired tumor biopsy samples.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 9. (At selected sites only) Participants should be willing and able to provide both pre-treatment and on-treatment paired tumor biopsy samples. Fresh tissue samples are required as these will be used for the proof of mechanism (flow cytometry) analysis.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 10. Eastern Cooperative Oncology Group Performance Status of 0 or 1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 11. An estimated life expectancy of at least 12 weeks.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 12. Adequate hematologic and organ function as confirmed by laboratory values.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 13. QT interval corrected with the Fridericia formula ≤ 480 milliseconds in 12-lead electrocardiogram at Screening.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Key Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1. Presence or history of autoimmune diseases or immune-mediated diseases that require chronic use of systemic corticosteroids (&#92;&gt; 10 milligrams of prednisone equivalent per day), immunosuppressive agents, or disease-modifying agents.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 2. Presence or history of interstitial lung disease and (non-infectious) pneumonitis that required corticosteroids.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 3. Active clinically significant bacterial, viral or fungal infection, or any major episode of infection requiring hospitalization or treatment with parenteral anti-infectives within 4 weeks before the first dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 4. Uncontrolled or clinically significant cardiovascular disease defined as New York Heart Association classification III or IV.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 5. A positive test for hepatitis B surface antigen and/or hepatitis C virus (HCV) antibody (participants with positive HCV antibody are eligible if a confirmatory HCV RNA test is undetectable).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 6. A positive serological test for human immunodeficiency virus infection.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 7. Known history of any other relevant congenital or acquired immunodeficiency.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 8. Known history of an allogeneic tissue and/or solid organ transplant.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 9. Known history of severe allergy, hypersensitivity, anaphylaxis, or any serious adverse reaction to any component of study intervention or formulation components and/or any other monoclonal antibodies.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 10. Women who are pregnant or breastfeeding (or have discontinued breastfeeding) or trying to become pregnant.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 11. Clinical evidence of uncontrolled brain metastasis.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 12. Clinically uncontrollable symptomatic pleural effusion and/or ascites. (Participants who do not require fluid drainage or have no significant increase of fluid for 28 days may be eligible with approval by the sponsor.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 13. Known additional malignancy that is progressing or has required active treatment within the past 3 years.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 14. (Part B and C CRC cohorts only)&#58; Colorectal cancer with mismatch repair deficient/microsatellite instability-high status.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 15. (Parts A-2 and C only)&#58; Has received prior therapy with an anti-programmed death 1, anti-programmed death ligand 1, or anti-programmed death ligand 2 agent or with an agent directed to another stimulatory or co-inhibitory T-cell receptor (for example, cytotoxic T-lymphocyte-associated protein 4, OX-40, CD137), and was discontinued from that treatment due to ≥ Grade 3 immune-related adverse event.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 16. Prior treatment with systemic anticancer drugs (including any investigational medicinal products) within 28 days or 5 half-lives (whichever is shorter) before the first dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 17. Prior major surgery within 28 days before the first dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 18. Prior extended field radiotherapy within 28 days before the first dose of study intervention (within 14 days for limited field radiation for palliation) or history of radiation pneumonitis.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 19. Participants who have not recovered from any previous treatment toxicities to ≤ Grade 1 or baseline (except alopecia and peripheral neuropathy) before the first dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 20. Prior treatment with anti-CCR8 antibody for any indication.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 21. Receipt of hematopoietic growth factors (for example, granulocyte-colony stimulating factor or erythropoietin) within 14 days before the first dose of study intervention or blood transfusions within 14 days before the first dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 22. Receipt of a live, attenuated vaccine within 30 days before the first dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Note&#58; Additional inclusion/exclusion criteria may apply, per protocol.&#96; to &#96;Eligibility Criteria&#58; Key Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1. Participants with histologically or cytologically conﬁrmed advanced (locoregionally recurrent, not amenable to curative therapy) or metastatic solid tumors who have no standard therapies with a proven clinical beneﬁt, or who are intolerant to or unwilling to receive these therapies for any reasons.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 2. Measurable disease by Response Evaluation Criteria in Solid Tumors version 1.1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 3. (Part A only) Participants should have 1 of the following tumor types&#58; malignant melanoma, head and neck squamous cell carcinoma, renal cell carcinoma, urothelial carcinoma, non-small cell lung cancer, or triple-negative breast cancer, esophageal cancer (esophageal squamous cell carcinoma and adenocarcinoma), or gastric cancer (gastric and gastroesophageal junction adenocarcinoma). Participants with colorectal cancer (CRC), pancreatic cancer, cervical cancer, epithelial ovarian cancer, and other types of solid tumors may also be enrolled upon discussion with and approval by the sponsor. For the backﬁll cohorts only, speciﬁc tumor types may be selected.                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 4. (Part B CRC cohorts only) Participants must have histologically or cytologically conﬁrmed metastatic adenocarcinoma of the colon or rectum, who had disease progression on or after receiving all of the following standard of care systemic therapies for advanced or metastatic disease or who were intolerant to&#58; ﬂuoropyrimidine, oxaliplatin, and irinotecan; anti-epidermal growth factor receptor (EGFR) therapy if rat sarcoma virus (RAS) (Kirsten RAS/neuroblastoma RAS &#92;&#91;KRAS/NRAS&#92;&#93;) wild-type and medically appropriate ; V-raf murine sarcoma viral oncogene homolog B (BRAF) inhibitor if BRAF V600E mutation. In addition, participants who received up to 2 additional lines of therapy for advanced or metastatic disease of the following therapies are also eligible&#58; triﬂuridine/tipiracil, regorafenib, fruquintinib, other drugs approved in the country, or investigational drugs. |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 5. (Part C CRC cohorts only) Participants must have histologically or cytologically conﬁrmed metastatic adenocarcinoma of the colon or rectum, who had disease progression on or after receiving all of the following standard of care systemic therapies for advanced or metastatic disease or who were intolerant to&#58; ﬂuoropyrimidine, oxaliplatin, and irinotecan; anti-EGFR therapy if RAS (KRAS/NRAS) wild-type and medically appropriate ; BRAF inhibitor if BRAF V600E mutation. In addition, participants who received up to 2 additional lines of therapy for advanced or metastatic disease of the following therapies are also eligible&#58; triﬂuridine/tipiracil, regorafenib, fruquintinib, other drugs approved in the country, or investigational drugs.                                                                                                                                                          |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 6. (Parts D and E) Participants must have histologically or cytologically conﬁrmed metastatic adenocarcinoma of the colon or rectum, who had disease progression on or after receiving all of the following standard of care systemic therapies for advanced or metastatic disease or who were intolerant to&#58; fluoropyrimidine, oxaliplatin, and irinotecan; anti-EGFR therapy if RAS (KRAS/NRAS) wild-type and medically appropriate; BRAF inhibitor if BRAF-V600E mutation.. In addition, participants who received up to 2 additional lines of therapy for advanced or metastatic disease of the following therapies are also eligible&#58; triﬂuridine/tipiracil, regorafenib, fruquintinib, other drugs approved in the country, or investigational drugs.                                                                                                                                                                   |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 7. Participants should be willing and able to provide permission to access archival formalin-ﬁxed paraffin-embedded tumor tissues (as block or unstained slides) for this study.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 8. Participants should be willing and able to provide both pre-treatment and on-treatment paired tumor biopsy samples.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 9. (Part A and B/CRC Cohorts only; At selected sites only) Participants should be willing and able to provide both pre-treatment and on-treatment paired tumor biopsy samples. Fresh tissue samples are required as these will be used for the proof of mechanism (ﬂow cytometry) analysis.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 10. Eastern Cooperative Oncology Group Performance Status of 0 or 1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 11. An estimated life expectancy of at least 12 weeks.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 12. Adequate hematologic and organ function as conﬁrmed by laboratory values.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 13. QT interval corrected with the Fridericia formula ≤ 480 milliseconds in 12- lead electrocardiogram at Screening.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Key Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1. Presence or history of autoimmune diseases or immune-mediated diseases that require chronic use of systemic corticosteroids (&#92;&gt; 10 milligrams of prednisone equivalent per day), immunosuppressive agents, or disease-modifying agents.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 2. Presence or history of interstitial lung disease and (non-infectious) pneumonitis that required corticosteroids.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 3. Active clinically signiﬁcant bacterial, viral or fungal infection, or any major episode of infection requiring hospitalization or treatment with parenteral anti-infectives within 4 weeks before the ﬁrst dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 4. Uncontrolled or clinically signiﬁcant cardiovascular disease deﬁned as New York Heart Association classiﬁcation III or IV.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 5. A positive test for hepatitis B surface antigen and/or hepatitis C virus (HCV) antibody (participants with positive HCV antibody are eligible if a conﬁrmatory HCV RNA test is undetectable).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 6. A positive serological test for human immunodeﬁciency virus infection.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 7. Known history of any other relevant congenital or acquired immunodeﬁciency.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 8. Known history of an allogeneic tissue and/or solid organ transplant.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 9. Known history of severe allergy, hypersensitivity, anaphylaxis, or any serious adverse reaction to any component of study intervention or formulation components and/or any other monoclonal antibodies.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 10. Women who are pregnant or breastfeeding (or have discontinued breastfeeding) or trying to become pregnant.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 11. (Parts D and E only) Serious non-healing wound, non-healing ulcer, or non healing bone fracture.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 12. (Parts D and E only) Presence or history of severe arterial thromboembolic events (for example, cerebral infarction, transient ischemic attacks, myocardial infarction, and angina) within 6 months prior to the ﬁrst dose of study intervention, and/or ≥ Grade 3 venous thromboembolic events (for example, deep vein thrombosis) within 3 months prior to the ﬁrst dose of study intervention. Participants who receive a full-dose therapeutic anticoagulation should be excluded.                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 13. (Parts D and E only) Known coagulopathy that increases risk of bleeding, bleeding diatheses, or any other hemorrhage/bleeding event of ≥ Grade 3 within 4 weeks prior to the ﬁrst dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 14. (Parts D and E only) Presence or history of any life-threatening vascular endothelial growth factor (VEGF)-related adverse event (AE).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 15. (Parts D and E only) Proteinuria ≥ 2+ by urine dipstick test within 4 weeks prior to the ﬁrst dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 16. Clinical evidence of uncontrolled brain metastasis.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 17. Clinically uncontrollable symptomatic pleural effusion and/or ascites. (Participants who do not require ﬂuid drainage or have no signiﬁcant increase of ﬂuid for 28 days may be eligible with approval by the sponsor.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 18. Known additional malignancy that is progressing or has required active treatment within the past 3 years.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 19. (Part B, C, D and E CRC cohorts only)&#58; Colorectal cancer with mismatch repair deﬁcient/microsatellite instability-high status.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 20. (Parts A-2, C and E only)&#58; Has received prior therapy with an anti-programmed death 1, anti-programmed death ligand 1, or anti-programmed death ligand 2 agent or with an agent directed to another stimulatory or co-inhibitory T-cell receptor (for example, cytotoxic T-lymphocyte-associated protein 4, OX-40, CD137), and was discontinued from that treatment due to ≥ Grade 3 immune-related adverse event.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 21. Prior treatment with systemic anticancer drugs (including any investigational medicinal products) within 28 days or 5 half-lives (whichever is shorter) before the ﬁrst dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 22. Prior major surgery within 28 days before the ﬁrst dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 23. Prior extended ﬁeld radiotherapy within 28 days before the ﬁrst dose of study intervention (within 14 days for limited ﬁeld radiation for palliation) or history of radiation pneumonitis.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 24. Participants who have not recovered from any previous treatment toxicities to ≤ Grade 1 or baseline (except alopecia and peripheral neuropathy) before the ﬁrst dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 25. Prior treatment with anti-CCR8 antibody for any indication.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 26. Receipt of hematopoietic growth factors (for example, granulocyte-colony stimulating factor or erythropoietin) within 14 days before the ﬁrst dose of study intervention or blood transfusions within 14 days before the ﬁrst dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 27. (Parts D and E only) Presence or history of allergic reactions or hypersensitivity to bevacizumab or any of its excipients.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 28. (Parts D and E only) Presence or history of hypersensitivity to Chinese Hamster Ovary cell products or other recombinant human or humanized antibodies.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 29. Receipt of a live, attenuated vaccine within 30 days before the ﬁrst dose of study intervention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Note&#58; Additional protocol deﬁned Inclusion/Exclusion criteria may apply.&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | **contactsLocationsModule.locations.&#91;0&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                | **contactsLocationsModule.locations.&#91;0&#93;status**: ACTIVE_NOT_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-19 02&#58;24&#58;59 | **contactsLocationsModule.locations.&#91;2&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                | **contactsLocationsModule.locations.&#91;2&#93;status**: ACTIVE_NOT_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.interventions.&#91;0&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;S-531011&#x27;, &#x27;description&#x27;&#58; &#x27;Administered by intravenous infusion&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Part A-1&#58; S-531011 Monotherapy&#x27;, &#x27;Part A-2&#58; S-531011 + Pembrolizumab&#x27;, &#x27;Part B&#58; S-531011 Monotherapy&#x27;, &#x27;Part C&#58; S-531011 + Pembrolizumab&#x27;&#93;&#125; | **armsInterventionsModule.interventions.&#91;0&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;S-531011&#x27;, &#x27;description&#x27;&#58; &#x27;Administered by intravenous infusion&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Part A-1&#58; S-531011 Monotherapy&#x27;, &#x27;Part A-2&#58; S-531011 + Pembrolizumab&#x27;, &#x27;Part B&#58; S-531011 Monotherapy&#x27;, &#x27;Part C&#58; S-531011 + Pembrolizumab&#x27;, &#x27;Part D&#58; S-531011 + Bevacizumab&#x27;, &#x27;Part E&#58; S-531011 + Bevacizumab + Pembrolizumab&#x27;&#93;&#125;                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-19 02&#58;24&#58;59 | **outcomesModule.primaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B and C&#58; Objective Response Rate&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part B&#93;; Approximately 24 months &#91;Part C&#93;)&#x27;&#125;                                                                                                              | **outcomesModule.primaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B, C, D, E&#58; Objective Response Rate&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part B&#93;; Approximately 24 months &#91;Parts C, D, E&#93;)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | **outcomesModule.primaryOutcomes.&#91;5&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B and C&#58; Progression-free Survival&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part B&#93;; Approximately 24 months &#91;Part C&#93;)&#x27;&#125;                                                                                                            | **outcomesModule.primaryOutcomes.&#91;5&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B, C, D, E&#58; Progression-free Survival&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part B&#93;; Approximately 24 months &#91;Parts C, D, E&#93;)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.interventions.&#91;1&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Pembrolizumab&#x27;, &#x27;description&#x27;&#58; &#x27;Administered by intravenous infusion&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Part A-2&#58; S-531011 + Pembrolizumab&#x27;, &#x27;Part C&#58; S-531011 + Pembrolizumab&#x27;&#93;, &#x27;otherNames&#x27;&#58; &#91;&#x27;KEYTRUDA&#x27;&#93;&#125;                              | **armsInterventionsModule.interventions.&#91;1&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Pembrolizumab&#x27;, &#x27;description&#x27;&#58; &#x27;Administered by intravenous infusion&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Part A-2&#58; S-531011 + Pembrolizumab&#x27;, &#x27;Part C&#58; S-531011 + Pembrolizumab&#x27;, &#x27;Part E&#58; S-531011 + Bevacizumab + Pembrolizumab&#x27;&#93;, &#x27;otherNames&#x27;&#58; &#91;&#x27;KEYTRUDA&#x27;&#93;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-19 02&#58;24&#58;59 | **outcomesModule.primaryOutcomes.&#91;6&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B and C&#58; Overall Survival&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From first dose to death, or up to a maximum of 18 months after last dose in the last participant&#x27;&#125;                                                                                                                                                                                                     | **outcomesModule.primaryOutcomes.&#91;6&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B, C, D, E&#58; Overall Survival&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part B&#93;; Approximately 24 months &#91;Parts C, D, E&#93;)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-19 02&#58;24&#58;59 | **outcomesModule.primaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B and C&#58; Duration of Response&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part B&#93;; Approximately 24 months &#91;Part C&#93;)&#x27;&#125;                                                                                                                 | **outcomesModule.primaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B, C, D, E&#58; Duration of Response&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part B&#93;; Approximately 24 months &#91;Parts C, D, E&#93;)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-19 02&#58;24&#58;59 | **outcomesModule.primaryOutcomes.&#91;3&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B and C&#58; Disease Control Rate&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part B&#93;; Approximately 24 months &#91;Part C&#93;)&#x27;&#125;                                                                                                                 | **outcomesModule.primaryOutcomes.&#91;3&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B, C, D, E&#58; Disease Control Rate&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part B&#93;; Approximately 24 months &#91;Parts C, D, E&#93;)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-19 02&#58;24&#58;59 | **outcomesModule.primaryOutcomes.&#91;4&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B and C&#58; Time to Response&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part B&#93;; Approximately 24 months &#91;Part C&#93;)&#x27;&#125;                                                                                                                     | **outcomesModule.primaryOutcomes.&#91;4&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Parts B, C, D, E&#58; Time to Response&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Every 6 weeks for the first 24 weeks and every 9 weeks thereafter, until disease progression (Approximately 12 months &#91;Part B&#93;; Approximately 24 months &#91;Parts C, D, E&#93;)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
