---
title: "NCT07205718 Change History"
---

| Timestamp                   | Before                                                                                      | After                                                                                                     |
|:----------------------------|:--------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------|
| 2026-02-10 07&#58;03&#58;39 | **statusModule.statusVerifiedDate**: 2025-11                                                | **statusModule.statusVerifiedDate**: 2026-02                                                              |
| 2026-02-10 07&#58;03&#58;39 | **statusModule.lastUpdateSubmitDate**: 2025-11-28                                           | **statusModule.lastUpdateSubmitDate**: 2026-02-04                                                         |
| 2026-02-10 07&#58;03&#58;39 | **statusModule.lastUpdatePostDateStruct.date**: 2025-12-01                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-06                                                |
| 2026-02-10 07&#58;03&#58;39 | **contactsLocationsModule.locations.&#91;2&#93;status**: NOT_YET_RECRUITING                 | **contactsLocationsModule.locations.&#91;2&#93;status**: RECRUITING                                       |
| 2026-02-10 07&#58;03&#58;39 | **contactsLocationsModule.locations.&#91;4&#93;status**: NOT_YET_RECRUITING                 | **contactsLocationsModule.locations.&#91;4&#93;status**: RECRUITING                                       |
| 2026-02-10 07&#58;03&#58;39 | **contactsLocationsModule.locations.&#91;10&#93;status**: NOT_YET_RECRUITING                | **contactsLocationsModule.locations.&#91;10&#93;status**: RECRUITING                                      |
| 2026-03-26 02&#58;29&#58;47 | **statusModule.statusVerifiedDate**: 2026-02                                                | **statusModule.statusVerifiedDate**: 2026-03                                                              |
| 2026-03-26 02&#58;29&#58;47 | **statusModule.lastUpdateSubmitDate**: 2026-02-04                                           | **statusModule.lastUpdateSubmitDate**: 2026-03-24                                                         |
| 2026-03-26 02&#58;29&#58;47 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-06                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-25                                                |
| 2026-03-26 02&#58;29&#58;47 | **contactsLocationsModule.locations.&#91;7&#93;status**: NOT_YET_RECRUITING                 | **contactsLocationsModule.locations.&#91;7&#93;status**: RECRUITING                                       |
| 2026-03-26 02&#58;29&#58;47 | **contactsLocationsModule.locations.&#91;9&#93;status**: NOT_YET_RECRUITING                 | **contactsLocationsModule.locations.&#91;9&#93;status**: RECRUITING                                       |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.statusVerifiedDate**: 2026-03                                                | **statusModule.statusVerifiedDate**: 2026-05                                                              |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.lastUpdateSubmitDate**: 2026-03-24                                           | **statusModule.lastUpdateSubmitDate**: 2026-05-20                                                         |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-25                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-22                                                |
| 2026-05-26 02&#58;38&#58;39 | **contactsLocationsModule.locations.&#91;1&#93;status**: NOT_YET_RECRUITING                 | **contactsLocationsModule.locations.&#91;1&#93;status**: RECRUITING                                       |
| 2026-05-26 02&#58;38&#58;39 | **contactsLocationsModule.locations.&#91;6&#93;status**: NOT_YET_RECRUITING                 | **contactsLocationsModule.locations.&#91;6&#93;status**: RECRUITING                                       |
| 2026-05-26 02&#58;38&#58;39 | **contactsLocationsModule.locations.&#91;7&#93;facility**: Case Comprehensive Cancer Center | **contactsLocationsModule.locations.&#91;7&#93;facility**: University Hospitals Cleveland Medical Center  |
| 2026-05-26 02&#58;38&#58;39 | **contactsLocationsModule.locations.&#91;8&#93;status**: NOT_YET_RECRUITING                 | **contactsLocationsModule.locations.&#91;8&#93;status**: RECRUITING                                       |
| 2026-06-06 03&#58;35&#58;39 | **statusModule.statusVerifiedDate**: 2026-05                                                | **statusModule.statusVerifiedDate**: 2026-06                                                              |
| 2026-06-06 03&#58;35&#58;39 | **statusModule.lastUpdateSubmitDate**: 2026-05-20                                           | **statusModule.lastUpdateSubmitDate**: 2026-06-04                                                         |
| 2026-06-06 03&#58;35&#58;39 | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-22                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-05                                                |
| 2026-06-06 03&#58;35&#58;39 | **contactsLocationsModule.locations.&#91;0&#93;status**: NOT_YET_RECRUITING                 | **contactsLocationsModule.locations.&#91;0&#93;status**: RECRUITING                                       |
| 2026-06-16 04&#58;16&#58;42 | **statusModule.lastUpdateSubmitDate**: 2026-06-04                                           | **statusModule.lastUpdateSubmitDate**: 2026-06-12                                                         |
| 2026-06-16 04&#58;16&#58;42 | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-05                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-15                                                |
| 2026-06-16 04&#58;16&#58;42 | **contactsLocationsModule.locations.&#91;3&#93;contacts.&#91;0&#93;email**: vklam@jhmi.edu  | **contactsLocationsModule.locations.&#91;3&#93;contacts.&#91;0&#93;email**: ThoracicCancerTrials@jhmi.edu |
