---
title: "NCT05574335 Change History"
---

| Timestamp                   | Before                                                                                                                         | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|:----------------------------|:-------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-12 14&#58;01&#58;39 | **statusModule.statusVerifiedDate**: 2026-01                                                                                   | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-02-12 14&#58;01&#58;39 | **statusModule.lastUpdateSubmitDate**: 2026-01-05                                                                              | **statusModule.lastUpdateSubmitDate**: 2026-02-10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-02-12 14&#58;01&#58;39 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-06                                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-07-29 02&#58;40&#58;59 | **statusModule.statusVerifiedDate**: 2026-02                                                                                   | **statusModule.statusVerifiedDate**: 2026-06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-29 02&#58;40&#58;59 | **statusModule.startDateStruct.date**: 2023-04-26                                                                              | **statusModule.startDateStruct.date**: 2023-05-18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-07-29 02&#58;40&#58;59 | **statusModule.lastUpdateSubmitDate**: 2026-02-10                                                                              | **statusModule.lastUpdateSubmitDate**: 2026-06-30                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-07-29 02&#58;40&#58;59 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-11                                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-07-28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-07-29 02&#58;40&#58;59 | **outcomesModule.primaryOutcomes.&#91;0&#93;measure**: Number of Participants with a T cell phenotype signature response       | **outcomesModule.primaryOutcomes.&#91;0&#93;measure**: Number of Participants With a T Cell Phenotype Signature Response                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-29 02&#58;40&#58;59 | -                                                                                                                              | Field &#96;outcomesModule.primaryOutcomes.&#91;0&#93;description&#96; changed from &#96;Evaluating four siplizumab dosing regimens for induction of a T cell phenotype signature is based on a 20% increase or greater from baseline in PD1+TIGIT+ frequency within circulating CD4 Tem and a 75% increase or greater from baseline in the CD4 Treg/Tem ratio in blood.                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-29 02&#58;40&#58;59 | -                                                                                                                              | The two criteria will be evaluated at weeks 2, 4, 8, and 12. An individual who achieves both signature criteria at any time point on or before week 12 is counted as having the signature response. Both criteria do not need to be achieved at the same time point.&#96; to &#96;A participant is defined as achieving a T Cell phenotype signature response if the participant experiences both a 75% increase or greater from baseline in the CD4 Treg/Tem ratio in blood and a 20% increase or greater from baseline in PD1+TIGIT+ frequency within circulating CD4 Tem. The two criteria will be evaluated at weeks 2, 4, 8, and 12. Both criteria do not need to be achieved at the same time point.&#96; |
| 2026-07-29 02&#58;40&#58;59 | **outcomesModule.primaryOutcomes.&#91;0&#93;timeFrame**: From week 0 (baseline) to week 12                                     | **outcomesModule.primaryOutcomes.&#91;0&#93;timeFrame**: Week 0 to Week 12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-07-29 02&#58;40&#58;59 | **outcomesModule.secondaryOutcomes.&#91;0&#93;measure**: Frequency of Adverse Events (AEs) in all siplizumab dosing arms       | **outcomesModule.secondaryOutcomes.&#91;0&#93;measure**: Frequency of Adverse Events (AEs) in All Siplizumab Dosing Arms                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-29 02&#58;40&#58;59 | **outcomesModule.secondaryOutcomes.&#91;1&#93;measure**: Mixed Meal Tolerance Test (MMTT)-stimulated mean 2-hour C-peptide AUC | **outcomesModule.secondaryOutcomes.&#91;1&#93;measure**: Mixed Meal Tolerance Test (MMTT)-Stimulated Mean 2-hour C-peptide AUC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-29 02&#58;40&#58;59 | **outcomesModule.secondaryOutcomes.&#91;2&#93;measure**: Insulin use (U/kg/day)                                                | **outcomesModule.secondaryOutcomes.&#91;2&#93;measure**: Insulin Use (U/kg/Day)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-07-29 02&#58;40&#58;59 | -                                                                                                                              | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;resultsFirstSubmitDate&#x27;&#93;** (Added)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-29 02&#58;40&#58;59 | -                                                                                                                              | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;resultsFirstSubmitQcDate&#x27;&#93;** (Added)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-07-29 02&#58;40&#58;59 | -                                                                                                                              | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;resultsFirstPostDateStruct&#x27;&#93;** (Added)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
