---
title: "NCT05537740 Change History"
---

| Timestamp                   | Before                                                                                                                      | After                                                                                                                               |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-12 14&#58;01&#58;36 | **root&#91;&#x27;referencesModule&#x27;&#93;&#91;&#x27;seeAlsoLinks&#x27;&#93;** (Removed)                                  | -                                                                                                                                   |
| 2026-02-24 00&#58;57&#58;04 | **statusModule.statusVerifiedDate**: 2026-01                                                                                | **statusModule.statusVerifiedDate**: 2026-02                                                                                        |
| 2026-02-24 00&#58;57&#58;04 | **statusModule.lastUpdateSubmitDate**: 2026-01-21                                                                           | **statusModule.lastUpdateSubmitDate**: 2026-02-20                                                                                   |
| 2026-02-24 00&#58;57&#58;04 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-22                                                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-23                                                                          |
| 2026-02-24 00&#58;57&#58;04 | **contactsLocationsModule.locations.&#91;20&#93;facility**: Clinica Universidad De Navarra &#124; Oncologia Medica          | **contactsLocationsModule.locations.&#91;20&#93;facility**: Clinica Universidad de Navarra &#124; Pamplona &#124; Oncologia         |
| 2026-02-24 00&#58;57&#58;04 | **contactsLocationsModule.locations.&#91;22&#93;facility**: Clinica Universidad De Navarra &#124; Oncologia Medica          | **contactsLocationsModule.locations.&#91;22&#93;facility**: Clinica Universidad de Navarra &#124; Madrid &#124; Oncologia           |
| 2026-03-21 02&#58;05&#58;09 | **statusModule.statusVerifiedDate**: 2026-02                                                                                | **statusModule.statusVerifiedDate**: 2026-03                                                                                        |
| 2026-03-21 02&#58;05&#58;09 | **statusModule.primaryCompletionDateStruct.date**: 2026-07-07                                                               | **statusModule.primaryCompletionDateStruct.date**: 2027-04-30                                                                       |
| 2026-03-21 02&#58;05&#58;09 | **statusModule.lastUpdateSubmitDate**: 2026-02-20                                                                           | **statusModule.lastUpdateSubmitDate**: 2026-03-19                                                                                   |
| 2026-03-21 02&#58;05&#58;09 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-23                                                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-20                                                                          |
| 2026-03-21 02&#58;05&#58;09 | **contactsLocationsModule.locations.&#91;20&#93;facility**: Clinica Universidad de Navarra &#124; Pamplona &#124; Oncologia | **contactsLocationsModule.locations.&#91;20&#93;facility**: Clinica Universidad De Navarra &#124; Pamplona &#124; Oncologia         |
| 2026-03-21 02&#58;05&#58;09 | **contactsLocationsModule.locations.&#91;22&#93;facility**: Clinica Universidad de Navarra &#124; Madrid &#124; Oncologia   | **contactsLocationsModule.locations.&#91;22&#93;facility**: Clinica Universidad De Navarra &#124; Madrid &#124; Oncologia           |
| 2026-03-21 02&#58;05&#58;09 | -                                                                                                                           | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;14&#93;&#91;&#x27;state&#x27;&#93;** (Added) |
| 2026-03-21 02&#58;05&#58;09 | -                                                                                                                           | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;13&#93;&#91;&#x27;state&#x27;&#93;** (Added) |
| 2026-03-21 02&#58;05&#58;09 | -                                                                                                                           | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;15&#93;&#91;&#x27;state&#x27;&#93;** (Added) |
| 2026-03-21 02&#58;05&#58;09 | -                                                                                                                           | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;16&#93;&#91;&#x27;state&#x27;&#93;** (Added) |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.statusVerifiedDate**: 2026-03                                                                                | **statusModule.statusVerifiedDate**: 2026-05                                                                                        |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.lastUpdateSubmitDate**: 2026-03-19                                                                           | **statusModule.lastUpdateSubmitDate**: 2026-05-19                                                                                   |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-20                                                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-20                                                                          |
| 2026-05-26 02&#58;38&#58;39 | **contactsLocationsModule.locations.&#91;14&#93;state**: Nouvelle-Aquitaine                                                 | **contactsLocationsModule.locations.&#91;14&#93;state**: New Aquitaine                                                              |
| 2026-06-24 14&#58;19&#58;39 | **statusModule.statusVerifiedDate**: 2026-05                                                                                | **statusModule.statusVerifiedDate**: 2026-06                                                                                        |
| 2026-06-24 14&#58;19&#58;39 | **statusModule.lastUpdateSubmitDate**: 2026-05-19                                                                           | **statusModule.lastUpdateSubmitDate**: 2026-06-18                                                                                   |
| 2026-06-24 14&#58;19&#58;39 | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-20                                                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-22                                                                          |
| 2026-06-24 14&#58;19&#58;39 | -                                                                                                                           | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;12&#93;&#91;&#x27;state&#x27;&#93;** (Added) |
