---
title: "NCT04256421 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|:----------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;52&#93;city**: Napoli                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;52&#93;city**: Naples                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;52&#93;geoPoint.lat**: 40.87618                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | **contactsLocationsModule.locations.&#91;52&#93;geoPoint.lat**: 40.85216                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;52&#93;geoPoint.lon**: 14.5195                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | **contactsLocationsModule.locations.&#91;52&#93;geoPoint.lon**: 14.26811                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-04-04 02&#58;21&#58;52 | **statusModule.statusVerifiedDate**: 2026-01                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-04-04 02&#58;21&#58;52 | **statusModule.lastUpdateSubmitDate**: 2026-01-09                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **statusModule.lastUpdateSubmitDate**: 2026-03-13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-04-04 02&#58;21&#58;52 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.primaryOutcomes.&#91;0&#93;measure**: Investigator-Assessed Progression Free Survival (PFS) in the Primary Analysis Set (PAS)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | **outcomesModule.primaryOutcomes.&#91;0&#93;measure**: Investigator-assessed Progression-free Survival (PFS) in the Primary Analysis Set (PAS)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.primaryOutcomes.&#91;0&#93;description**: PFS was defined as the time from randomization to the first documented disease progression (PD) as determined by the investigator with the use of Response Evaluation Criteria in Solid Tumors (RECIST) v1.1 or death from any cause, whichever occurred first. PD&#58; at least a 20% increase in the sum of diameters (SOD) of target lesions, taking as reference the smallest SOD on study (including baseline). In addition to the relative increase of 20%, the SOD must also demonstrate an absolute increase of &#92;&gt;/&#61; 5 millimeters (mm).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | **outcomesModule.primaryOutcomes.&#91;0&#93;description**: PFS was defined as the time from randomization to the first documented PD as determined by the investigator with the use of Response Evaluation Criteria in Solid Tumors Version 1.1 (RECIST v1.1) or death from any cause, whichever occurred first. PD was defined as at least a 20% increase in the sum of diameters (SOD) of target lesions, taking as reference the smallest SOD on study (including baseline). In addition to the relative increase of 20%, the SOD must also demonstrate an absolute increase of ≥ 5 millimeters (mm).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.primaryOutcomes.&#91;0&#93;timeFrame**: From randomization to the first occurrence of disease progression or death from any cause, whichever occurs first (up to approximately 24 months)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | **outcomesModule.primaryOutcomes.&#91;0&#93;timeFrame**: From randomization to the first occurrence of PD or death from any cause, whichever occurred first (up to approximately 24 months)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;57&#93;city**: Padua                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **contactsLocationsModule.locations.&#91;57&#93;city**: Padova                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;57&#93;geoPoint.lat**: 45.40797                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | **contactsLocationsModule.locations.&#91;57&#93;geoPoint.lat**: 45.26618                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;57&#93;geoPoint.lon**: 11.88586                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | **contactsLocationsModule.locations.&#91;57&#93;geoPoint.lon**: 11.77208                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;13&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;TTCD of EORTC QLQ-C30 GHS/QoL in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;TTCD was the time from randomization until the first confirmed clinically meaningful deterioration in patient-reported global health status (GHS)/ quality of life (QoL). TTCD was determined based on patient-reported GHS/QoL (items 29-30) as collected and measured by the EORTC QLQ-C30. HS/ QoL items are scored on a 7-point scale that ranges from &quot;very poor&quot; to &quot;excellent&quot;. A high score for the GHS/QoL subscale represented a high health related quality of life. The scale was linearly transformed so that each score ranged from 0 to 100. A score change of at least 10-point in GHS/QoL subscale score was perceived by participants as clinically meaningful. Confirmed clinically meaningful deterioration was defined as a clinically meaningful decrease from baseline that was held for at least two consecutive assessments or an initial clinically meaningful decrease from baseline followed by death from any cause within 3 weeks.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization until the first confirmed clinically meaningful deterioration up to 24 months&#x27;&#125;                                                                                                                                        | **outcomesModule.secondaryOutcomes.&#91;13&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;TTCD of EORTC QLQ-C30 GHS/QoL in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;TTCD was the time from randomization until the first confirmed clinically meaningful deterioration in patient-reported GHS/QoL. TTCD was determined based on patient-reported GHS/QoL (Items 29-30) as collected and measured by the EORTC QLQ-C30. GHS/QoL items were scored on a 7-point scale, ranging from &quot;very poor&quot; to &quot;excellent&quot;. A high score for the GHS/QoL subscale represented a high health-related QoL. The scale was linearly transformed so that each score ranged from 0 to 100. A score change of at least 10-point in GHS/QoL subscale score was perceived by participants as clinically meaningful. Confirmed clinically meaningful deterioration was defined as a clinically meaningful decrease from baseline that was held for at least two consecutive assessments or an initial clinically meaningful decrease from baseline followed by death from any cause within 3 weeks.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization until the first confirmed clinically meaningful deterioration (up to approximately 24 months)&#x27;&#125;                                                                                                                                                                                    |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;0&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;PFS in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;PFS was defined as the time from randomization to the first documented PD as determined by the investigator with the use of RECIST v1.1 or death from any cause, whichever occurred first. PD&#58; at least a 20% increase in the SOD of target lesions, taking as reference the smallest SOD on study (including baseline). In addition to the relative increase of 20%, the SOD must also demonstrate an absolute increase of &#92;&#92;&gt;/&#61; 5 mm.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization to the first occurrence of disease progression or death from any cause, whichever occurs first (up to approximately 24 months)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **outcomesModule.secondaryOutcomes.&#91;0&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;PFS in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;PFS was defined as the time from randomization to the first documented PD as determined by the investigator with the use of RECIST v1.1 or death from any cause, whichever occurred first. PD was defined as at least a 20% increase in the SOD of target lesions, taking as reference the smallest SOD on study (including baseline). In addition to the relative increase of 20%, the SOD must also demonstrate an absolute increase of ≥ 5 mm.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization to the first occurrence of PD or death from any cause, whichever occurred first (up to approximately 24 months)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;6&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-Assessed PFS Rates at 6 Months and 12 Months in the PAS&#x27;, &#x27;description&#x27;&#58; &#x27;PFS rate at 6 months and 12 months was defined as the percentage of participants who were event free at these specific time points. Percentages have been rounded off to the nearest decimal point. A point estimate of the event-free rate is a single, numerical value used to approximate the true event-free rate of the entire population at a specific point in time. This value is calculated from ordered data (Event, Censoring) of each patient, using the Kaplan-Meier method, and accounts for censored observations( so Event free rates may not directly be calculated based only on patients remaining at risk).&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Month 6, Month 12&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;6&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-assessed PFS Rates at 6 Months and 12 Months in the PAS&#x27;, &#x27;description&#x27;&#58; &#x27;PFS rate at 6 months and 12 months was defined as the percentage of participants who were event-free at these specific time points. Percentages have been rounded off to the nearest decimal point. A point estimate of the event-free rate was a single, numerical value used to approximate the true event-free rate of the entire population at a specific point in time. This value was calculated from ordered data (Event, Censoring) of each participant, using the Kaplan-Meier (K-M) method, accounting for censored observations (so event-free rates may not directly be calculated based only on participants remaining at risk).&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Month 6, Month 12&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;16&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Cmin of Atezolizumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;At the end of each cycle (each cycle is 21 days) of Cycles 1, 2, 3, 7, 11 and 15 (approximately 11 months)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;16&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Minimum Serum Concentration (Cmin) of Tiragolumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;At the end of Cycles 1, 2, 3, 7, 11 and 15 (approximately 11 months) (1 Cycle&#61;21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;10&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Time to Confirmed Deterioration (TTCD) of European Organisation for Research and Treatment of Cancer (EORTC) Quality of Life Questionnaire-Core (QLQ-C30) Physical Functioning in the PAS&#x27;, &#x27;description&#x27;&#58; &quot;TTCD was the time from randomization until the first confirmed clinically meaningful deterioration in physical functioning. TTCD was determined based on patient-reported physical functioning (items 1-5) as collected and measured by the EORTC QLQ-C30. The PF is measured on 4-point scale (1&#61;&#x27;Not at all&#x27; to 4&#61;&#x27;Very much&#x27;). A high score for the physical function subscale represented a high/healthy level of functioning. The scale was linearly transformed so that each score ranged from 0 to 100. A score change of at least 10-point in physical functioning subscale score was perceived by participants as clinically meaningful. Confirmed clinically meaningful deterioration was defined as a clinically meaningful decrease from baseline that was held for at least two consecutive assessments or an initial clinically meaningful decrease from baseline followed by death from any cause within 3 weeks.&quot;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization until the first confirmed clinically meaningful deterioration up to approximately 24 months&#x27;&#125; | **outcomesModule.secondaryOutcomes.&#91;10&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Time to Confirmed Deterioration (TTCD) of European Organisation for Research and Treatment of Cancer (EORTC) Quality-of-life Questionnaire-Core 30 (QLQ-C30) Physical Functioning (PF) in the PAS&#x27;, &#x27;description&#x27;&#58; &quot;TTCD was the time from randomization until the first confirmed clinically meaningful deterioration in PF. TTCD was determined based on patient-reported PF (Items 1-5) as collected and measured by the EORTC QLQ-C30. The PF was measured on 4-point scale (1&#61;&#x27;Not at all&#x27; to 4&#61;&#x27;Very much&#x27;). A high score for the PF subscale represented a high/healthy level of functioning. The scale was linearly transformed so that each score ranged from 0 to 100. A score change of at least 10-point in PF subscale score was perceived by participants as clinically meaningful. Confirmed clinically meaningful deterioration was defined as a clinically meaningful decrease from baseline that was held for at least two consecutive assessments or an initial clinically meaningful decrease from baseline followed by death from any cause within 3 weeks.&quot;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization until the first confirmed clinically meaningful deterioration (up to approximately 24 months)&#x27;&#125;                                                               |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;15&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Minimum Serum Concentration (Cmin) of Tiragolumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;At the end of each cycle (each cycle is 21 days) of Cycles 1, 2, 3, 7, 11 and 15 (approximately 11 months)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | **outcomesModule.secondaryOutcomes.&#91;15&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Number of Participants With Severity of Cytokine-release Syndrome (CRS), as Determined by the American Society for Transplantation and Cell Therapy (ASTCT) Consensus Grading Scale&#x27;, &#x27;description&#x27;&#58; &#x27;CRS&#61;supraphysiologic response following administration of any immune therapy that results in activation/engagement of endogenous or infused T cells and/or other immune effector cells. Symptoms may be progressive, including fever at onset, and may also include hypotension, capillary leak (hypoxia), and end-organ dysfunction. Severity of CRS was determined per ASTCT Consensus Grading Criteria, which categorizes CRS into 5 grades&#58; Grade 1&#58; Fever (≥38◦Celsius), with/without constitutional symptoms, in absence of hypotension &#92;&#92;&amp; hypoxia; Grade 2&#58; Fever with hypotension not requiring vasopressors and/or hypoxia requiring low-flow oxygen; Grade 3&#58; Fever with hypotension requiring one vasopressor, with/without vasopressin, and/or hypoxia requiring high-flow oxygen; Grade 4&#58; Fever accompanied by hypotension requiring multiple vasopressors (excluding vasopressin) and/or hypoxia requiring positive-pressure ventilation; Grade 5&#58; death due to CRS. Only non zero values have been reported.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to 58 months&#x27;&#125; |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;17&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Maximum Serum Concentration (Cmax) of Tiragolumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Predose and 30 minutes post end of infusion (EOI) on Day 1 of Cycle 1 (each cycle is 21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;17&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Cmin of Atezolizumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;At the end of each Cycles 1, 2, 3, 7, 11 and 15 (approximately 11 months) (1 Cycle&#61;21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;19&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Number of Participants With Anti-Drug Antibodies (ADAs) to Tiragolumab&#x27;, &#x27;description&#x27;&#58; &#x27;Reported here is the number of participants who had a positive ADA assay result at baseline and the number of participants positive for treatment emergent ADAs. The participants positive for treatment emergent ADAs include treatment-induced and treatment-enhanced ADA positive participants. Treatment-induced ADAs are participants with negative or missing baseline ADA result(s) and at least one positive post-baseline ADA result. Treatment-enhanced ADAs are participants with a positive ADA result at baseline who had one or more post-baseline titer results that were at least 0.60 t.u. greater than the baseline titer result. The total number of participants who developed ADAs to tiragolumab was determined by summing the ADA-positive participants across all timepoints.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Predose on Day 1 of Cycles 1 (each cycle is 21 days), 2, 3, 4, 8,12 and 16 and at treatment discontinuation (TD) visit (up to 24 months)&#x27;&#125;                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;19&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Cmax of Atezolizumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Pre-dose and 30 minutes post EOI on Day 1 of Cycle 1 (1 Cycle&#61;21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;14&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Percentage of Participants With Adverse Events&#x27;, &#x27;description&#x27;&#58; &#x27;An adverse event is any untoward medical occurrence in a subject administered a pharmaceutical product and which does not necessarily have to have a causal relationship with the treatment. An adverse event can therefore be any unfavorable and unintended sign (including an abnormal laboratory finding, for example), symptom, or disease temporally associated with the use of a pharmaceutical product, whether or not considered related to the pharmaceutical product. Preexisting conditions which worsen during a study are also considered as adverse events.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to 65 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **outcomesModule.secondaryOutcomes.&#91;14&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Number of Participants With Adverse Events (AEs)&#x27;, &#x27;description&#x27;&#58; &#x27;An AE was defined as any untoward medical occurrence in a participant administered a pharmaceutical product and which does not necessarily have to have a causal relationship with the treatment. An adverse event can therefore be any unfavorable and unintended sign (including an abnormal laboratory finding, for example), symptom, or disease temporally associated with the use of a pharmaceutical product, whether or not considered related to the pharmaceutical product. Pre-existing conditions which worsen during a study were also considered as AEs.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to 58 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;8&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Overall Survival Rates at 12 Months and 24 Months in the PAS&#x27;, &#x27;description&#x27;&#58; &#x27;Overall survival rate at 12 months and 24 months was defined as the percentage of participants who were alive at these specific time points. Percentages have been rounded off to the nearest decimal point. A point estimate of the event-free rate is a single, numerical value used to approximate the true event-free rate of the entire population at a specific point in time. This value is calculated from ordered data (Event, Censoring) of each patient, using the Kaplan-Meier method, and accounts for censored observations( so Event free rates may not directly be calculated based only on patients remaining at risk).&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Month 12, Month 24&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **outcomesModule.secondaryOutcomes.&#91;8&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;OS Rates at 12 Months and 24 Months in the PAS&#x27;, &#x27;description&#x27;&#58; &#x27;OS rate at 12 months and 24 months was defined as the percentage of participants who were alive at these specific time points. Percentages have been rounded off to the nearest decimal point. A point estimate of the event-free rate was a single, numerical value used to approximate the true event-free rate of the entire population at a specific point in time. This value was calculated from ordered data (Event, Censoring) of each participant, using the K-M method, accounting for censored observations (so event-free rates may not directly be calculated based only on participants remaining at risk).&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Month 12, Month 24&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;18&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Cmax of Atezolizumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Predose and 30 minutes post EOI on Day 1 of Cycle 1 (each cycle is 21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;18&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Maximum Serum Concentration (Cmax) of Tiragolumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Pre-dose and 30 minutes post end of infusion (EOI) on Day 1 of Cycle 1 (1 Cycle&#61;21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;21&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Change From Baseline in EuroQol 5-Dimension, 5-Level (EQ-5D-5L) Index-based and Visual Analog Scale Scores&#x27;, &#x27;description&#x27;&#58; &quot;The EQ-5D-5L is a validated self-report health status questionnaire that was used to calculate a health status utility score for use in health economic analyses. There were two components to the EQ-5D-5L&#58; a five-item health state profile that assessed mobility, self-care, usual activities, pain/discomfort, and anxiety/depression, as well as a visual analog scale (VAS) that measured health state. The EQ VAS records the participant&#x27;s self-rated health on a vertical visual analogue scale ranging from 0 to 100 A single composite score was calculated based on the responses as an indicator of the participant&#x27;s health status. The scale ranges 0-100, 0&#61;worst health and 100&#61;best health.&quot;, &#x27;timeFrame&#x27;&#58; &#x27;From baseline up to 65 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                         | **outcomesModule.secondaryOutcomes.&#91;21&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Number of Participants With ADAs to Atezolizumab&#x27;, &#x27;description&#x27;&#58; &#x27;Participants were considered to be ADA-positive if they were ADA-negative at baseline but developed an ADA response following atezolizumab administration (treatment-induced ADA response), or if they were ADA positive at baseline and the titer of one or more post-baseline samples was greater than the titer of the baseline sample by a scientifically reasonable margin such at least 0.60 t.u. greater than the baseline titer result (treatment-enhanced ADA response). The total number of participants who developed ADAs to tiragolumab was determined by summing the ADA-positive participants across all timepoints.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Pre-dose on Day 1 of Cycles 1, 2, 3, 4, 8,12, 16 and at TD visit (up to 24 months) (1 Cycle&#61;21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;5&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-Assessed DOR in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;DOR was defined as the time from the first occurrence of a documented OR to PD or death from any cause, whichever occurred first, as determined by the investigator with the use of RECIST v1.1. CR&#58; was defined as disappearance of all target lesions or any pathological lymph nodes must have reduction in short axis to &#92;&#92;&lt; 10 mm PR was defined as at least a 30% decrease in the SOD of all target lesions, taking as reference the baseline SOD, in the absence of CR. PD&#61; at least a 20% increase in the SOD of target lesions, taking as reference the smallest SOD on study (including baseline). In addition to the relative increase of 20%, the SOD must also demonstrate an absolute increase of &#92;&#92;&gt;/&#61; 5 mm.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From the first occurrence of a documented confirmed objective response to disease progression or death from any cause, whichever occurs first (up to approximately 24 months)&#x27;&#125;                                                                                                                                                                                                                                                                                       | **outcomesModule.secondaryOutcomes.&#91;5&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-assessed DOR in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;DOR was defined as the time from the first occurrence of a documented OR (CR or PR) to PD or death from any cause, whichever occurred first, as determined by the investigator with the use of RECIST v1.1. CR was defined as disappearance of all target lesions or any pathological lymph nodes (whether target or non-target) must have reduction in short axis to &#92;&#92;&lt; 10 mm. PR was defined as at least a 30% decrease in the SOD of all target lesions, taking as reference the baseline SOD, in the absence of CR. PD was defined as at least a 20% increase in the SOD of target lesions, taking as reference the smallest SOD on study (including baseline). In addition to the relative increase of 20%, the SOD must also demonstrate an absolute increase of ≥ 5 mm.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From the first occurrence of a documented confirmed OR to PD or death from any cause, whichever occurred first (up to approximately 24 months)&#x27;&#125;                                                                                                                                                                                                                                                                                             |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;3&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-Assessed Confirmed ORR in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;ORR was defined as the percentage of participants with CR or PR as determined by the investigator with the use of RECIST v1.1. CR was defined as disappearance of all target lesions or any pathological lymph nodes must have reduction in short axis to &#92;&#92;&lt; 10 mm. PR was defined as at least a 30% decrease in the SOD of all target lesions, taking as reference the baseline SOD, in the absence of CR.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization up to approximately 24 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;3&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-assessed Confirmed ORR in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;ORR was defined as the percentage of participants with CR or PR as determined by the investigator with the use of RECIST v1.1. CR was defined as disappearance of all target lesions or any pathological lymph nodes (whether target or non-target) must have reduction in short axis to &#92;&#92;&lt; 10 mm. PR was defined as at least a 30% decrease in the SOD of all target lesions, taking as reference the baseline SOD, in the absence of CR. Percentages have been rounded off.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization up to approximately 24 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;11&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;TTCD of EORTC QLQ-C30 Physical Functioning in the FAS&#x27;, &#x27;description&#x27;&#58; &quot;TTCD was the time from randomization until the first confirmed clinically meaningful deterioration in physical functioning. TTCD was determined based on patient-reported physical functioning (items 1-5) as collected and measured by the EORTC QLQ-C30. The PF is measured on 4-point scale (1&#61;&#x27;Not at all&#x27; to 4&#61;&#x27;Very much&#x27;). A high score for the physical function subscale represented a high/healthy level of functioning. The scale was linearly transformed so that each score ranged from 0 to 100. A score change of at least 10-point in physical functioning subscale score was perceived by participants as clinically meaningful. Confirmed clinically meaningful deterioration was defined as a clinically meaningful decrease from baseline that was held for at least two consecutive assessments or an initial clinically meaningful decrease from baseline followed by death from any cause within 3 weeks.&quot;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization until the first confirmed clinically meaningful deterioration up to approximately 24 months&#x27;&#125;                                                                                                                                     | **outcomesModule.secondaryOutcomes.&#91;11&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;TTCD of EORTC QLQ-C30 Physical Functioning in the FAS&#x27;, &#x27;description&#x27;&#58; &quot;TTCD was the time from randomization until the first confirmed clinically meaningful deterioration in PF. TTCD was determined based on patient-reported PF (Items 1-5) as collected and measured by the EORTC QLQ-C30. The PF was measured on 4-point scale (1&#61;&#x27;Not at all&#x27; to 4&#61;&#x27;Very much&#x27;). A high score for the PF subscale represented a high/healthy level of functioning. The scale was linearly transformed so that each score ranged from 0 to 100. A score change of at least 10-point in PF subscale score was perceived by participants as clinically meaningful. Confirmed clinically meaningful deterioration was defined as a clinically meaningful decrease from baseline that was held for at least two consecutive assessments or an initial clinically meaningful decrease from baseline followed by death from any cause within 3 weeks.&quot;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization until the first confirmed clinically meaningful deterioration (up to approximately 24 months)&#x27;&#125;                                                                                                                                                                                                           |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;20&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Number of Participants With ADAs to Atezolizumab&#x27;, &#x27;description&#x27;&#58; &#x27;Reported here is the number of participants who had a positive ADA assay result at baseline and the number of participants positive for treatment emergent ADAs. The number of participants positive for treatment emergent ADAs includes treatment-induced and treatment-enhanced ADA positive participants. Treatment-induced ADAs are participants with negative or missing baseline ADA result(s) and at least one positive post-baseline ADA result. Treatment-enhanced ADAs are participants with a positive ADA result at baseline who had one or more post-baseline titer results that were at least 0.60 t.u. greater than the baseline titer result. The total number of participants who developed ADAs to atezolizumab was determined by summing the ADA-positive participants across all timepoints.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Predose on Day 1 of Cycles 1 (each cycle is 21 days), 2, 3, 4, 8,12 and 16 and at TD visit (up to 24 months)&#x27;&#125;                                                                                                                                                                                                                                                                                       | **outcomesModule.secondaryOutcomes.&#91;20&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Number of Participants With Anti-drug Antibodies (ADAs) to Tiragolumab&#x27;, &#x27;description&#x27;&#58; &#x27;Participants were considered to be ADA-positive if they were ADA-negative at baseline but developed an ADA response following tiragolumab administration (treatment-induced ADA response), or if they were ADA positive at baseline and the titer of one or more post-baseline samples was greater than the titer of the baseline sample by a scientifically reasonable margin such at least 0.60 titer unit (t.u.) greater than the baseline titer result (treatment-enhanced ADA response). The total number of participants who developed ADAs to tiragolumab was determined by summing the ADA-positive participants across all timepoints.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Pre-dose on Day 1 of Cycles 1, 2, 3, 4, 8,12, 16 and at treatment discontinuation (TD) visit (up to 24 months) (1 Cycle&#61;21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;7&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-Assessed PFS Rates at 6 Months and 12 Months in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;PFS rate at 6 months and 12 months was defined as the percentage of participants who were event free at these specific time points. Percentages have been rounded off to the nearest decimal point. A point estimate of the event-free rate is a single, numerical value used to approximate the true event-free rate of the entire population at a specific point in time. This value is calculated from ordered data (Event, Censoring) of each patient, using the Kaplan-Meier method, and accounts for censored observations( so Event free rates may not directly be calculated based only on patients remaining at risk).&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Month 6, Month 12&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;7&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-assessed PFS Rates at 6 Months and 12 Months in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;PFS rate at 6 months and 12 months was defined as the percentage of participants who were event-free at these specific time points. Percentages have been rounded off to the nearest decimal point. A point estimate of the event-free rate was a single, numerical value used to approximate the true event-free rate of the entire population at a specific point in time. This value was calculated from ordered data (Event, Censoring) of each participant, using the K-M method, accounting for censored observations (so event-free rates may not directly be calculated based only on participants remaining at risk).&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Month 6, Month 12&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;9&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Overall Survival Rates at 12 Months and 24 Months in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;Overall survival rate at 12 months and 24 months was defined as the percentage of participants who were alive at these specific time points. Percentages have been rounded off to the nearest decimal point. A point estimate of the event-free rate is a single, numerical value used to approximate the true event-free rate of the entire population at a specific point in time. This value is calculated from ordered data (Event, Censoring) of each patient, using the Kaplan-Meier method, and accounts for censored observations( so Event free rates may not directly be calculated based only on patients remaining at risk).&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Month 12, Month 24&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **outcomesModule.secondaryOutcomes.&#91;9&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;OS Rates at 12 Months and 24 Months in the FAS&#x27;, &#x27;description&#x27;&#58; &#x27;OS rate at 12 months and 24 months was defined as the percentage of participants who were alive at these specific time points. Percentages have been rounded off to the nearest decimal point. A point estimate of the event-free rate was a single, numerical value used to approximate the true event-free rate of the entire population at a specific point in time. This value was calculated from ordered data (Event, Censoring) of each participant, using the K-M method, accounting for censored observations (so event-free rates may not directly be calculated based only on participants remaining at risk).&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Month 12, Month 24&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-Assessed Confirmed Objective Response Rate (ORR) in the PAS&#x27;, &#x27;description&#x27;&#58; &#x27;ORR was defined as the percentage of participants with a complete response (CR) or a partial response (PR) as determined by the investigator with the use of RECIST v1.1. CR was defined as disappearance of all target lesions or any pathological lymph nodes must have reduction in short axis to &#92;&#92;&lt; 10 mm. PR was defined as at least a 30% decrease in the SOD of all target lesions, taking as reference the baseline SOD, in the absence of CR.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization up to approximately 24 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **outcomesModule.secondaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-assessed Confirmed Objective Response Rate (ORR) in the PAS&#x27;, &#x27;description&#x27;&#58; &#x27;ORR was defined as the percentage of participants with a complete response (CR) or a partial response (PR) as determined by the investigator with the use of RECIST v1.1. CR was defined as disappearance of all target lesions or any pathological lymph nodes (whether target or non-target) must have reduction in short axis to &#92;&#92;&lt; 10 mm. PR was defined as at least a 30% decrease in the SOD of all target lesions, taking as reference the baseline SOD, in the absence of CR. Percentages have been rounded off.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization up to approximately 24 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;4&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-Assessed Duration of Response (DOR) in the PAS&#x27;, &#x27;description&#x27;&#58; &#x27;DOR was defined as the time from the first occurrence of a documented objective response (OR) to PD or death from any cause, whichever occurred first, as determined by the investigator with the use of RECIST v1.1. CR&#58; was defined as disappearance of all target lesions or any pathological lymph nodes must have reduction in short axis to &#92;&#92;&lt; 10 mm PR was defined as at least a 30% decrease in the SOD of all target lesions, taking as reference the baseline SOD, in the absence of CR. PD&#61; at least a 20% increase in the SOD of target lesions, taking as reference the smallest SOD on study (including baseline). In addition to the relative increase of 20%, the SOD must also demonstrate an absolute increase of &#92;&#92;&gt;/&#61; 5 mm.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From the first occurrence of a documented confirmed objective response to disease progression or death from any cause, whichever occurs first (up to approximately 24 months)&#x27;&#125;                                                                                                                                                                                                                                           | **outcomesModule.secondaryOutcomes.&#91;4&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Investigator-assessed Duration of Response (DOR) in the PAS&#x27;, &#x27;description&#x27;&#58; &#x27;DOR was defined as the time from the first occurrence of a documented OR (CR or PR) to PD or death from any cause, whichever occurred first, as determined by the investigator with the use of RECIST v1.1. CR was defined as disappearance of all target lesions or any pathological lymph nodes (whether target or non-target) must have reduction in short axis to &#92;&#92;&lt; 10 mm. PR was defined as at least a 30% decrease in the SOD of all target lesions, taking as reference the baseline SOD, in the absence of CR. PD was defined as at least a 20% increase in the SOD of target lesions, taking as reference the smallest SOD on study (including baseline). In addition to the relative increase of 20%, the SOD must also demonstrate an absolute increase of ≥ 5 mm.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From the first occurrence of a documented confirmed objective response (OR) to PD or death from any cause, whichever occurred first (up to approximately 24 months)&#x27;&#125;                                                                                                                                                                                                                                                 |
| 2026-04-04 02&#58;21&#58;52 | **outcomesModule.secondaryOutcomes.&#91;12&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;TTCD of EORTC QLQ-C30 Global Health Status (GHS)/Quality of Life (QoL) in the PAS&#x27;, &#x27;description&#x27;&#58; &#x27;TTCD was the time from randomization until the first confirmed clinically meaningful deterioration in patient-reported global health status (GHS)/ quality of life (QoL). TTCD was determined based on patient-reported GHS/QoL (items 29-30) as collected and measured by the EORTC QLQ-C30. HS/QoL items are scored on a 7-point scale that ranges from &quot;very poor&quot; to &quot;excellent&quot;. A high score for the GHS/QoL subscale represented a high health related quality of life. The scale was linearly transformed so that each score ranged from 0 to 100. A score change of at least 10-point in GHS/QoL subscale score was perceived by participants as clinically meaningful. Confirmed clinically meaningful deterioration was defined as a clinically meaningful decrease from baseline that was held for at least two consecutive assessments or an initial clinically meaningful decrease from baseline followed by death from any cause within 3 weeks.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization until the first confirmed clinically meaningful deterioration up to approximately 24 months&#x27;&#125;                                                                                  | **outcomesModule.secondaryOutcomes.&#91;12&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;TTCD of EORTC QLQ-C30 Global Health Status (GHS)/Quality-of-life (QoL) in the PAS&#x27;, &#x27;description&#x27;&#58; &#x27;TTCD was the time from randomization until the first confirmed clinically meaningful deterioration in patient-reported GHS/QoL. TTCD was determined based on patient-reported GHS/QoL (Items 29-30) as collected and measured by the EORTC QLQ-C30. GHS/QoL items were scored on a 7-point scale, ranging from &quot;very poor&quot; to &quot;excellent&quot;. A high score for the GHS/QoL subscale represented a high health-related QoL. The scale was linearly transformed so that each score ranged from 0 to 100. A score change of at least 10-point in GHS/QoL subscale score was perceived by participants as clinically meaningful. Confirmed clinically meaningful deterioration was defined as a clinically meaningful decrease from baseline that was held for at least two consecutive assessments or an initial clinically meaningful decrease from baseline followed by death from any cause within 3 weeks.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization until the first confirmed clinically meaningful deterioration (up to approximately 24 months)&#x27;&#125;                                                                                                                                           |
| 2026-04-04 02&#58;21&#58;52 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **root&#91;&#x27;outcomesModule&#x27;&#93;&#91;&#x27;otherOutcomes&#x27;&#93;** (Added)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;109&#93;city**: Taoyuan District                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | **contactsLocationsModule.locations.&#91;109&#93;city**: Taoyuan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;109&#93;geoPoint.lat**: 24.9896                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | **contactsLocationsModule.locations.&#91;109&#93;geoPoint.lat**: 24.99368                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;109&#93;geoPoint.lon**: 121.3187                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | **contactsLocationsModule.locations.&#91;109&#93;geoPoint.lon**: 121.29696                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
