---
title: "NCT04294810 Change History"
---

| Timestamp                   | Before                                                                     | After                                                                      |
|:----------------------------|:---------------------------------------------------------------------------|:---------------------------------------------------------------------------|
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;48&#93;city**: Napoli             | **contactsLocationsModule.locations.&#91;48&#93;city**: Naples             |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;48&#93;geoPoint.lat**: 40.87618   | **contactsLocationsModule.locations.&#91;48&#93;geoPoint.lat**: 40.85216   |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;48&#93;geoPoint.lon**: 14.5195    | **contactsLocationsModule.locations.&#91;48&#93;geoPoint.lon**: 14.26811   |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;56&#93;city**: Padua              | **contactsLocationsModule.locations.&#91;56&#93;city**: Padova             |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;56&#93;geoPoint.lat**: 45.40797   | **contactsLocationsModule.locations.&#91;56&#93;geoPoint.lat**: 45.26618   |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;56&#93;geoPoint.lon**: 11.88586   | **contactsLocationsModule.locations.&#91;56&#93;geoPoint.lon**: 11.77208   |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lat**: 22.4143    | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lat**: 25.3238    |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lon**: 108.78745  | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lon**: 105.583    |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lat**: 31.00435   | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lat**: 22.75904   |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lon**: -108.15213 | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lon**: -98.98718  |
| 2026-05-30 03&#58;31&#58;20 | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lat**: 22.75904   | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lat**: 31.00435   |
| 2026-05-30 03&#58;31&#58;20 | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lon**: -98.98718  | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lon**: -108.15213 |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lat**: 31.00435   | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lat**: 27.46194   |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lon**: -108.15213 | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lon**: -109.94134 |
