---
title: "NCT05635643 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                    | After                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-03-20 02&#58;10&#58;44 | **statusModule.statusVerifiedDate**: 2025-07                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-20 02&#58;10&#58;44 | **statusModule.primaryCompletionDateStruct.date**: 2026-02                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.primaryCompletionDateStruct.date**: 2026-09-30                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-20 02&#58;10&#58;44 | **statusModule.completionDateStruct.date**: 2026-02                                                                                                                                                                                                                                                                                                                                                                                                       | **statusModule.completionDateStruct.date**: 2027-01-01                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-20 02&#58;10&#58;44 | **statusModule.lastUpdateSubmitDate**: 2025-07-30                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-03-17                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-20 02&#58;10&#58;44 | **statusModule.lastUpdatePostDateStruct.date**: 2025-08-01                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-19                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;39 | **referencesModule.references.&#91;0&#93;citation**: Wang X, Kapoor VN, Chin DJ, Klakamp SL, Baruffaldi F, Mohan JF, Haines R, Dulak A, Panduro M, Ren Y, Masia R, Hill JA, LaVallee TM, Rajasekaran N. CHS-114&#58; an afucosylated anti-CCR8 monoclonal antibody that selectively depletes intratumoral Treg cells and induces antitumor immune responses. Mol Cancer Ther. 2025 Dec 22. doi&#58; 10.1158/1535-7163.MCT-25-0367. Online ahead of print. | **referencesModule.references.&#91;0&#93;citation**: Wang X, Kapoor VN, Chin DJ, Klakamp SL, Baruffaldi F, Mohan JF, Haines R, Dulak A, Panduro M, Ren Y, Masia R, Hill JA, LaVallee TM, Rajasekaran N. CHS-114&#58; An Afucosylated Anti-CCR8 Monoclonal Antibody that Selectively Depletes Intratumoral Treg Cells and Induces Antitumor Immune Responses. Mol Cancer Ther. 2026 May 4;25(5)&#58;685-700. doi&#58; 10.1158/1535-7163.MCT-25-0367. |
| 2026-07-28 00&#58;26&#58;03 | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.statusVerifiedDate**: 2026-07                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;03 | **statusModule.lastUpdateSubmitDate**: 2026-03-17                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-07-13                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;03 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-19                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-07-14                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-07-28 00&#58;26&#58;03 | **contactsLocationsModule.overallOfficials.&#91;0&#93;name**: Koho Izuka, MD                                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.overallOfficials.&#91;0&#93;name**: Study Director                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;03 | **contactsLocationsModule.overallOfficials.&#91;0&#93;affiliation**: Coherus BioSciences                                                                                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.overallOfficials.&#91;0&#93;affiliation**: Coherus Oncology                                                                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;03 | **contactsLocationsModule.locations.&#91;0&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;0&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;03 | **contactsLocationsModule.locations.&#91;1&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;1&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;03 | **contactsLocationsModule.locations.&#91;3&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;3&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;03 | **contactsLocationsModule.locations.&#91;5&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;5&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;03 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)                                                                                                                                                                                                                                                                                                                   | -                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;03 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;1&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)                                                                                                                                                                                                                                                                                                                   | -                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;03 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;3&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)                                                                                                                                                                                                                                                                                                                   | -                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;03 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;5&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)                                                                                                                                                                                                                                                                                                                   | -                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
