---
title: "NCT05327530 Change History"
---

| Timestamp                   | Before                                                                   | After                                                                     |
|:----------------------------|:-------------------------------------------------------------------------|:--------------------------------------------------------------------------|
| 2026-03-21 02&#58;05&#58;09 | **contactsLocationsModule.locations.&#91;61&#93;city**: Napoli           | **contactsLocationsModule.locations.&#91;61&#93;city**: Naples            |
| 2026-03-21 02&#58;05&#58;09 | **contactsLocationsModule.locations.&#91;61&#93;geoPoint.lat**: 40.87618 | **contactsLocationsModule.locations.&#91;61&#93;geoPoint.lat**: 40.85216  |
| 2026-03-21 02&#58;05&#58;09 | **contactsLocationsModule.locations.&#91;61&#93;geoPoint.lon**: 14.5195  | **contactsLocationsModule.locations.&#91;61&#93;geoPoint.lon**: 14.26811  |
| 2026-03-21 02&#58;05&#58;09 | **contactsLocationsModule.locations.&#91;62&#93;city**: Napoli           | **contactsLocationsModule.locations.&#91;62&#93;city**: Naples            |
| 2026-03-21 02&#58;05&#58;09 | **contactsLocationsModule.locations.&#91;62&#93;geoPoint.lat**: 40.87618 | **contactsLocationsModule.locations.&#91;62&#93;geoPoint.lat**: 40.85216  |
| 2026-03-21 02&#58;05&#58;09 | **contactsLocationsModule.locations.&#91;62&#93;geoPoint.lon**: 14.5195  | **contactsLocationsModule.locations.&#91;62&#93;geoPoint.lon**: 14.26811  |
| 2026-04-04 02&#58;21&#58;51 | **contactsLocationsModule.locations.&#91;63&#93;city**: Padua            | **contactsLocationsModule.locations.&#91;63&#93;city**: Padova            |
| 2026-04-04 02&#58;21&#58;51 | **contactsLocationsModule.locations.&#91;63&#93;geoPoint.lat**: 45.40797 | **contactsLocationsModule.locations.&#91;63&#93;geoPoint.lat**: 44.38225  |
| 2026-04-04 02&#58;21&#58;51 | **contactsLocationsModule.locations.&#91;63&#93;geoPoint.lon**: 11.88586 | **contactsLocationsModule.locations.&#91;63&#93;geoPoint.lon**: 11.14261  |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2026-01                             | **statusModule.statusVerifiedDate**: 2026-04                              |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2026-01-23                        | **statusModule.lastUpdateSubmitDate**: 2026-04-23                         |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-26               | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-24                |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;93&#93;city**: Taoyuan District | **contactsLocationsModule.locations.&#91;93&#93;city**: Taoyuan           |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;93&#93;geoPoint.lat**: 24.9896  | **contactsLocationsModule.locations.&#91;93&#93;geoPoint.lat**: 24.99368  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;93&#93;geoPoint.lon**: 121.3187 | **contactsLocationsModule.locations.&#91;93&#93;geoPoint.lon**: 121.29696 |
