---
title: "NCT04895709 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                    | After                                                                                                                                                                                                                                                                                                                                                                 |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-26 00&#58;55&#58;48 | **statusModule.statusVerifiedDate**: 2025-12                                                                                                                                                                                                                                                                                                              | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                          |
| 2026-02-26 00&#58;55&#58;48 | **statusModule.lastUpdateSubmitDate**: 2025-12-16                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-02-23                                                                                                                                                                                                                                                                                                                     |
| 2026-02-26 00&#58;55&#58;48 | **statusModule.lastUpdatePostDateStruct.date**: 2025-12-17                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-25                                                                                                                                                                                                                                                                                                            |
| 2026-02-26 00&#58;55&#58;48 | **contactsLocationsModule.centralContacts.&#91;0&#93;name**: BMS Study Connect Contact Center www.BMSStudyConnect.com                                                                                                                                                                                                                                     | **contactsLocationsModule.centralContacts.&#91;0&#93;name**: BMS Clinical Trials Contact Center www.BMSClinicalTrials.com                                                                                                                                                                                                                                             |
| 2026-02-26 00&#58;55&#58;48 | **contactsLocationsModule.locations.&#91;3&#93;status**: COMPLETED                                                                                                                                                                                                                                                                                        | **contactsLocationsModule.locations.&#91;3&#93;status**: ACTIVE_NOT_RECRUITING                                                                                                                                                                                                                                                                                        |
| 2026-02-26 00&#58;55&#58;48 | **contactsLocationsModule.locations.&#91;7&#93;status**: COMPLETED                                                                                                                                                                                                                                                                                        | **contactsLocationsModule.locations.&#91;7&#93;status**: ACTIVE_NOT_RECRUITING                                                                                                                                                                                                                                                                                        |
| 2026-02-26 00&#58;55&#58;48 | -                                                                                                                                                                                                                                                                                                                                                         | **root&#91;&#x27;ipdSharingStatementModule&#x27;&#93;** (Added)                                                                                                                                                                                                                                                                                                       |
| 2026-03-21 02&#58;05&#58;09 | **contactsLocationsModule.locations.&#91;39&#93;city**: Napoli                                                                                                                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;39&#93;city**: Naples                                                                                                                                                                                                                                                                                                        |
| 2026-03-21 02&#58;05&#58;09 | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lat**: 40.87618                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lat**: 40.85216                                                                                                                                                                                                                                                                                              |
| 2026-03-21 02&#58;05&#58;09 | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lon**: 14.5195                                                                                                                                                                                                                                                                                   | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lon**: 14.26811                                                                                                                                                                                                                                                                                              |
| 2026-04-07 02&#58;32&#58;47 | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                              | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                          |
| 2026-04-07 02&#58;32&#58;47 | **statusModule.lastUpdateSubmitDate**: 2026-02-23                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-04-03                                                                                                                                                                                                                                                                                                                     |
| 2026-04-07 02&#58;32&#58;47 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-25                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-06                                                                                                                                                                                                                                                                                                            |
| 2026-04-07 02&#58;32&#58;47 | **contactsLocationsModule.locations.&#91;3&#93;facility**: Local Institution - 0062                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;3&#93;facility**: University of Iowa                                                                                                                                                                                                                                                                                         |
| 2026-04-07 02&#58;32&#58;47 | **contactsLocationsModule.locations.&#91;3&#93;status**: ACTIVE_NOT_RECRUITING                                                                                                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;3&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                   |
| 2026-04-07 02&#58;32&#58;47 | **contactsLocationsModule.locations.&#91;7&#93;facility**: Local Institution - 0001                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;7&#93;facility**: Providence Cancer Center Oncology and Hematology Care- Eastside                                                                                                                                                                                                                                            |
| 2026-04-07 02&#58;32&#58;47 | **contactsLocationsModule.locations.&#91;7&#93;status**: ACTIVE_NOT_RECRUITING                                                                                                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;7&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                   |
| 2026-04-07 02&#58;32&#58;47 | -                                                                                                                                                                                                                                                                                                                                                         | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;3&#93;&#91;&#x27;contacts&#x27;&#93;** (Added)                                                                                                                                                                                                                                 |
| 2026-04-07 02&#58;32&#58;47 | -                                                                                                                                                                                                                                                                                                                                                         | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;7&#93;&#91;&#x27;contacts&#x27;&#93;** (Added)                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.lastUpdateSubmitDate**: 2026-04-03                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-04-08                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-06                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-13                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;39 | **contactsLocationsModule.locations.&#91;19&#93;contacts.&#91;0&#93;phone**: 9053170886                                                                                                                                                                                                                                                                   | **contactsLocationsModule.locations.&#91;19&#93;contacts.&#91;0&#93;phone**: 905-387-9495                                                                                                                                                                                                                                                                             |
| 2026-06-05 03&#58;53&#58;46 | **identificationModule.briefTitle**: A Study of BMS-986340 as Monotherapy and in Combination With Nivolumab or Docetaxel in Participants With Advanced Solid Tumors                                                                                                                                                                                       | **identificationModule.briefTitle**: A Study of BMS-986340 as Monotherapy and as Combination Therapy in Participants With Advanced Solid Tumors                                                                                                                                                                                                                       |
| 2026-06-05 03&#58;53&#58;46 | **identificationModule.officialTitle**: A Phase 1/2 Study of BMS-986340 as Monotherapy and in Combination With Nivolumab or Docetaxel in Participants With Advanced Solid Tumors                                                                                                                                                                          | **identificationModule.officialTitle**: A Phase 1/2 Study of BMS-986340 as Monotherapy and as Combination Therapy in Participants With Advanced Solid Tumors                                                                                                                                                                                                          |
| 2026-06-05 03&#58;53&#58;46 | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                              | **statusModule.statusVerifiedDate**: 2026-06                                                                                                                                                                                                                                                                                                                          |
| 2026-06-05 03&#58;53&#58;46 | **statusModule.primaryCompletionDateStruct.date**: 2028-07-07                                                                                                                                                                                                                                                                                             | **statusModule.primaryCompletionDateStruct.date**: 2031-08-31                                                                                                                                                                                                                                                                                                         |
| 2026-06-05 03&#58;53&#58;46 | **statusModule.completionDateStruct.date**: 2028-07-07                                                                                                                                                                                                                                                                                                    | **statusModule.completionDateStruct.date**: 2031-08-31                                                                                                                                                                                                                                                                                                                |
| 2026-06-05 03&#58;53&#58;46 | **statusModule.lastUpdateSubmitDate**: 2026-04-08                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-06-02                                                                                                                                                                                                                                                                                                                     |
| 2026-06-05 03&#58;53&#58;46 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-13                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-04                                                                                                                                                                                                                                                                                                            |
| 2026-06-05 03&#58;53&#58;46 | **descriptionModule.briefSummary**: The purpose of this study is to assess the safety, tolerability, and recommended dose(s) of BMS-986340 as monotherapy and in combination with nivolumab or docetaxel in participants with advanced solid tumors. This study is a first-in-human (FIH) study of BMS-986340 in participants with advanced solid tumors. | **descriptionModule.briefSummary**: The purpose of this study is to assess the safety, tolerability, and recommended dose(s) of BMS-986340 as monotherapy and in combination with nivolumab, docetaxel, or Pumitamig in participants with advanced solid tumors. This study is a first-in-human (FIH) study of BMS-986340 in participants with advanced solid tumors. |
| 2026-06-05 03&#58;53&#58;46 | **designModule.designInfo.allocation**: NON_RANDOMIZED                                                                                                                                                                                                                                                                                                    | **designModule.designInfo.allocation**: RANDOMIZED                                                                                                                                                                                                                                                                                                                    |
| 2026-06-05 03&#58;53&#58;46 | **designModule.enrollmentInfo.count**: 949                                                                                                                                                                                                                                                                                                                | **designModule.enrollmentInfo.count**: 1109                                                                                                                                                                                                                                                                                                                           |
| 2026-06-05 03&#58;53&#58;46 | **outcomesModule.primaryOutcomes.&#91;2&#93;measure**: Incidence of AEs meeting protocol defined dose-limiting toxicity (DLT) criteria                                                                                                                                                                                                                    | **outcomesModule.primaryOutcomes.&#91;2&#93;measure**: Number of deaths                                                                                                                                                                                                                                                                                               |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Inclusion Criteria                                                                                                                                                                                                                                                                            |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Fresh pre-treatment and on-treatment tumor biopsy must be provided for biomarker analysis.                                                                                                                                                                                                                                                                          |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Measurable disease per Response Evaluation Criteria in Solid Tumors (RECIST) v1.1 and at least 1 lesion accessible for biopsy. Fine needle biopsy, cytology, and bone lesion biopsies are not acceptable.                                                                                                                                                           |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Eastern Cooperative Oncology Group Performance Status of 0 or 1.                                                                                                                                                                                                                                                                                                    |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Radiographically documented progressive disease on or after the most recent therapy.                                                                                                                                                                                                                                                                                |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Received standard-of-care therapies, (except for Part 1C, where participants with prior docetaxel use for the advanced/metastatic setting will be excluded), including an available programmed death (ligand)-1 inhibitor known to be effective in the tumor type for which they are being evaluated.                                                               |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Advanced or metastatic disease and have received, be refractory to, not be a candidate for, or be intolerant of existing therapies known to provide clinical benefit for the condition of the participant.                                                                                                                                                          |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | Exclusion Criteria                                                                                                                                                                                                                                                                                                                                                    |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Women&#96; to &#96;Inclusion Criteria                                                                                                                                                                                                                                                                                                                               |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Fresh pre-treatment and on-treatment tumor biopsy must be provided for biomarker analysis.                                                                                                                                                                                                                                                                          |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Measurable disease per Response Evaluation Criteria in Solid Tumors (RECIST) v1.1 and at least 1 lesion accessible for biopsy. Fine needle biopsy, cytology, and bone lesion biopsies are not acceptable.                                                                                                                                                           |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Eastern Cooperative Oncology Group Performance Status of 0 or 1.                                                                                                                                                                                                                                                                                                    |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Radiographically documented progressive disease on or after the most recent therapy.                                                                                                                                                                                                                                                                                |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Received standard-of-care therapies, (except for Part 1C, 2C and 2D, where participants with prior docetaxel use for the advanced/metastatic setting will be excluded), including an available programmed death (ligand)-1 inhibitor known to be effective in the tumor type for which they are being evaluated.                                                    |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | * Advanced or metastatic disease and have received, be refractory to, not be a candidate for, or be intolerant of existing therapies known to provide clinical benefit for the condition of the participant.                                                                                                                                                          |
| 2026-06-05 03&#58;53&#58;46 | -                                                                                                                                                                                                                                                                                                                                                         | Exclusion Criter&#96;                                                                                                                                                                                                                                                                                                                                                 |
| 2026-06-05 03&#58;53&#58;46 | **contactsLocationsModule.locations.&#91;24&#93;facility**: Universitaetsklinikum Ulm                                                                                                                                                                                                                                                                     | **contactsLocationsModule.locations.&#91;24&#93;facility**: Local Institution - 0044                                                                                                                                                                                                                                                                                  |
| 2026-06-05 03&#58;53&#58;46 | **contactsLocationsModule.locations.&#91;24&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                      | **contactsLocationsModule.locations.&#91;24&#93;status**: COMPLETED                                                                                                                                                                                                                                                                                                   |
| 2026-06-05 03&#58;53&#58;46 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;24&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)                                                                                                                                                                                                                  | -                                                                                                                                                                                                                                                                                                                                                                     |
