---
title: "NCT05935098 Change History"
---

| Timestamp                   | Before                                                        | After                                                                              |
|:----------------------------|:--------------------------------------------------------------|:-----------------------------------------------------------------------------------|
| 2026-03-14 02&#58;07&#58;20 | **identificationModule.organization.fullName**: BeiGene       | **identificationModule.organization.fullName**: BeOne Medicines                    |
| 2026-03-14 02&#58;07&#58;20 | **statusModule.statusVerifiedDate**: 2025-06                  | **statusModule.statusVerifiedDate**: 2026-03                                       |
| 2026-03-14 02&#58;07&#58;20 | **statusModule.overallStatus**: ACTIVE_NOT_RECRUITING         | **statusModule.overallStatus**: TERMINATED                                         |
| 2026-03-14 02&#58;07&#58;20 | **statusModule.primaryCompletionDateStruct.date**: 2027-03-31 | **statusModule.primaryCompletionDateStruct.date**: 2026-01-27                      |
| 2026-03-14 02&#58;07&#58;20 | **statusModule.primaryCompletionDateStruct.type**: ESTIMATED  | **statusModule.primaryCompletionDateStruct.type**: ACTUAL                          |
| 2026-03-14 02&#58;07&#58;20 | **statusModule.completionDateStruct.date**: 2027-03-31        | **statusModule.completionDateStruct.date**: 2026-01-27                             |
| 2026-03-14 02&#58;07&#58;20 | **statusModule.completionDateStruct.type**: ESTIMATED         | **statusModule.completionDateStruct.type**: ACTUAL                                 |
| 2026-03-14 02&#58;07&#58;20 | **statusModule.lastUpdateSubmitDate**: 2025-06-23             | **statusModule.lastUpdateSubmitDate**: 2026-03-11                                  |
| 2026-03-14 02&#58;07&#58;20 | **statusModule.lastUpdatePostDateStruct.date**: 2025-06-25    | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-13                         |
| 2026-03-14 02&#58;07&#58;20 | **designModule.enrollmentInfo.count**: 263                    | **designModule.enrollmentInfo.count**: 99                                          |
| 2026-03-14 02&#58;07&#58;20 | **designModule.enrollmentInfo.type**: ESTIMATED               | **designModule.enrollmentInfo.type**: ACTUAL                                       |
| 2026-03-14 02&#58;07&#58;20 | -                                                             | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;whyStopped&#x27;&#93;** (Added) |
