---
title: "NCT04836507 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                   | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|:----------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-06-16 04&#58;16&#58;42 | -                                                                                                                                                                                                                        | Minor formatting updates.                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | **identificationModule.briefTitle**: Study of Efficacy and Safety of CRC01 in Adult Large B-cell Lymphoma Patients                                                                                                       | **identificationModule.briefTitle**: Study of Efficacy and Safety of CRC01 in Adult Large B-cell Lymphoma and B-cell Acute Lymphoblastic Leukemia Patients                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;05 | **identificationModule.officialTitle**: An Open-label, Multi-center, Single-arm Phase 1/2 Study to Assess Tolerability, Safety and Efficacy of CRC01 in Adult Patients With Relapsed or Refractory Large B-cell Lymphoma | **identificationModule.officialTitle**: An Open-label, Multi-center, Single-arm Phase 1/2 Study to Assess Tolerability, Safety and Efficacy of CRC01 in Adult Patients With Relapsed or Refractory Large B-cell Lymphoma and B-cell Acute Lymphoblastic Leukemia                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.statusVerifiedDate**: 2021-04                                                                                                                                                                             | **statusModule.statusVerifiedDate**: 2026-06                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.primaryCompletionDateStruct.date**: 2023-05                                                                                                                                                               | **statusModule.primaryCompletionDateStruct.date**: 2030-08-15                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.completionDateStruct.date**: 2028-02                                                                                                                                                                      | **statusModule.completionDateStruct.date**: 2030-09-26                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.lastUpdateSubmitDate**: 2021-04-29                                                                                                                                                                        | **statusModule.lastUpdateSubmitDate**: 2026-06-29                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.lastUpdatePostDateStruct.date**: 2021-05-03                                                                                                                                                               | **statusModule.lastUpdatePostDateStruct.date**: 2026-07-01                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;05 | **descriptionModule.briefSummary**: This is a multi-center, phase I/II study to determine the efficacy and safety of CRC01 in adult patients with relapsed or refractory large B-cell lymphoma.                          | **descriptionModule.briefSummary**: This is a multi-center, phase I/II study to determine the efficacy and safety of CRC01 in adult patients with relapsed or refractory large B-cell lymphoma and B-cell Acute Lymphoblastic Leukemia.                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | Field &#96;armsInterventionsModule.interventions.&#91;0&#93;description&#96; changed from &#96;A single infusion of chimeric antigen receptor (CAR)-transduced autologous T cells administered intravenously at a target dose of 2 x 10&#92;^6 anti-CD19 CAR T cells/kg.&#96; to &#96;Cohort A &#58;A single infusion of chimeric antigen receptor (CAR)-transduced autologous T cells administered intravenously at a target dose of 2 x 10&#92;^6 anti-CD19 CAR T cells/kg. |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | Cohort B &#58;A single infusion of chimeric antigen receptor (CAR)-transduced autologous T cells administered intravenously at a target dose of 1.5 x 10&#92;^6 anti-CD19 CAR T cells/kg.&#96;                                                                                                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;05 | **outcomesModule.primaryOutcomes.&#91;1&#93;measure**: Phase 2 Pivotal Study&#58; Overall Response Rate (ORR)                                                                                                            | **outcomesModule.primaryOutcomes.&#91;1&#93;measure**: Phase 2 Pivotal Study&#58; Cohort A &#58; Overall Response Rate (ORR) Cohort B &#58; Overall Complete Remission Rate (OCR)                                                                                                                                                                                                                                                                                             |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | Field &#96;outcomesModule.primaryOutcomes.&#91;1&#93;description&#96; changed from &#96;ORR is defined as the incidence of either a complete response (CR) or a partial response (PR) per the Lugano Criteria for Response Assessment (2014).&#96; to &#96;Cohort A &#58; ORR is defined as the incidence of either a complete response (CR) or a partial response (PR) per the Lugano Criteria for Response Assessment (2014).                                               |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | Cohort B &#58; OCR is defined as the incidence of either a complete Remission (CR) or a Complete Remission with incomplete hematologic recovery (CRi) per the ALL Response Criteria.&#96;                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 1. ≥ 19 years of age and provided written informed consent                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 2. Histologically confirmed following large B-cell lymphomas according to the World Health Organization classification 2017                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | * Diffuse large B-cell lymphoma, not otherwise specified Including Large cell transformation from follicular lymphoma (Transformed follicular lymphoma)                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | * High-grade B-cell lymphoma, not otherwise specified                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | * High-grade B-cell lymphoma with double-hit/triple-hit                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | * Primary mediastinal large B cell lymphoma                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 3. Relapsed or refractory disease after ≥ two lines of chemotherapy including rituximab, anthracycline and either having failed autologous Hematopoietic stem cell transplantation (ASCT) or being ineligible for or not consenting to ASCT.                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 4. At least one measurable lesion (Long diameter ≥ 1.5cm)                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 5. Eastern Cooperative Oncology Group (ECOG) performance status 0 or 1                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 6. Adequate renal and hepatic functions based on the laboratory test results                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | * Total Bilirubin ≤ 2.0mg/dL w&#96; to &#96;Cohort A&#58;                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 1. ≥ 19 years of age and provided written informed consent                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 2. Histologically confirmed following large B-cell lymphomas according to the World Health Organization classification 2017                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | * Diffuse large B-cell lymphoma, not otherwise specified Including Large cell transformation from follicular lymphoma (Transformed follicular lymphoma)                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | * High-grade B-cell lymphoma, not otherwise specified                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | * High-grade B-cell lymphoma with double-hit/triple-hit                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | * Primary mediastinal large B cell lymphoma                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 3. Relapsed or refractory disease after ≥ two lines of chemotherapy including rituximab, anthracycline and either having failed autologous Hematopoietic stem cell transplantation (ASCT) or being ineligible for or not consenting to ASCT.                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 4. At least one measurable lesion (Long diameter ≥ 1.5cm)                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 5. Eastern Cooperative Oncology Group (ECOG) performance status 0 or 1                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | 6. Adequate renal and hepatic functions based on the laboratory test results                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                        | * Total Bilirubin ≤&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
