---
title: "NCT06754501 Change History"
---

| Timestamp                   | Before                                                                                                                                  | After                                                      |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------|
| 2026-02-19 01&#58;00&#58;00 | **statusModule.statusVerifiedDate**: 2025-08                                                                                            | **statusModule.statusVerifiedDate**: 2026-02               |
| 2026-02-19 01&#58;00&#58;00 | **statusModule.overallStatus**: RECRUITING                                                                                              | **statusModule.overallStatus**: ACTIVE_NOT_RECRUITING      |
| 2026-02-19 01&#58;00&#58;00 | **statusModule.lastUpdateSubmitDate**: 2025-10-01                                                                                       | **statusModule.lastUpdateSubmitDate**: 2026-02-16          |
| 2026-02-19 01&#58;00&#58;00 | **statusModule.lastUpdatePostDateStruct.date**: 2025-10-07                                                                              | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-18 |
| 2026-02-19 01&#58;00&#58;00 | **designModule.enrollmentInfo.count**: 35                                                                                               | **designModule.enrollmentInfo.count**: 4                   |
| 2026-02-19 01&#58;00&#58;00 | **designModule.enrollmentInfo.type**: ESTIMATED                                                                                         | **designModule.enrollmentInfo.type**: ACTUAL               |
| 2026-02-19 01&#58;00&#58;00 | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;expandedAccessInfo&#x27;&#93;** (Removed)                                            | -                                                          |
| 2026-02-19 01&#58;00&#58;00 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;centralContacts&#x27;&#93;** (Removed)                                    | -                                                          |
| 2026-02-19 01&#58;00&#58;00 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;status&#x27;&#93;** (Removed)   | -                                                          |
| 2026-02-19 01&#58;00&#58;00 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed) | -                                                          |
