---
title: "NCT05020912 Change History"
---

| Timestamp                   | Before                                                                                                                                  | After                                                                                                                                                                                                                                                 |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-06-02 04&#58;04&#58;22 | **statusModule.statusVerifiedDate**: 2025-11                                                                                            | **statusModule.statusVerifiedDate**: 2026-05                                                                                                                                                                                                          |
| 2026-06-02 04&#58;04&#58;22 | **statusModule.overallStatus**: RECRUITING                                                                                              | **statusModule.overallStatus**: ACTIVE_NOT_RECRUITING                                                                                                                                                                                                 |
| 2026-06-02 04&#58;04&#58;22 | **statusModule.lastUpdateSubmitDate**: 2025-11-25                                                                                       | **statusModule.lastUpdateSubmitDate**: 2026-05-28                                                                                                                                                                                                     |
| 2026-06-02 04&#58;04&#58;22 | **statusModule.lastUpdatePostDateStruct.date**: 2025-11-26                                                                              | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-01                                                                                                                                                                                            |
| 2026-06-02 04&#58;04&#58;22 | **designModule.enrollmentInfo.count**: 28                                                                                               | **designModule.enrollmentInfo.count**: 18                                                                                                                                                                                                             |
| 2026-06-02 04&#58;04&#58;22 | **designModule.enrollmentInfo.type**: ESTIMATED                                                                                         | **designModule.enrollmentInfo.type**: ACTUAL                                                                                                                                                                                                          |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Inclusion Criteria&#58;                                                                                                                                                       |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Adults scheduled to undergo Mohs surgery within the Dermatologic Surgery unit of the Department of Dermatology, Cleveland Clinic                                                                                                                    |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Must have at least one BCC tumor eligible for removal by surgical excision                                                                                                                                                                          |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Men and women of any ethnic group are eligible                                                                                                                                                                                                      |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Must provide informed consent to participate                                                                                                                                                                                                        |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | Exclusion Criteria&#58;                                                                                                                                                                                                                               |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Pregnant or breastfeeding                                                                                                                                                                                                                           |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Currently being treated for other cancers with medical or radiation therapy                                                                                                                                                                         |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Known hypersensitivity to 5-aminolevulinic acid (ALA)                                                                                                                                                                                               |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * History of a photosensitivity disease, e.g.,porphyria cutanea tarda&#96; to &#96;Inclusion Criteria                                                                                                                                                 |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Must be an adult parcticpant (&#92;&gt; 18 yrs) who is scheduled to undergo BCC surgery (via Mohs surgery, ED&#92;&amp;C, or standard elliptical excision) within the Dermatologic Surgery unit of the Department of Dermatology, Cleveland Clinic. |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Must have at least one BCC tumor eligible for surgical removal                                                                                                                                                                                      |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Participants of any ethnic group are eligible for this trial.                                                                                                                                                                                       |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Must provide informed consent to participate in the trial.                                                                                                                                                                                          |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | Exclusion Criteria                                                                                                                                                                                                                                    |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Pregnant or breastfeeding                                                                                                                                                                                                                           |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Currently being treated for other cancers with medical or radiation therapy                                                                                                                                                                         |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * Known hypersensitivity to 5-aminolevulinic acid                                                                                                                                                                                                     |
| 2026-06-02 04&#58;04&#58;22 | -                                                                                                                                       | * History of a photosensitivity disease, e.g., porphyria cutanea tarda&#96;                                                                                                                                                                           |
| 2026-06-02 04&#58;04&#58;22 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;centralContacts&#x27;&#93;** (Removed)                                    | -                                                                                                                                                                                                                                                     |
| 2026-06-02 04&#58;04&#58;22 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;status&#x27;&#93;** (Removed)   | -                                                                                                                                                                                                                                                     |
| 2026-06-02 04&#58;04&#58;22 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed) | -                                                                                                                                                                                                                                                     |
