---
title: "NCT05061628 Change History"
---

| Timestamp                   | Before                                                                                                                                  | After                                                                                                                                              |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-07-28 00&#58;26&#58;04 | **statusModule.statusVerifiedDate**: 2021-08                                                                                            | **statusModule.statusVerifiedDate**: 2026-07                                                                                                       |
| 2026-07-28 00&#58;26&#58;04 | **statusModule.overallStatus**: UNKNOWN                                                                                                 | **statusModule.overallStatus**: COMPLETED                                                                                                          |
| 2026-07-28 00&#58;26&#58;04 | **statusModule.primaryCompletionDateStruct.date**: 2023-08-14                                                                           | **statusModule.primaryCompletionDateStruct.date**: 2023-04-23                                                                                      |
| 2026-07-28 00&#58;26&#58;04 | **statusModule.primaryCompletionDateStruct.type**: ESTIMATED                                                                            | **statusModule.primaryCompletionDateStruct.type**: ACTUAL                                                                                          |
| 2026-07-28 00&#58;26&#58;04 | **statusModule.completionDateStruct.date**: 2024-09-30                                                                                  | **statusModule.completionDateStruct.date**: 2023-04-23                                                                                             |
| 2026-07-28 00&#58;26&#58;04 | **statusModule.completionDateStruct.type**: ESTIMATED                                                                                   | **statusModule.completionDateStruct.type**: ACTUAL                                                                                                 |
| 2026-07-28 00&#58;26&#58;04 | **statusModule.lastUpdateSubmitDate**: 2021-09-21                                                                                       | **statusModule.lastUpdateSubmitDate**: 2026-07-08                                                                                                  |
| 2026-07-28 00&#58;26&#58;04 | **statusModule.lastUpdatePostDateStruct.date**: 2021-09-29                                                                              | **statusModule.lastUpdatePostDateStruct.date**: 2026-07-09                                                                                         |
| 2026-07-28 00&#58;26&#58;04 | **designModule.designInfo.allocation**: NA                                                                                              | **designModule.designInfo.allocation**: NON_RANDOMIZED                                                                                             |
| 2026-07-28 00&#58;26&#58;04 | **designModule.designInfo.maskingInfo.masking**: NONE                                                                                   | **designModule.designInfo.maskingInfo.masking**: SINGLE                                                                                            |
| 2026-07-28 00&#58;26&#58;04 | **designModule.enrollmentInfo.count**: 176                                                                                              | **designModule.enrollmentInfo.count**: 47                                                                                                          |
| 2026-07-28 00&#58;26&#58;04 | **designModule.enrollmentInfo.type**: ESTIMATED                                                                                         | **designModule.enrollmentInfo.type**: ACTUAL                                                                                                       |
| 2026-07-28 00&#58;26&#58;04 | -                                                                                                                                       | **root&#91;&#x27;designModule&#x27;&#93;&#91;&#x27;designInfo&#x27;&#93;&#91;&#x27;maskingInfo&#x27;&#93;&#91;&#x27;whoMasked&#x27;&#93;** (Added) |
| 2026-07-28 00&#58;26&#58;04 | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;lastKnownStatus&#x27;&#93;** (Removed)                                               | -                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;04 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;centralContacts&#x27;&#93;** (Removed)                                    | -                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;04 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;status&#x27;&#93;** (Removed)   | -                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;04 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed) | -                                                                                                                                                  |
