---
title: "NCT04995523 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                        | After                                                                                                                                                                                                                                                                                                                                                                                                         |
|:----------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-03-25 02&#58;23&#58;20 | **statusModule.statusVerifiedDate**: 2025-11                                                                                                                                                                                                                                                                                                                                                                                                                  | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-25 02&#58;23&#58;20 | **statusModule.overallStatus**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                    | **statusModule.overallStatus**: ACTIVE_NOT_RECRUITING                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-25 02&#58;23&#58;20 | **statusModule.primaryCompletionDateStruct.date**: 2026-08-18                                                                                                                                                                                                                                                                                                                                                                                                 | **statusModule.primaryCompletionDateStruct.date**: 2026-08-28                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-25 02&#58;23&#58;20 | **statusModule.completionDateStruct.date**: 2028-03-16                                                                                                                                                                                                                                                                                                                                                                                                        | **statusModule.completionDateStruct.date**: 2028-06-01                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-25 02&#58;23&#58;20 | **statusModule.lastUpdateSubmitDate**: 2025-11-21                                                                                                                                                                                                                                                                                                                                                                                                             | **statusModule.lastUpdateSubmitDate**: 2026-03-20                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-25 02&#58;23&#58;20 | **statusModule.lastUpdatePostDateStruct.date**: 2025-11-24                                                                                                                                                                                                                                                                                                                                                                                                    | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-24                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-25 02&#58;23&#58;20 | **designModule.enrollmentInfo.count**: 210                                                                                                                                                                                                                                                                                                                                                                                                                    | **designModule.enrollmentInfo.count**: 212                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-25 02&#58;23&#58;20 | **designModule.enrollmentInfo.type**: ESTIMATED                                                                                                                                                                                                                                                                                                                                                                                                               | **designModule.enrollmentInfo.type**: ACTUAL                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;1&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Chicago&#x27;, &#x27;state&#x27;&#58; &#x27;Illinois&#x27;, &#x27;zip&#x27;&#58; &#x27;60637&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.85003, &#x27;lon&#x27;&#58; -87.65005&#125;&#125;   | **contactsLocationsModule.locations.&#91;1&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Rochester&#x27;, &#x27;state&#x27;&#58; &#x27;Minnesota&#x27;, &#x27;zip&#x27;&#58; &#x27;55905&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 44.02163, &#x27;lon&#x27;&#58; -92.4699&#125;&#125; |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;20&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Tbilisi&#x27;, &#x27;zip&#x27;&#58; &#x27;0112&#x27;, &#x27;country&#x27;&#58; &#x27;Georgia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.69143, &#x27;lon&#x27;&#58; 44.83412&#125;&#125;                                                       | **contactsLocationsModule.locations.&#91;20&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Tokyo&#x27;, &#x27;zip&#x27;&#58; &#x27;104-0045&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.6895, &#x27;lon&#x27;&#58; 139.69171&#125;&#125;                                                       |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;3&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Rochester&#x27;, &#x27;state&#x27;&#58; &#x27;Minnesota&#x27;, &#x27;zip&#x27;&#58; &#x27;55905&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 44.02163, &#x27;lon&#x27;&#58; -92.4699&#125;&#125; | **contactsLocationsModule.locations.&#91;3&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Melbourne&#x27;, &#x27;zip&#x27;&#58; &#x27;3000&#x27;, &#x27;country&#x27;&#58; &#x27;Australia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -37.814, &#x27;lon&#x27;&#58; 144.96332&#125;&#125;                                                    |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;11&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Porto Alegre&#x27;, &#x27;zip&#x27;&#58; &#x27;90035903&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -30.03283, &#x27;lon&#x27;&#58; -51.23019&#125;&#125;                                             | **contactsLocationsModule.locations.&#91;11&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Chengdu&#x27;, &#x27;zip&#x27;&#58; &#x27;610041&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 30.66667, &#x27;lon&#x27;&#58; 104.06667&#125;&#125;                                                      |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;4&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;WITHDRAWN&#x27;, &#x27;city&#x27;&#58; &#x27;Houston&#x27;, &#x27;state&#x27;&#58; &#x27;Texas&#x27;, &#x27;zip&#x27;&#58; &#x27;77030&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 29.76328, &#x27;lon&#x27;&#58; -95.36327&#125;&#125;       | **contactsLocationsModule.locations.&#91;4&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Anderlecht&#x27;, &#x27;zip&#x27;&#58; &#x27;1070&#x27;, &#x27;country&#x27;&#58; &#x27;Belgium&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 50.83619, &#x27;lon&#x27;&#58; 4.31454&#125;&#125;                                                      |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;19&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Toulouse&#x27;, &#x27;zip&#x27;&#58; &#x27;31059&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.60426, &#x27;lon&#x27;&#58; 1.44367&#125;&#125;                                                       | **contactsLocationsModule.locations.&#91;19&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Sendai&#x27;, &#x27;zip&#x27;&#58; &#x27;981-0914&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 38.26667, &#x27;lon&#x27;&#58; 140.86667&#125;&#125;                                                     |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;13&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;São Paulo&#x27;, &#x27;zip&#x27;&#58; &#x27;01246-000&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -23.5475, &#x27;lon&#x27;&#58; -46.63611&#125;&#125;                                                | **contactsLocationsModule.locations.&#91;13&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Copenhagen&#x27;, &#x27;zip&#x27;&#58; &#x27;2100&#x27;, &#x27;country&#x27;&#58; &#x27;Denmark&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 55.67594, &#x27;lon&#x27;&#58; 12.56553&#125;&#125;                                                    |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;2&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;WITHDRAWN&#x27;, &#x27;city&#x27;&#58; &#x27;Baltimore&#x27;, &#x27;state&#x27;&#58; &#x27;Maryland&#x27;, &#x27;zip&#x27;&#58; &#x27;21201&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 39.29038, &#x27;lon&#x27;&#58; -76.61219&#125;&#125;  | **contactsLocationsModule.locations.&#91;2&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Fairfax&#x27;, &#x27;state&#x27;&#58; &#x27;Virginia&#x27;, &#x27;zip&#x27;&#58; &#x27;22031&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 38.84622, &#x27;lon&#x27;&#58; -77.30637&#125;&#125;   |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;6&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;COMPLETED&#x27;, &#x27;city&#x27;&#58; &#x27;Melbourne&#x27;, &#x27;zip&#x27;&#58; &#x27;3000&#x27;, &#x27;country&#x27;&#58; &#x27;Australia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -37.814, &#x27;lon&#x27;&#58; 144.96332&#125;&#125;                                                     | **contactsLocationsModule.locations.&#91;6&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Florianópolis&#x27;, &#x27;zip&#x27;&#58; &#x27;88034-000&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -27.59667, &#x27;lon&#x27;&#58; -48.54917&#125;&#125;                                            |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;5&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Fairfax&#x27;, &#x27;state&#x27;&#58; &#x27;Virginia&#x27;, &#x27;zip&#x27;&#58; &#x27;22031&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 38.84622, &#x27;lon&#x27;&#58; -77.30637&#125;&#125;   | **contactsLocationsModule.locations.&#91;5&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Leuven&#x27;, &#x27;zip&#x27;&#58; &#x27;3000&#x27;, &#x27;country&#x27;&#58; &#x27;Belgium&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 50.87959, &#x27;lon&#x27;&#58; 4.70093&#125;&#125;                                                          |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;39&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Taichung&#x27;, &#x27;country&#x27;&#58; &#x27;Taiwan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 24.1469, &#x27;lon&#x27;&#58; 120.6839&#125;&#125;                                                                                               | **contactsLocationsModule.locations.&#91;39&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Muang&#x27;, &#x27;zip&#x27;&#58; &#x27;50200&#x27;, &#x27;country&#x27;&#58; &#x27;Thailand&#x27;&#125;                                                                                                                                                           |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;18&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Dijon&#x27;, &#x27;zip&#x27;&#58; &#x27;21079&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 47.31344, &#x27;lon&#x27;&#58; 5.01391&#125;&#125;                                                          | **contactsLocationsModule.locations.&#91;18&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Niigata&#x27;, &#x27;zip&#x27;&#58; &#x27;951-8566&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 37.92259, &#x27;lon&#x27;&#58; 139.04125&#125;&#125;                                                    |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;12&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Rio de Janeiro&#x27;, &#x27;zip&#x27;&#58; &#x27;20231-050&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -22.90642, &#x27;lon&#x27;&#58; -43.18223&#125;&#125;                                          | **contactsLocationsModule.locations.&#91;12&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Chongqing&#x27;, &#x27;zip&#x27;&#58; &#x27;400030&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 29.56026, &#x27;lon&#x27;&#58; 106.55771&#125;&#125;                                                    |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;10&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Natal&#x27;, &#x27;zip&#x27;&#58; &#x27;59075-740&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -5.795, &#x27;lon&#x27;&#58; -35.20944&#125;&#125;                                                      | **contactsLocationsModule.locations.&#91;10&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;São Paulo&#x27;, &#x27;zip&#x27;&#58; &#x27;01246-000&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -23.5475, &#x27;lon&#x27;&#58; -46.63611&#125;&#125;                                                |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;25&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Kuala Lumpur&#x27;, &#x27;zip&#x27;&#58; &#x27;59100&#x27;, &#x27;country&#x27;&#58; &#x27;Malaysia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 3.1412, &#x27;lon&#x27;&#58; 101.68653&#125;&#125;                                                 | **contactsLocationsModule.locations.&#91;25&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Leiden&#x27;, &#x27;zip&#x27;&#58; &#x27;2333 ZA&#x27;, &#x27;country&#x27;&#58; &#x27;Netherlands&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 52.15833, &#x27;lon&#x27;&#58; 4.49306&#125;&#125;                                                  |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;27&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Chisinau&#x27;, &#x27;zip&#x27;&#58; &#x27;MD-2025&#x27;, &#x27;country&#x27;&#58; &#x27;Moldova&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 47.00902, &#x27;lon&#x27;&#58; 28.85938&#125;&#125;                                                   | **contactsLocationsModule.locations.&#91;27&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Seoul&#x27;, &#x27;zip&#x27;&#58; &#x27;03082&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 37.566, &#x27;lon&#x27;&#58; 126.9784&#125;&#125;                                                      |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;9&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Florianópolis&#x27;, &#x27;zip&#x27;&#58; &#x27;88034-000&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -27.59667, &#x27;lon&#x27;&#58; -48.54917&#125;&#125;                                            | **contactsLocationsModule.locations.&#91;9&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Rio de Janeiro&#x27;, &#x27;zip&#x27;&#58; &#x27;20231-050&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -22.90642, &#x27;lon&#x27;&#58; -43.18223&#125;&#125;                                           |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;32&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Seoul&#x27;, &#x27;zip&#x27;&#58; &#x27;03082&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 37.566, &#x27;lon&#x27;&#58; 126.9784&#125;&#125;                                                      | **contactsLocationsModule.locations.&#91;32&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Madrid&#x27;, &#x27;zip&#x27;&#58; &#x27;28041&#x27;, &#x27;country&#x27;&#58; &#x27;Spain&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 40.4165, &#x27;lon&#x27;&#58; -3.70256&#125;&#125;                                                          |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;7&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;ACTIVE_NOT_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Anderlecht&#x27;, &#x27;zip&#x27;&#58; &#x27;1070&#x27;, &#x27;country&#x27;&#58; &#x27;Belgium&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 50.83619, &#x27;lon&#x27;&#58; 4.31454&#125;&#125;                                           | **contactsLocationsModule.locations.&#91;7&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Natal&#x27;, &#x27;zip&#x27;&#58; &#x27;59075-740&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -5.795, &#x27;lon&#x27;&#58; -35.20944&#125;&#125;                                                       |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;17&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;ACTIVE_NOT_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Copenhagen&#x27;, &#x27;zip&#x27;&#58; &#x27;2100&#x27;, &#x27;country&#x27;&#58; &#x27;Denmark&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 55.67594, &#x27;lon&#x27;&#58; 12.56553&#125;&#125;                                         | **contactsLocationsModule.locations.&#91;17&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Kashiwa&#x27;, &#x27;zip&#x27;&#58; &#x27;227-8577&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.86224, &#x27;lon&#x27;&#58; 139.97732&#125;&#125;                                                    |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;8&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;ACTIVE_NOT_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Leuven&#x27;, &#x27;zip&#x27;&#58; &#x27;3000&#x27;, &#x27;country&#x27;&#58; &#x27;Belgium&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 50.87959, &#x27;lon&#x27;&#58; 4.70093&#125;&#125;                                               | **contactsLocationsModule.locations.&#91;8&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Porto Alegre&#x27;, &#x27;zip&#x27;&#58; &#x27;90035903&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -30.03283, &#x27;lon&#x27;&#58; -51.23019&#125;&#125;                                              |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;14&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Chengdu&#x27;, &#x27;zip&#x27;&#58; &#x27;610041&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 30.66667, &#x27;lon&#x27;&#58; 104.06667&#125;&#125;                                                      | **contactsLocationsModule.locations.&#91;14&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Dijon&#x27;, &#x27;zip&#x27;&#58; &#x27;21079&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 47.31344, &#x27;lon&#x27;&#58; 5.01391&#125;&#125;                                                          |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;28&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;ACTIVE_NOT_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Groningen&#x27;, &#x27;zip&#x27;&#58; &#x27;9713 GZ&#x27;, &#x27;country&#x27;&#58; &#x27;Netherlands&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 53.21917, &#x27;lon&#x27;&#58; 6.56667&#125;&#125;                                    | **contactsLocationsModule.locations.&#91;28&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Seoul&#x27;, &#x27;zip&#x27;&#58; &#x27;03722&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 37.566, &#x27;lon&#x27;&#58; 126.9784&#125;&#125;                                                      |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;15&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;ACTIVE_NOT_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Chongqing&#x27;, &#x27;zip&#x27;&#58; &#x27;400030&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 29.56026, &#x27;lon&#x27;&#58; 106.55771&#125;&#125;                                         | **contactsLocationsModule.locations.&#91;15&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Toulouse&#x27;, &#x27;zip&#x27;&#58; &#x27;31059&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.60426, &#x27;lon&#x27;&#58; 1.44367&#125;&#125;                                                       |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;26&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Kuching&#x27;, &#x27;zip&#x27;&#58; &#x27;93586&#x27;, &#x27;country&#x27;&#58; &#x27;Malaysia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 1.55, &#x27;lon&#x27;&#58; 110.33333&#125;&#125;                                                        | **contactsLocationsModule.locations.&#91;26&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Utrecht&#x27;, &#x27;zip&#x27;&#58; &#x27;3584 CX&#x27;, &#x27;country&#x27;&#58; &#x27;Netherlands&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 52.09083, &#x27;lon&#x27;&#58; 5.12222&#125;&#125;                                                 |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;24&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Tokyo&#x27;, &#x27;zip&#x27;&#58; &#x27;104-0045&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.6895, &#x27;lon&#x27;&#58; 139.69171&#125;&#125;                                                       | **contactsLocationsModule.locations.&#91;24&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Groningen&#x27;, &#x27;zip&#x27;&#58; &#x27;9713 GZ&#x27;, &#x27;country&#x27;&#58; &#x27;Netherlands&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 53.21917, &#x27;lon&#x27;&#58; 6.56667&#125;&#125;                                               |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;29&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;ACTIVE_NOT_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Leiden&#x27;, &#x27;zip&#x27;&#58; &#x27;2333 ZA&#x27;, &#x27;country&#x27;&#58; &#x27;Netherlands&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 52.15833, &#x27;lon&#x27;&#58; 4.49306&#125;&#125;                                       | **contactsLocationsModule.locations.&#91;29&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Seoul&#x27;, &#x27;zip&#x27;&#58; &#x27;05505&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 37.566, &#x27;lon&#x27;&#58; 126.9784&#125;&#125;                                                      |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;23&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Sendai&#x27;, &#x27;zip&#x27;&#58; &#x27;981-0914&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 38.26667, &#x27;lon&#x27;&#58; 140.86667&#125;&#125;                                                     | **contactsLocationsModule.locations.&#91;23&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Chisinau&#x27;, &#x27;zip&#x27;&#58; &#x27;MD-2025&#x27;, &#x27;country&#x27;&#58; &#x27;Moldova&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 47.00902, &#x27;lon&#x27;&#58; 28.85938&#125;&#125;                                                   |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;21&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Kashiwa&#x27;, &#x27;zip&#x27;&#58; &#x27;227-8577&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.86224, &#x27;lon&#x27;&#58; 139.97732&#125;&#125;                                                    | **contactsLocationsModule.locations.&#91;21&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Kuala Lumpur&#x27;, &#x27;zip&#x27;&#58; &#x27;59100&#x27;, &#x27;country&#x27;&#58; &#x27;Malaysia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 3.1412, &#x27;lon&#x27;&#58; 101.68653&#125;&#125;                                                 |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;33&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Seoul&#x27;, &#x27;zip&#x27;&#58; &#x27;03722&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 37.566, &#x27;lon&#x27;&#58; 126.9784&#125;&#125;                                                      | **contactsLocationsModule.locations.&#91;33&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Taichung&#x27;, &#x27;zip&#x27;&#58; &#x27;40201&#x27;, &#x27;country&#x27;&#58; &#x27;Taiwan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 24.1469, &#x27;lon&#x27;&#58; 120.6839&#125;&#125;                                                       |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;0&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;WITHDRAWN&#x27;, &#x27;city&#x27;&#58; &#x27;Orange&#x27;, &#x27;state&#x27;&#58; &#x27;California&#x27;, &#x27;zip&#x27;&#58; &#x27;92868&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 33.78779, &#x27;lon&#x27;&#58; -117.85311&#125;&#125;  | **contactsLocationsModule.locations.&#91;0&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Chicago&#x27;, &#x27;state&#x27;&#58; &#x27;Illinois&#x27;, &#x27;zip&#x27;&#58; &#x27;60637&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.85003, &#x27;lon&#x27;&#58; -87.65005&#125;&#125;   |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;35&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;ACTIVE_NOT_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Barcelona&#x27;, &#x27;zip&#x27;&#58; &#x27;08035&#x27;, &#x27;country&#x27;&#58; &#x27;Spain&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.38879, &#x27;lon&#x27;&#58; 2.15899&#125;&#125;                                            | **contactsLocationsModule.locations.&#91;35&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Tainan&#x27;, &#x27;zip&#x27;&#58; &#x27;70403&#x27;, &#x27;country&#x27;&#58; &#x27;Taiwan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 22.99083, &#x27;lon&#x27;&#58; 120.21333&#125;&#125;                                                       |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;22&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Niigata&#x27;, &#x27;zip&#x27;&#58; &#x27;951-8566&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 37.92259, &#x27;lon&#x27;&#58; 139.04125&#125;&#125;                                                    | **contactsLocationsModule.locations.&#91;22&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Kuching&#x27;, &#x27;zip&#x27;&#58; &#x27;93586&#x27;, &#x27;country&#x27;&#58; &#x27;Malaysia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 1.55, &#x27;lon&#x27;&#58; 110.33333&#125;&#125;                                                        |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;36&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;ACTIVE_NOT_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Madrid&#x27;, &#x27;zip&#x27;&#58; &#x27;28027&#x27;, &#x27;country&#x27;&#58; &#x27;Spain&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 40.4165, &#x27;lon&#x27;&#58; -3.70256&#125;&#125;                                               | **contactsLocationsModule.locations.&#91;36&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Taipei&#x27;, &#x27;zip&#x27;&#58; &#x27;110&#x27;, &#x27;country&#x27;&#58; &#x27;Taiwan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 25.05306, &#x27;lon&#x27;&#58; 121.52639&#125;&#125;                                                         |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;38&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Taichung&#x27;, &#x27;zip&#x27;&#58; &#x27;40201&#x27;, &#x27;country&#x27;&#58; &#x27;Taiwan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 24.1469, &#x27;lon&#x27;&#58; 120.6839&#125;&#125;                                                       | **contactsLocationsModule.locations.&#91;38&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Chanthaburi&#x27;, &#x27;zip&#x27;&#58; &#x27;22000&#x27;, &#x27;country&#x27;&#58; &#x27;Thailand&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 12.60961, &#x27;lon&#x27;&#58; 102.10447&#125;&#125;                                                |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;34&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Seoul&#x27;, &#x27;zip&#x27;&#58; &#x27;05505&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 37.566, &#x27;lon&#x27;&#58; 126.9784&#125;&#125;                                                      | **contactsLocationsModule.locations.&#91;34&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Taichung&#x27;, &#x27;country&#x27;&#58; &#x27;Taiwan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 24.1469, &#x27;lon&#x27;&#58; 120.6839&#125;&#125;                                                                                               |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;16&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;WITHDRAWN&#x27;, &#x27;city&#x27;&#58; &#x27;Wuhan&#x27;, &#x27;zip&#x27;&#58; &#x27;430022&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 30.58333, &#x27;lon&#x27;&#58; 114.26667&#125;&#125;                                                         | **contactsLocationsModule.locations.&#91;16&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Tbilisi&#x27;, &#x27;zip&#x27;&#58; &#x27;0112&#x27;, &#x27;country&#x27;&#58; &#x27;Georgia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.69143, &#x27;lon&#x27;&#58; 44.83412&#125;&#125;                                                       |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;30&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;COMPLETED&#x27;, &#x27;city&#x27;&#58; &#x27;Utrecht&#x27;, &#x27;zip&#x27;&#58; &#x27;3584 CX&#x27;, &#x27;country&#x27;&#58; &#x27;Netherlands&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 52.09083, &#x27;lon&#x27;&#58; 5.12222&#125;&#125;                                                  | **contactsLocationsModule.locations.&#91;30&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Barcelona&#x27;, &#x27;zip&#x27;&#58; &#x27;08035&#x27;, &#x27;country&#x27;&#58; &#x27;Spain&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.38879, &#x27;lon&#x27;&#58; 2.15899&#125;&#125;                                                       |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;37&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;ACTIVE_NOT_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Madrid&#x27;, &#x27;zip&#x27;&#58; &#x27;28041&#x27;, &#x27;country&#x27;&#58; &#x27;Spain&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 40.4165, &#x27;lon&#x27;&#58; -3.70256&#125;&#125;                                               | **contactsLocationsModule.locations.&#91;37&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Bangkok&#x27;, &#x27;zip&#x27;&#58; &#x27;10700&#x27;, &#x27;country&#x27;&#58; &#x27;Thailand&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 13.75398, &#x27;lon&#x27;&#58; 100.50144&#125;&#125;                                                    |
| 2026-03-25 02&#58;23&#58;20 | **contactsLocationsModule.locations.&#91;31&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;status&#x27;&#58; &#x27;WITHDRAWN&#x27;, &#x27;city&#x27;&#58; &#x27;Singapore&#x27;, &#x27;zip&#x27;&#58; &#x27;308433&#x27;, &#x27;country&#x27;&#58; &#x27;Singapore&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 1.28967, &#x27;lon&#x27;&#58; 103.85007&#125;&#125;                                                  | **contactsLocationsModule.locations.&#91;31&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Madrid&#x27;, &#x27;zip&#x27;&#58; &#x27;28027&#x27;, &#x27;country&#x27;&#58; &#x27;Spain&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 40.4165, &#x27;lon&#x27;&#58; -3.70256&#125;&#125;                                                          |
| 2026-03-25 02&#58;23&#58;20 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;centralContacts&#x27;&#93;** (Removed)                                                                                                                                                                                                                                                                                                                                                          | -                                                                                                                                                                                                                                                                                                                                                                                                             |
