---
title: "NCT04457778 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|:----------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2023-11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2023-12-07                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | **statusModule.lastUpdateSubmitDate**: 2026-04-13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2023-12-08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-04                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;40 | **descriptionModule.briefSummary**: The main purpose of this study is to determine the safety, tolerability, pharmacokinetics (PK), immunogenicity and (if observed) the maximum tolerated dose (MTD) of M6223 as a single agent (Part 1A) for both the every 2 weeks (Q2W) regimen and the every 3 weeks (Q3W) regimen and of M6223 combined with bintrafusp alfa (Part 1B) for Q2W regimen in participants with metastatic or locally advanced solid unresectable tumors.                                                                                                                                                         | **descriptionModule.briefSummary**: The main purpose of this study was to determine the safety, tolerability, pharmacokinetics (PK), immunogenicity and (if observed) the maximum tolerated dose (MTD) of M6223 as a single agent (Part 1A) for both the every 2 weeks (Q2W) regimen and the every 3 weeks (Q3W) regimen and of M6223 combined with bintrafusp alfa (Part 1B) for Q2W regimen in participants with metastatic or locally advanced solid unresectable tumors.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.primaryOutcomes.&#91;4&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part IA and IB&#58; Occurrence of Clinically Significant Change From Baseline in Electrocardiogram Findings&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Time from baseline to final assessment at end of safety follow-up visit (up to a maximum of approximately 2 years)&#x27;&#125;                                                                                                                                                                                                                                                             | **outcomesModule.primaryOutcomes.&#91;4&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and 1B&#58; Number of Participants With Clinically Meaningful Change From Baseline in Electrocardiogram (ECG)&#x27;, &#x27;description&#x27;&#58; &#x27;Number of participants with clinically significant change from baseline in ECG parameters were reported. Clinical Significance was decided by the investigator. The 12-lead ECGs were recorded after the participants have rested for at least 5 minutes in supine position. The parameters included heart rate (HR), Respiratory Rate, Pulse Rate, QRS, QT and QTcB calculated by the Bazett formula.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Approximately 2 years 11 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;5&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and Part 1B&#58; Time to Reach Maximum Serum Concentration (Tmax) of M6223&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Pre-dose up to 14 days (in Q2W regimen) or 21 days (in Q3W regimen) post-dose of Cycles 1, 2, and 4 (Each cycle is of 14 days in Q2W regimen and each Cycle is of 21 days in Q3W regimen)&#x27;&#125;                                                                                                                                                                                                             | **outcomesModule.secondaryOutcomes.&#91;5&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and Part 1B&#58; Time to Reach Maximum Serum Concentration (Tmax) of M6223&#x27;, &#x27;description&#x27;&#58; &#x27;Time taken to reach maximum concentration of M66223 after admistration is reported.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Cycle 1 and 2&#58; Day 1 (-2h, EOI, 4-6h), Day 2 (25-31h), Day 5 (±1h), Day 8 (±1h); Cycle 3 to end of treatment&#58; Day 1 (-2h pre-dose only)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and Part 1B&#58; Area Under Serum Concentration-Time Curve Over a Dosing Interval From Time Zero to Tau (τ) (AUCτ) of M6223&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Pre-dose up to 14 days (in Q2W regimen) or 21 days (in Q3W regimen) post-dose of Cycles 1, 2, and 4 (Each cycle is of 14 days in Q2W regimen and each Cycle is of 21 days in Q3W regimen)&#x27;&#125;                                                                                                                                                            | **outcomesModule.secondaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and Part 1B&#58; Area Under Serum Concentration-Time Curve Over a Dosing Interval From Time Zero to Tau (AUC-tau) of M6223&#x27;, &#x27;description&#x27;&#58; &#x27;Area under the concentration-time curve from time zero up to time Tau, where Tau is the dosing interval.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Pre-dose up to 14 days (in Q2W regimen) or 21 days (in Q3W regimen) post-dose of Cycle 1 (Cycle is of 21 days in Q3W regimen)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;16&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and 1B&#58; Disease Control According to Response Criteria in Solid Tumors Version 1.1 (RECIST 1.1) Assessed as per Investigator&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From first study drug administration until documented disease progression or death due to any cause whichever occurs first, (approximately assessed up to 2 years)&#x27;&#125;                                                                                                                                                                             | **outcomesModule.secondaryOutcomes.&#91;16&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and 1B&#58; Overall Survival&#x27;, &#x27;description&#x27;&#58; &#x27;Overall survival was defined as the time (in months) from first study drug administration to the date of death due to any cause. Participants last known to be alive were censored at date of last contact. Analysis was performed using Kaplan-Meier method.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From first study drug administration to the date of death due to any cause (approximately 2 years 11 months)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and Part 1B&#58; Area Under the Serum Concentration-Time Curve From Time Zero to Infinity (AUC 0-inf) of M6223&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Pre-dose up to 14 days (in Q2W regimen) or 21 days (in Q3W regimen) post-dose of Cycles 1, 2, and 4 (Each cycle is of 14 days in Q2W regimen and each Cycle is of 21 days in Q3W regimen)&#x27;&#125;                                                                                                                                                                         | **outcomesModule.secondaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and Part 1B&#58; Area Under the Serum Concentration-Time Curve From Time Zero to Infinity (AUC 0-inf) of M6223&#x27;, &#x27;description&#x27;&#58; &#x27;Area under the serum concentration time curve from time zero to infinity, calculated as AUC0 t + AUCextra. AUCextra represents an extrapolated value obtained by Clast/λz, where Clast is the calculated serum concentration at the last sampling time point at which the measured serum concentration is at or above LLQ and λz is elimination rate constant.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Pre-dose up to 14 days (in Q2W regimen) or 21 days (in Q3W regimen) post-dose of Cycles 1, 2, and 4 (Each cycle is of 14 days in Q2W regimen and each Cycle is of 21 days in Q3W regimen)&#x27;&#125;                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.primaryOutcomes.&#91;3&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part IA and IB&#58; Occurrence of Clinically Significant Change From Baseline in Clinical Laboratory Measures&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Time from baseline to final assessment at end of safety follow-up visit (up to a maximum of approximately 2 years)&#x27;&#125;                                                                                                                                                                                                                                                           | **outcomesModule.primaryOutcomes.&#91;3&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and 1B&#58; Number of Participants With Clinically Meaningful Change From Baseline in Laboratory Values&#x27;, &#x27;description&#x27;&#58; &#x27;Number of participants with clinically meaningful change from baseline in laboratory parameters were reported. Clinically meaningful abnormalities (identified as laboratory values having CTCAE grades &#92;&#92;&gt;&#61; 3). Laboratory investigation included hematology, biochemistry, urinalysis, and coagulation.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Approximately 2 years 11 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-05-26 02&#58;38&#58;40 | **armsInterventionsModule.interventions.&#91;0&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;M6223&#x27;, &#x27;description&#x27;&#58; &#x27;Participants will receive an intravenous (IV) infusion of M6223 at escalated doses every 2 weeks (Q2W) or every 3 weeks (Q3W) on Day 1 of each Cycle (Each cycle is of 14 days) according to the recommendation of the SMC(Safety Monitoring Committee) until the maximum tolerated dose(MTD) has been reached or confirmed disease progression.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Part 1A&#58; M6223 Monotherapy&#x27;&#93;&#125; | **armsInterventionsModule.interventions.&#91;0&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;M6223&#x27;, &#x27;description&#x27;&#58; &#x27;Participants received an intravenous (IV) infusion of M6223 at escalated doses every 2 weeks (Q2W) or every 3 weeks (Q3W) on Day 1 of each Cycle (Each cycle is of 14 days) according to the recommendation of the SMC(Safety Monitoring Committee) until the maximum tolerated dose(MTD) has been reached or confirmed disease progression.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Part 1A&#58; M6223 Monotherapy&#x27;&#93;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;9&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1B&#58; Serum Concentration Observed Immediately Before Next Dosing (Ctrough) of Bintrafusp alfa&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Pre-dose up to 14 days (in Q2W regimen) post-dose of Cycles 1, 2, and 4 (Each cycle is of 14 days in Q2W regimen)&#x27;&#125;                                                                                                                                                                                                                                                                  | **outcomesModule.secondaryOutcomes.&#91;9&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1B&#58; Serum Concentration Observed Immediately Before Next Dosing (Ctrough) of Bintrafusp Alfa&#x27;, &#x27;description&#x27;&#58; &#x27;Ctrough is the concentration prior to study drug administration.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Day 1 of Treatment of Cycles 1 and 4 from time zero to 14 days postdose&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;40 | **armsInterventionsModule.interventions.&#91;1&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Bintrafusp alfa&#x27;, &#x27;description&#x27;&#58; &#x27;Participants will receive an IV infusion of bintrafusp alfa Q2W on Day 1 of each Cycle (Cycle is 14 days) until confirmed disease progression.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Part1B&#58; M6223 + Bintrafusp alfa&#x27;&#93;&#125;                                                                                                                                                                                    | **armsInterventionsModule.interventions.&#91;1&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Bintrafusp alfa&#x27;, &#x27;description&#x27;&#58; &#x27;Participants received an IV infusion of bintrafusp alfa Q2W on Day 1 of each Cycle (Cycle is 14 days) until confirmed disease progression.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Part1B&#58; M6223 + Bintrafusp alfa&#x27;&#93;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.primaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part IA and IB&#58; Occurrence of Treatment-Emergent Adverse Events (TEAEs) and Treatment Related Adverse Events (TRAEs) According to the National Cancer Institute Common Terminology Criteria of Adverse Events (NCI-CTCAE) version 5&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Time from first study drug administration to final assessment at end of safety follow-up visit (up to a maximum of approximately 2 years)&#x27;&#125;                                                                                                          | **outcomesModule.primaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and 1B&#58; Number of Participants With Treatment-Emergent Adverse Events (TEAEs) and Treatment-Related TEAEs&#x27;, &#x27;description&#x27;&#58; &#x27;An adverse event (AE) is defined as any untoward medical occurrence in a participant or clinical study participant, temporally associated with the use of study intervention, whether considered related to the study intervention or not. A serious AE was an AE that resulted in any of the following outcomes&#58; death; life threatening; persistent/significant disability/incapacity; initial or prolonged inpatient hospitalization; congenital anomaly/birth defect or was otherwise considered medically important. TEAEs were defined as events that started or worsened after first dose of study intervention until 30 days after last dose. TEAEs included both serious and non-serious TEAEs. Treatment-related TEAEs is defined as reasonably related to the study intervention.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Approximately 2 years 11 months&#x27;&#125; |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | Field &#96;outcomesModule.secondaryOutcomes.&#91;13&#93;&#96; changed from &#96;&#123;&#x27;measure&#x27;&#58; &#x27;Part 1A and IB&#58; Best Overall Response According to Response C                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
