---
title: "NCT07098338 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|:----------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-10 07&#58;03&#58;50 | **statusModule.statusVerifiedDate**: 2025-09                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **statusModule.statusVerifiedDate**: 2026-01                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-02-10 07&#58;03&#58;50 | **statusModule.primaryCompletionDateStruct.date**: 2027-03-21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | **statusModule.primaryCompletionDateStruct.date**: 2029-04-06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-02-10 07&#58;03&#58;50 | **statusModule.lastUpdateSubmitDate**: 2025-09-25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | **statusModule.lastUpdateSubmitDate**: 2026-02-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-02-10 07&#58;03&#58;50 | **statusModule.lastUpdatePostDateStruct.date**: 2025-09-30                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-05                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-02-10 07&#58;03&#58;50 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | Field &#96;descriptionModule.detailedDescription&#96; changed from &#96;The master protocol will include 3 sub-studies, each focused on a specific disease population.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-02-10 07&#58;03&#58;50 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | * Sub-study 1 will investigate rilvegostomig± ramucirumab in 1L non-actionable genomic alterations (AGA) NSCLC with PD-L1 ≥50%.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-02-10 07&#58;03&#58;50 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | * Sub-study 2 will investigate rilvegostomig + ramucirumab in 1L non-actionable genomic alterations (AGA) NSCLC with PD-L1 1-49%.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-02-10 07&#58;03&#58;50 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | * Sub-study 3 will investigate Dato-DXd + ramucirumab ± rilvegostomig in 2L AGA+                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-02-10 07&#58;03&#58;50 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | Each sub-study may include 2 parts (unless stated in the individual sub study protocols)&#58; Part A&#58; one or more Safety Run-in cohort(s), and Part B&#58; one or more Dose Expansion cohort(s).&#96; to &#96;The master protocol will include 3 sub-studies, each focused on a specific disease population.                                                                                                                                                                                                                                                                                                                                                         |
| 2026-02-10 07&#58;03&#58;50 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | * Sub-study 1 will investigate rilvegostomig± ramucirumab in 1L non-actionable genomic alterations (AGA) NSCLC with PD-L1 ≥50%.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-02-10 07&#58;03&#58;50 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | * Sub-study 2 will investigate rilvegostomig + ramucirumab in 1L non-actionable genomic alterations (AGA) NSCLC with PD-L1 1-49%.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-02-10 07&#58;03&#58;50 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | * Sub-study 3 will investigate Dato-DXd + ramucirumab ± rilvegostomig in 2/3L AGA+                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-02-10 07&#58;03&#58;50 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | Each sub-study may include 2 parts (unless stated in the individual sub study protocols)&#58; Part A&#58; one or more Safety Run-in cohort(s), and Part B&#58; one or more Dose Expansion cohort(s).&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-02-10 07&#58;03&#58;50 | **outcomesModule.primaryOutcomes.&#91;1&#93;description**: ORR is defined as the proportion of participants who have a confirmed CR (complete response) or confirmed PR (partial response), determined by the Investigator at local site per RECIST 1.1                                                                                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.primaryOutcomes.&#91;1&#93;description**: ORR is defined as the proportion of participants who have a confirmed CR (complete response) or confirmed PR (partial response) per RECIST 1.1                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-02-10 07&#58;03&#58;50 | **outcomesModule.secondaryOutcomes.&#91;2&#93;description**: PFS is defined as the time from the start of treatment until the date of objective disease progression or death (by any cause in the absence of progression) per RECIST 1.1 as assessed by Investigator.                                                                                                                                                                                                                                                                                                                                                                                                  | **outcomesModule.secondaryOutcomes.&#91;2&#93;description**: PFS is defined as the time from the start of treatment until the date of objective disease progression or death (by any cause in the absence of progression) per RECIST 1.1.                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;10&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;10&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;11&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;11&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;12&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;12&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;14&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;14&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;16&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;16&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;17&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;17&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;19&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;19&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;26&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;26&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;28&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;28&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;29&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;29&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;32&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;32&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;33&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;33&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;34&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;34&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;36&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;36&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;37&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;37&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;38&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;38&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;40&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;40&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;41&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;41&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;42&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;42&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;43&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;43&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;44&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;44&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;46&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;46&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;48&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;48&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;50&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;50&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **contactsLocationsModule.locations.&#91;51&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;51&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **armsInterventionsModule.armGroups.&#91;0&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Sub-study 1, investigate rilvegostomig± ramucirumab in 1L non-AGA NSCLC with PD-L1 ≥50%&#x27;, &#x27;type&#x27;&#58; &#x27;EXPERIMENTAL&#x27;, &#x27;description&#x27;&#58; &#x27;Participants will receive rilvegostomig ± ramucirumab until RECIST 1.1-defined radiological progression as assessed by the investigator, unacceptable toxicity, withdrawal of consent, or other discontinuation criterion&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; Rilvegostomig&#x27;, &#x27;Drug&#58; Ramucirumab&#x27;&#93;&#125;                                     | **armsInterventionsModule.armGroups.&#91;0&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Sub-study 1, investigate rilvegostomig± ramucirumab in 1L non-AGA NSCLC with PD-L1 ≥50%&#x27;, &#x27;type&#x27;&#58; &#x27;EXPERIMENTAL&#x27;, &#x27;description&#x27;&#58; &#x27;Participants will receive rilvegostomig ± ramucirumab until RECIST 1.1-defined radiological progression, unacceptable toxicity, withdrawal of consent, or other discontinuation criterion&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; Rilvegostomig&#x27;, &#x27;Drug&#58; Ramucirumab&#x27;&#93;&#125;                                                                       |
| 2026-02-10 07&#58;03&#58;50 | **armsInterventionsModule.interventions.&#91;2&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Dato-DXd&#x27;, &#x27;description&#x27;&#58; &#x27;Dato-DXd will be administered as IV infusion.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Sub-study 3, investigate Dato-DXd + ramucirumab ± rilvegostomig in 2L AGA+ NSCLC&#x27;&#93;, &#x27;otherNames&#x27;&#58; &#91;&#x27;DS-1062&#x27;&#93;&#125;                                                                                                                                                                                                                       | **armsInterventionsModule.interventions.&#91;2&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Dato-DXd&#x27;, &#x27;description&#x27;&#58; &#x27;Dato-DXd will be administered as IV infusion.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Sub-study 3, investigate Dato-DXd + ramucirumab ± rilvegostomig in 2/3L AGA+ NSCLC&#x27;&#93;, &#x27;otherNames&#x27;&#58; &#91;&#x27;DS-1062&#x27;&#93;&#125;                                                                                                                                                                                                                       |
| 2026-02-10 07&#58;03&#58;50 | **armsInterventionsModule.interventions.&#91;0&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Rilvegostomig&#x27;, &#x27;description&#x27;&#58; &#x27;Rilvegostomig will be administered as IV infusion.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Sub-study 1, investigate rilvegostomig± ramucirumab in 1L non-AGA NSCLC with PD-L1 ≥50%&#x27;, &#x27;Sub-study 2, investigate rilvegostomig + ramucirumab in 1L non-AGA NSCLC with PD-L1 1-49%&#x27;, &#x27;Sub-study 3, investigate Dato-DXd + ramucirumab ± rilvegostomig in 2L AGA+ NSCLC&#x27;&#93;, &#x27;otherNames&#x27;&#58; &#91;&#x27;AZD2936&#x27;&#93;&#125; | **armsInterventionsModule.interventions.&#91;0&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Rilvegostomig&#x27;, &#x27;description&#x27;&#58; &#x27;Rilvegostomig will be administered as IV infusion.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Sub-study 1, investigate rilvegostomig± ramucirumab in 1L non-AGA NSCLC with PD-L1 ≥50%&#x27;, &#x27;Sub-study 2, investigate rilvegostomig + ramucirumab in 1L non-AGA NSCLC with PD-L1 1-49%&#x27;, &#x27;Sub-study 3, investigate Dato-DXd + ramucirumab ± rilvegostomig in 2/3L AGA+ NSCLC&#x27;&#93;, &#x27;otherNames&#x27;&#58; &#91;&#x27;AZD2936&#x27;&#93;&#125; |
| 2026-02-10 07&#58;03&#58;50 | **armsInterventionsModule.armGroups.&#91;2&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Sub-study 3, investigate Dato-DXd + ramucirumab ± rilvegostomig in 2L AGA+ NSCLC&#x27;, &#x27;type&#x27;&#58; &#x27;EXPERIMENTAL&#x27;, &#x27;description&#x27;&#58; &#x27;Participants will receive Dato-DXd + ramucirumab ± rilvegostomig until RECIST 1.1-defined radiological progression as assessed by the investigator, unacceptable toxicity, withdrawal of consent, or other discontinuation criterion&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; Rilvegostomig&#x27;, &#x27;Drug&#58; Ramucirumab&#x27;, &#x27;Drug&#58; Dato-DXd&#x27;&#93;&#125; | **armsInterventionsModule.armGroups.&#91;2&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Sub-study 3, investigate Dato-DXd + ramucirumab ± rilvegostomig in 2/3L AGA+ NSCLC&#x27;, &#x27;type&#x27;&#58; &#x27;EXPERIMENTAL&#x27;, &#x27;description&#x27;&#58; &#x27;Participants will receive Dato-DXd + ramucirumab ± rilvegostomig until RECIST 1.1-defined radiological progression, unacceptable toxicity, withdrawal of consent, or other discontinuation criterion&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; Rilvegostomig&#x27;, &#x27;Drug&#58; Ramucirumab&#x27;, &#x27;Drug&#58; Dato-DXd&#x27;&#93;&#125;                                 |
| 2026-02-10 07&#58;03&#58;50 | **armsInterventionsModule.armGroups.&#91;1&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Sub-study 2, investigate rilvegostomig + ramucirumab in 1L non-AGA NSCLC with PD-L1 1-49%&#x27;, &#x27;type&#x27;&#58; &#x27;EXPERIMENTAL&#x27;, &#x27;description&#x27;&#58; &#x27;Participants will receive rilvegostomig + ramucirumab until RECIST 1.1-defined radiological progression as assessed by the investigator, unacceptable toxicity, withdrawal of consent, or other discontinuation criterion&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; Rilvegostomig&#x27;, &#x27;Drug&#58; Ramucirumab&#x27;&#93;&#125;                                   | **armsInterventionsModule.armGroups.&#91;1&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Sub-study 2, investigate rilvegostomig + ramucirumab in 1L non-AGA NSCLC with PD-L1 1-49%&#x27;, &#x27;type&#x27;&#58; &#x27;EXPERIMENTAL&#x27;, &#x27;description&#x27;&#58; &#x27;Participants will receive rilvegostomig + ramucirumab until RECIST 1.1-defined radiological progression, unacceptable toxicity, withdrawal of consent, or other discontinuation criterion&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; Rilvegostomig&#x27;, &#x27;Drug&#58; Ramucirumab&#x27;&#93;&#125;                                                                     |
| 2026-02-10 07&#58;03&#58;50 | **armsInterventionsModule.interventions.&#91;1&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Ramucirumab&#x27;, &#x27;description&#x27;&#58; &#x27;Ramucirumab will be administered as IV infusion.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Sub-study 1, investigate rilvegostomig± ramucirumab in 1L non-AGA NSCLC with PD-L1 ≥50%&#x27;, &#x27;Sub-study 2, investigate rilvegostomig + ramucirumab in 1L non-AGA NSCLC with PD-L1 1-49%&#x27;, &#x27;Sub-study 3, investigate Dato-DXd + ramucirumab ± rilvegostomig in 2L AGA+ NSCLC&#x27;&#93;, &#x27;otherNames&#x27;&#58; &#91;&#x27;Cyramza&#x27;&#93;&#125;     | **armsInterventionsModule.interventions.&#91;1&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Ramucirumab&#x27;, &#x27;description&#x27;&#58; &#x27;Ramucirumab will be administered as IV infusion.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Sub-study 1, investigate rilvegostomig± ramucirumab in 1L non-AGA NSCLC with PD-L1 ≥50%&#x27;, &#x27;Sub-study 2, investigate rilvegostomig + ramucirumab in 1L non-AGA NSCLC with PD-L1 1-49%&#x27;, &#x27;Sub-study 3, investigate Dato-DXd + ramucirumab ± rilvegostomig in 2/3L AGA+ NSCLC&#x27;&#93;, &#x27;otherNames&#x27;&#58; &#91;&#x27;Cyramza&#x27;&#93;&#125;     |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2026-01                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2026-02-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | **statusModule.lastUpdateSubmitDate**: 2026-04-28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-05                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;2&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;2&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;5&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;5&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;9&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;9&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;23&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;23&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;25&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;25&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;26&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;26&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;28&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;28&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;33&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;33&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;34&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;34&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;38&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;38&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;43&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;43&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;49&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;49&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;52&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;52&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;55&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;55&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;58&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;58&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;58&#93;city**: Taoyuan District                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **contactsLocationsModule.locations.&#91;58&#93;city**: Taoyuan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;58&#93;geoPoint.lat**: 24.9896                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | **contactsLocationsModule.locations.&#91;58&#93;geoPoint.lat**: 24.99368                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;58&#93;geoPoint.lon**: 121.3187                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **contactsLocationsModule.locations.&#91;58&#93;geoPoint.lon**: 121.29696                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-28 03&#58;42&#58;12 | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **statusModule.statusVerifiedDate**: 2026-05                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-28 03&#58;42&#58;12 | **statusModule.lastUpdateSubmitDate**: 2026-04-28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | **statusModule.lastUpdateSubmitDate**: 2026-05-25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-05-28 03&#58;42&#58;12 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-05-28 03&#58;42&#58;12 | **contactsLocationsModule.locations.&#91;14&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;14&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.statusVerifiedDate**: 2026-05                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **statusModule.statusVerifiedDate**: 2026-06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.lastUpdateSubmitDate**: 2026-05-25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | **statusModule.lastUpdateSubmitDate**: 2026-06-30                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **statusModule.lastUpdatePostDateStruct.date**: 2026-07-01                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;05 | **contactsLocationsModule.locations.&#91;0&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;0&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-07-28 00&#58;26&#58;05 | **contactsLocationsModule.locations.&#91;33&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;33&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | **contactsLocationsModule.locations.&#91;66&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;66&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | **contactsLocationsModule.locations.&#91;67&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;67&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | **contactsLocationsModule.locations.&#91;68&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;68&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | **contactsLocationsModule.locations.&#91;79&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;79&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | **contactsLocationsModule.locations.&#91;82&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;82&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
