---
title: "NCT06627647 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                 | After                                                                                                                                                                                                                                                                                                                                                                                                |
|:----------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-16 21&#58;08&#58;12 | **statusModule.statusVerifiedDate**: 2025-12                                                                                                                                                                                                                                                                                                                           | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                                                         |
| 2026-02-16 21&#58;08&#58;12 | **statusModule.lastUpdateSubmitDate**: 2025-12-19                                                                                                                                                                                                                                                                                                                      | **statusModule.lastUpdateSubmitDate**: 2026-02-11                                                                                                                                                                                                                                                                                                                                                    |
| 2026-02-16 21&#58;08&#58;12 | **statusModule.lastUpdatePostDateStruct.date**: 2025-12-22                                                                                                                                                                                                                                                                                                             | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-12                                                                                                                                                                                                                                                                                                                                           |
| 2026-02-16 21&#58;08&#58;12 | **contactsLocationsModule.locations.&#91;16&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;16&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                 |
| 2026-02-16 21&#58;08&#58;12 | **contactsLocationsModule.locations.&#91;23&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;23&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                 |
| 2026-02-16 21&#58;08&#58;12 | **contactsLocationsModule.locations.&#91;179&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;179&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                 |
| 2026-02-16 21&#58;08&#58;12 | **contactsLocationsModule.locations.&#91;183&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;183&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                 |
| 2026-02-16 21&#58;08&#58;12 | **contactsLocationsModule.locations.&#91;196&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;196&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                |
| 2026-02-16 21&#58;08&#58;12 | **contactsLocationsModule.locations.&#91;202&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;202&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                |
| 2026-02-16 21&#58;08&#58;12 | **contactsLocationsModule.locations.&#91;232&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;232&#93;status**: SUSPENDED                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-28 02&#58;22&#58;27 | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                           | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-28 02&#58;22&#58;27 | **statusModule.lastUpdateSubmitDate**: 2026-02-11                                                                                                                                                                                                                                                                                                                      | **statusModule.lastUpdateSubmitDate**: 2026-03-26                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-28 02&#58;22&#58;27 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-12                                                                                                                                                                                                                                                                                                             | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-27                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-28 02&#58;22&#58;27 | **contactsLocationsModule.locations.&#91;31&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                   | **contactsLocationsModule.locations.&#91;31&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-28 02&#58;22&#58;27 | **contactsLocationsModule.locations.&#91;89&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;89&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-28 02&#58;22&#58;27 | **contactsLocationsModule.locations.&#91;146&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;146&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                |
| 2026-03-28 02&#58;22&#58;27 | **contactsLocationsModule.locations.&#91;152&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;152&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                |
| 2026-03-28 02&#58;22&#58;27 | **contactsLocationsModule.locations.&#91;172&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;172&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                |
| 2026-03-28 02&#58;22&#58;27 | **contactsLocationsModule.locations.&#91;178&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;178&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                |
| 2026-03-28 02&#58;22&#58;27 | **contactsLocationsModule.locations.&#91;211&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;211&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                           | **statusModule.statusVerifiedDate**: 2026-05                                                                                                                                                                                                                                                                                                                                                         |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.lastUpdateSubmitDate**: 2026-03-26                                                                                                                                                                                                                                                                                                                      | **statusModule.lastUpdateSubmitDate**: 2026-05-21                                                                                                                                                                                                                                                                                                                                                    |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-27                                                                                                                                                                                                                                                                                                             | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-22                                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;20&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;20&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;37&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;37&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;127&#93;geoPoint.lat**: 22.8836                                                                                                                                                                                                                                                                                               | **contactsLocationsModule.locations.&#91;127&#93;geoPoint.lat**: 30.17415                                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;127&#93;geoPoint.lon**: 107.264                                                                                                                                                                                                                                                                                               | **contactsLocationsModule.locations.&#91;127&#93;geoPoint.lon**: 120.97629                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;255&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;255&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;256&#93;city**: Taoyuan District                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;256&#93;city**: Taoyuan                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;256&#93;geoPoint.lat**: 24.9896                                                                                                                                                                                                                                                                                               | **contactsLocationsModule.locations.&#91;256&#93;geoPoint.lat**: 24.99368                                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;256&#93;geoPoint.lon**: 121.3187                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;256&#93;geoPoint.lon**: 121.29696                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;259&#93;geoPoint.lat**: 13.7775                                                                                                                                                                                                                                                                                               | **contactsLocationsModule.locations.&#91;259&#93;geoPoint.lat**: 13.77706                                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;259&#93;geoPoint.lon**: 100.51977                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;259&#93;geoPoint.lon**: 100.51958                                                                                                                                                                                                                                                                                                                           |
| 2026-07-28 00&#58;26&#58;06 | **identificationModule.briefTitle**: A Global Phase III Study of Rilvegostomig or Pembrolizumab Plus Chemotherapy for First-Line Treatment of Metastatic Non-squamous NSCLC                                                                                                                                                                                            | **identificationModule.briefTitle**: A Global Phase III Study of Rilvegostomig or Pembrolizumab Plus Chemotherapy for First-Line Treatment of Locally Advanced or Metastatic Non-Squamous NSCLC                                                                                                                                                                                                      |
| 2026-07-28 00&#58;26&#58;06 | **identificationModule.officialTitle**: A Phase III, Randomized, Double-blind, Multicenter, Global Study of Rilvegostomig or Pembrolizumab in Combination With Platinum-based Chemotherapy for the First-line Treatment of Patients With Metastatic Non-squamous Non-small Cell Lung Cancer Whose Tumors Express PD-L1 (ARTEMIDE-Lung03)                               | **identificationModule.officialTitle**: A Phase III, Randomized, Double-blind, Multicenter, Global Study of Rilvegostomig or Pembrolizumab in Combination With Platinum-based Chemotherapy for the First-line Treatment of Patients With Locally Advanced or Metastatic Non-squamous Non-small Cell Lung Cancer Whose Tumors Express PD-L1 (ARTEMIDE-Lung03)                                         |
| 2026-07-28 00&#58;26&#58;06 | **statusModule.statusVerifiedDate**: 2026-05                                                                                                                                                                                                                                                                                                                           | **statusModule.statusVerifiedDate**: 2026-07                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | **statusModule.primaryCompletionDateStruct.date**: 2029-05-10                                                                                                                                                                                                                                                                                                          | **statusModule.primaryCompletionDateStruct.date**: 2030-11-18                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;06 | **statusModule.completionDateStruct.date**: 2030-03-25                                                                                                                                                                                                                                                                                                                 | **statusModule.completionDateStruct.date**: 2030-11-18                                                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | **statusModule.lastUpdateSubmitDate**: 2026-05-21                                                                                                                                                                                                                                                                                                                      | **statusModule.lastUpdateSubmitDate**: 2026-07-13                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-22                                                                                                                                                                                                                                                                                                             | **statusModule.lastUpdatePostDateStruct.date**: 2026-07-14                                                                                                                                                                                                                                                                                                                                           |
| 2026-07-28 00&#58;26&#58;06 | **descriptionModule.briefSummary**: The purpose of ARTEMIDE-Lung03 is to evaluate the efficacy and safety of rilvegostomig compared to pembrolizumab, both in combination with platinum-based doublet chemotherapy, as a first-line treatment of patients with non-squamous mNSCLC whose tumors express PD-L1.                                                         | **descriptionModule.briefSummary**: The purpose of ARTEMIDE-Lung03 is to evaluate the efficacy and safety of rilvegostomig compared to pembrolizumab, both in combination with platinum-based doublet chemotherapy, as a first-line treatment of patients with locally advanced or metastatic non-squamous NSCLC whose tumors express PD-L1.                                                         |
| 2026-07-28 00&#58;26&#58;06 | **descriptionModule.detailedDescription**: This is a Phase III, two-arm, randomized, double-blind, global, multicenter study assessing the efficacy and safety of rilvegostomig compared to pembrolizumab, both in combination with platinum-based doublet chemotherapy, as a 1L treatment for patients with non-squamous mNSCLC whose tumors express PD-L1 (TC ≥ 1%). | **descriptionModule.detailedDescription**: This is a Phase III, two-arm, randomized, double-blind, global, multicenter study assessing the efficacy and safety of rilvegostomig compared to pembrolizumab, both in combination with platinum-based doublet chemotherapy, as a 1L treatment for patients with locally advanced or metastatic non-squamous NSCLC whose tumors express PD-L1 (TC ≥ 1%). |
| 2026-07-28 00&#58;26&#58;06 | **designModule.enrollmentInfo.count**: 878                                                                                                                                                                                                                                                                                                                             | **designModule.enrollmentInfo.count**: 1160                                                                                                                                                                                                                                                                                                                                                          |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.primaryOutcomes.&#91;0&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                   | **outcomesModule.primaryOutcomes.&#91;0&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.primaryOutcomes.&#91;1&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                   | **outcomesModule.primaryOutcomes.&#91;1&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;0&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;0&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;1&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;1&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;2&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;2&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;3&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;3&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;4&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;4&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;5&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;5&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;6&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;6&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;7&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;7&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;8&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;8&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;9&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                 | **outcomesModule.secondaryOutcomes.&#91;9&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                      |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * Histologically or cytologically documented non-squamous NSCLC.                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * Stage IV mNSCLC (based on the American Joint Committee on Cancer Edition 8) not amenable to curative treatment.                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * Absence of sensitizing EGFR mutations (including, but not limited to, exon 19 deletion and exon 21 L858R, exon 21 L861Q, exon 18 G719X, and exon 20 S768I mutations) and ALK and ROS1 rearrangements.                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * Absence of documented tumor genomic mutation results from tests conducted as part of standard local practice in any other actionable driver oncogenes for which there are locally approved targeted 1L therapies.                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * Provision of acceptable tumor sample, to confirm tumor PD-L1 expression TC ≥ 1%.                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * At least one lesion not previously irradiated that qualifies as a RECIST 1.1 TL at baseline and can be accurately measured at baseline as ≥ 10 mm in the longest diameter (except lymph nodes, which must have short axis ≥ 15 mm) with CT or MRI and is suitable for accurate repeated measurements.                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * Adequat&#96; to &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * Histologically or cytologically documented non-squamous NSCLC.                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * Stage III B/C or IV NSCLC (based on the American Joint Committee on Cancer Edition 8) not amenable to curative treatment.                                                                                                                                                                                                                                                                          |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * Absence of sensitizing EGFR mutations (including, but not limited to, exon 19 deletion and exon 21 L858R, exon 21 L861Q, exon 18 G719X, and exon 20 S768I mutations) and ALK and ROS1 rearrangements.                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * Absence of documented tumor genomic mutation results from tests conducted as part of standard local practice in any other actionable driver oncogenes for which there are locally approved and available targeted 1L therapies.                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * Provision of acceptable tumor sample, to confirm tumor PD-L1 expression TC ≥ 1%.                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | * At least one lesion not previously irradiated that qualifies as a RECIST 1.1 TL at baseline and can be accurately measured at baseline as ≥ 10 mm in the longest diameter (except lymph nodes, which must have short axis ≥ 15 mm) with CT or MRI and is suitable for accurate repeated&#96;                                                                                                       |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;34&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;34&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;113&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;113&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;124&#93;status**: ACTIVE_NOT_RECRUITING                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;124&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;131&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;131&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;147&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;147&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;149&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;149&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;149&#93;city**: Cologne                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;149&#93;city**: Bochum                                                                                                                                                                                                                                                                                                                                      |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;149&#93;zip**: 51109                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;149&#93;zip**: 44791                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;149&#93;geoPoint.lat**: 50.93333                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;149&#93;geoPoint.lat**: 51.48165                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;149&#93;geoPoint.lon**: 6.95                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;149&#93;geoPoint.lon**: 7.21648                                                                                                                                                                                                                                                                                                                             |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;150&#93;city**: Esslingen am Neckar                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;150&#93;city**: Cologne                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;150&#93;zip**: 73730                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;150&#93;zip**: 51109                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;150&#93;geoPoint.lat**: 48.73961                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;150&#93;geoPoint.lat**: 50.93333                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;150&#93;geoPoint.lon**: 9.30473                                                                                                                                                                                                                                                                                               | **contactsLocationsModule.locations.&#91;150&#93;geoPoint.lon**: 6.95                                                                                                                                                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;151&#93;city**: Frankfurt                                                                                                                                                                                                                                                                                                     | **contactsLocationsModule.locations.&#91;151&#93;city**: Esslingen am Neckar                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;151&#93;zip**: 60488                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;151&#93;zip**: 73730                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;151&#93;geoPoint.lat**: 49.68333                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;151&#93;geoPoint.lat**: 48.73961                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;151&#93;geoPoint.lon**: 10.53333                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;151&#93;geoPoint.lon**: 9.30473                                                                                                                                                                                                                                                                                                                             |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;152&#93;city**: Gauting                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;152&#93;city**: Frankfurt                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;152&#93;zip**: 82131                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;152&#93;zip**: 60488                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;152&#93;geoPoint.lat**: 48.06919                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;152&#93;geoPoint.lat**: 49.68333                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;152&#93;geoPoint.lon**: 11.37703                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;152&#93;geoPoint.lon**: 10.53333                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;153&#93;city**: Giessen                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;153&#93;city**: Gauting                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;153&#93;zip**: 35392                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;153&#93;zip**: 82131                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;153&#93;geoPoint.lat**: 50.58727                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;153&#93;geoPoint.lat**: 48.06919                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;153&#93;geoPoint.lon**: 8.67554                                                                                                                                                                                                                                                                                               | **contactsLocationsModule.locations.&#91;153&#93;geoPoint.lon**: 11.37703                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;154&#93;city**: Großhansdorf                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;154&#93;city**: Giessen                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;154&#93;zip**: 22927                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;154&#93;zip**: 35392                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;154&#93;geoPoint.lat**: 53.66528                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;154&#93;geoPoint.lat**: 50.58727                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;154&#93;geoPoint.lon**: 10.28552                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;154&#93;geoPoint.lon**: 8.67554                                                                                                                                                                                                                                                                                                                             |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;155&#93;city**: Hamburg                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;155&#93;city**: Großhansdorf                                                                                                                                                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;155&#93;zip**: 20251                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;155&#93;zip**: 22927                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;155&#93;geoPoint.lat**: 53.55073                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;155&#93;geoPoint.lat**: 53.66528                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;155&#93;geoPoint.lon**: 9.99302                                                                                                                                                                                                                                                                                               | **contactsLocationsModule.locations.&#91;155&#93;geoPoint.lon**: 10.28552                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;156&#93;city**: Hanover                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;156&#93;city**: Hamburg                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;156&#93;zip**: 30459                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;156&#93;zip**: 20251                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;156&#93;geoPoint.lat**: 52.37052                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;156&#93;geoPoint.lat**: 53.55073                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                      | Field &#96;contactsLocationsMod                                                                                                                                                                                                                                                                                                                                                                      |
