---
title: "NCT04354246 Change History"
---

| Timestamp                   | Before                                                        | After                                                         |
|:----------------------------|:--------------------------------------------------------------|:--------------------------------------------------------------|
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2025-05                  | **statusModule.statusVerifiedDate**: 2026-05                  |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.overallStatus**: ACTIVE_NOT_RECRUITING         | **statusModule.overallStatus**: COMPLETED                     |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.primaryCompletionDateStruct.date**: 2025-12-30 | **statusModule.primaryCompletionDateStruct.date**: 2026-04-01 |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.primaryCompletionDateStruct.type**: ESTIMATED  | **statusModule.primaryCompletionDateStruct.type**: ACTUAL     |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.completionDateStruct.date**: 2025-12-30        | **statusModule.completionDateStruct.date**: 2026-04-01        |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.completionDateStruct.type**: ESTIMATED         | **statusModule.completionDateStruct.type**: ACTUAL            |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2025-05-18             | **statusModule.lastUpdateSubmitDate**: 2026-05-11             |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2025-05-22    | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-12    |
| 2026-05-26 02&#58;38&#58;40 | **designModule.enrollmentInfo.count**: 110                    | **designModule.enrollmentInfo.count**: 94                     |
| 2026-05-26 02&#58;38&#58;40 | **designModule.enrollmentInfo.type**: ESTIMATED               | **designModule.enrollmentInfo.type**: ACTUAL                  |
