---
title: "NCT05568095 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | After                                                                                                                                                                                                                                                                                                                                                                                                               |
|:----------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-03-05 00&#58;58&#58;08 | **statusModule.lastUpdateSubmitDate**: 2026-01-30                                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.lastUpdateSubmitDate**: 2026-03-02                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-05 00&#58;58&#58;08 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-02                                                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-04                                                                                                                                                                                                                                                                                                                                                          |
| 2026-04-03 02&#58;29&#58;25 | **statusModule.lastUpdateSubmitDate**: 2026-03-02                                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.lastUpdateSubmitDate**: 2026-03-31                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-03 02&#58;29&#58;25 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-04                                                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-02                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2025-04                                                                                                                                                                                                                                                                                                                                                                                                                                   | **statusModule.statusVerifiedDate**: 2026-05                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2026-03-31                                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.lastUpdateSubmitDate**: 2026-05-06                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-02                                                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-08                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;8&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;SCRI - Florida Cancer Specialists - North Region Research Office&#x27;, &#x27;city&#x27;&#58; &#x27;St. Petersburg&#x27;, &#x27;state&#x27;&#58; &#x27;Florida&#x27;, &#x27;zip&#x27;&#58; &#x27;33705&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 27.77086, &#x27;lon&#x27;&#58; -82.67927&#125;&#125;           | **contactsLocationsModule.locations.&#91;8&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;St. Petersburg&#x27;, &#x27;state&#x27;&#58; &#x27;Florida&#x27;, &#x27;zip&#x27;&#58; &#x27;33705&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 27.77086, &#x27;lon&#x27;&#58; -82.67927&#125;&#125;   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;158&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Szpital Miejski w Tychach&#x27;, &#x27;city&#x27;&#58; &#x27;Tychy&#x27;, &#x27;country&#x27;&#58; &#x27;Poland&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 50.13717, &#x27;lon&#x27;&#58; 18.96641&#125;&#125;                                                                                                                                                     | **contactsLocationsModule.locations.&#91;158&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Edirne&#x27;, &#x27;country&#x27;&#58; &#x27;Turkey (Türkiye)&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.67719, &#x27;lon&#x27;&#58; 26.55597&#125;&#125;                                                                                           |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;150&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Hospital Maria Auxiliadora&#x27;, &#x27;city&#x27;&#58; &#x27;San Juán de Miraflores&#x27;, &#x27;country&#x27;&#58; &#x27;Peru&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -11.93531, &#x27;lon&#x27;&#58; -75.41647&#125;&#125;                                                                                                                                   | **contactsLocationsModule.locations.&#91;150&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Santander&#x27;, &#x27;country&#x27;&#58; &#x27;Spain&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.46589, &#x27;lon&#x27;&#58; -3.80493&#125;&#125;                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;55&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Sunnybrook Health Sciences Centre - Bayview Campus&#x27;, &#x27;city&#x27;&#58; &#x27;Toronto&#x27;, &#x27;country&#x27;&#58; &#x27;Canada&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.70643, &#x27;lon&#x27;&#58; -79.39864&#125;&#125;                                                                                                                          | **contactsLocationsModule.locations.&#91;55&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Guangzhou&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 23.11667, &#x27;lon&#x27;&#58; 113.25&#125;&#125;                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;102&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Dél-pesti Centrumkórház - Országos Hematológiai és Infektológiai Intézet&#x27;, &#x27;city&#x27;&#58; &#x27;Budapest&#x27;, &#x27;country&#x27;&#58; &#x27;Hungary&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 47.49835, &#x27;lon&#x27;&#58; 19.04045&#125;&#125;                                                                                                  | **contactsLocationsModule.locations.&#91;102&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Nagaizumi-cho&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;&#125;                                                                                                                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;111&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Istituto di Ricovero e Cura a Carattere Scientifico (IRCCS) - Ospedale San Raffaele&#x27;, &#x27;city&#x27;&#58; &#x27;Milan&#x27;, &#x27;country&#x27;&#58; &#x27;Italy&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 45.46427, &#x27;lon&#x27;&#58; 9.18951&#125;&#125;                                                                                             | **contactsLocationsModule.locations.&#91;111&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Kaunas&#x27;, &#x27;country&#x27;&#58; &#x27;Lithuania&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 54.90156, &#x27;lon&#x27;&#58; 23.90909&#125;&#125;                                                                                                  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;40&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;CORI&#x27;, &#x27;city&#x27;&#58; &#x27;La Rioja&#x27;, &#x27;country&#x27;&#58; &#x27;Argentina&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -29.41328, &#x27;lon&#x27;&#58; -66.85637&#125;&#125;                                                                                                                                                                   | **contactsLocationsModule.locations.&#91;40&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Natal&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -5.795, &#x27;lon&#x27;&#58; -35.20944&#125;&#125;                                                                                                        |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;105&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Pécsi Tudományegyetem Klinikai Központ&#x27;, &#x27;city&#x27;&#58; &#x27;Pécs&#x27;, &#x27;country&#x27;&#58; &#x27;Hungary&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 46.07617, &#x27;lon&#x27;&#58; 18.22814&#125;&#125;                                                                                                                                        | **contactsLocationsModule.locations.&#91;105&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Osaka&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.69379, &#x27;lon&#x27;&#58; 135.50107&#125;&#125;                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;34&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;The Center for Cancer &amp; Blood Disorders - Fort Worth&#x27;, &#x27;city&#x27;&#58; &#x27;Fort Worth&#x27;, &#x27;state&#x27;&#58; &#x27;Texas&#x27;, &#x27;zip&#x27;&#58; &#x27;76104&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 32.72541, &#x27;lon&#x27;&#58; -97.32085&#125;&#125;                        | **contactsLocationsModule.locations.&#91;34&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;La Rioja&#x27;, &#x27;country&#x27;&#58; &#x27;Argentina&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -29.41328, &#x27;lon&#x27;&#58; -66.85637&#125;&#125;                                                                                               |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;10&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;SCRI - Florida Cancer Specialists - East Region Research Office&#x27;, &#x27;city&#x27;&#58; &#x27;West Palm Beach&#x27;, &#x27;state&#x27;&#58; &#x27;Florida&#x27;, &#x27;zip&#x27;&#58; &#x27;33401&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 26.71534, &#x27;lon&#x27;&#58; -80.05337&#125;&#125;          | **contactsLocationsModule.locations.&#91;10&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Louisville&#x27;, &#x27;state&#x27;&#58; &#x27;Kentucky&#x27;, &#x27;zip&#x27;&#58; &#x27;40202&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 38.25424, &#x27;lon&#x27;&#58; -85.75941&#125;&#125;     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;50&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Instituto Nacional de Câncer - Brazil&#x27;, &#x27;city&#x27;&#58; &#x27;Rio de Janeiro&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -22.90642, &#x27;lon&#x27;&#58; -43.18223&#125;&#125;                                                                                                                               | **contactsLocationsModule.locations.&#91;50&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Santiago&#x27;, &#x27;country&#x27;&#58; &#x27;Chile&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -33.45694, &#x27;lon&#x27;&#58; -70.64827&#125;&#125;                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;66&#93;**: &#123;&#x27;facility&#x27;&#58; &quot;Guangdong PR People&#x27;s Hospital&quot;, &#x27;city&#x27;&#58; &#x27;Guangzhou&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 23.11667, &#x27;lon&#x27;&#58; 113.25&#125;&#125;                                                                                                                                           | **contactsLocationsModule.locations.&#91;66&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Lyon&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 45.74906, &#x27;lon&#x27;&#58; 4.84789&#125;&#125;                                                                                                         |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;37&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Fred Hutchinson Cancer Center - Seattle Cancer Care Alliance (SCCA) Location&#x27;, &#x27;city&#x27;&#58; &#x27;Seattle&#x27;, &#x27;state&#x27;&#58; &#x27;Washington&#x27;, &#x27;zip&#x27;&#58; &#x27;98109&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 47.60621, &#x27;lon&#x27;&#58; -122.33207&#125;&#125; | **contactsLocationsModule.locations.&#91;37&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Murdoch&#x27;, &#x27;country&#x27;&#58; &#x27;Australia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -32.06987, &#x27;lon&#x27;&#58; 115.83757&#125;&#125;                                                                                                |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;119&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Chiba Cancer Center&#x27;, &#x27;city&#x27;&#58; &#x27;Chiba&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.6, &#x27;lon&#x27;&#58; 140.11667&#125;&#125;                                                                                                                                                               | **contactsLocationsModule.locations.&#91;119&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Mérida&#x27;, &#x27;zip&#x27;&#58; &#x27;97134&#x27;, &#x27;country&#x27;&#58; &#x27;Mexico&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 20.967, &#x27;lon&#x27;&#58; -89.62318&#125;&#125;                                                              |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;162&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Instituto Português de Oncologia do Porto Francisco Gentil&#x27;, &#x27;city&#x27;&#58; &#x27;Porto&#x27;, &#x27;country&#x27;&#58; &#x27;Portugal&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.1485, &#x27;lon&#x27;&#58; -8.61097&#125;&#125;                                                                                                                   | **contactsLocationsModule.locations.&#91;162&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Mamak&#x27;, &#x27;country&#x27;&#58; &#x27;Turkey (Türkiye)&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.48859, &#x27;lon&#x27;&#58; 32.36864&#125;&#125;                                                                                            |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;5&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Yale Cancer Center&#x27;, &#x27;city&#x27;&#58; &#x27;New Haven&#x27;, &#x27;state&#x27;&#58; &#x27;Connecticut&#x27;, &#x27;zip&#x27;&#58; &#x27;06520&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.30815, &#x27;lon&#x27;&#58; -72.92816&#125;&#125;                                                          | **contactsLocationsModule.locations.&#91;5&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;New Haven&#x27;, &#x27;state&#x27;&#58; &#x27;Connecticut&#x27;, &#x27;zip&#x27;&#58; &#x27;06520&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.30815, &#x27;lon&#x27;&#58; -72.92816&#125;&#125;    |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;106&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Hadassah University Hospital Ein Kerem&#x27;, &#x27;city&#x27;&#58; &#x27;Jerusalem&#x27;, &#x27;country&#x27;&#58; &#x27;Israel&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 31.76904, &#x27;lon&#x27;&#58; 35.21633&#125;&#125;                                                                                                                                    | **contactsLocationsModule.locations.&#91;106&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Osakasayama-shi&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;&#125;                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;108&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Davidoff Cancer Center&#x27;, &#x27;city&#x27;&#58; &#x27;Petah Tikva&#x27;, &#x27;country&#x27;&#58; &#x27;Israel&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 32.08707, &#x27;lon&#x27;&#58; 34.88747&#125;&#125;                                                                                                                                                  | **contactsLocationsModule.locations.&#91;108&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Saitama&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.90807, &#x27;lon&#x27;&#58; 139.65657&#125;&#125;                                                                                                    |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;161&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Fundação D. Anna de Sommer Champalimaud e Dr. Carlos Montez Champalimaud&#x27;, &#x27;city&#x27;&#58; &#x27;Lisbon&#x27;, &#x27;country&#x27;&#58; &#x27;Portugal&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 38.72509, &#x27;lon&#x27;&#58; -9.1498&#125;&#125;                                                                                                    | **contactsLocationsModule.locations.&#91;161&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Malatya&#x27;, &#x27;country&#x27;&#58; &#x27;Turkey (Türkiye)&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 38.35018, &#x27;lon&#x27;&#58; 38.31667&#125;&#125;                                                                                          |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;147&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Centro Hemato - Oncológico Privado (CHOP)&#x27;, &#x27;city&#x27;&#58; &#x27;Toluca&#x27;, &#x27;zip&#x27;&#58; &#x27;50120&#x27;, &#x27;country&#x27;&#58; &#x27;Mexico&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 19.28786, &#x27;lon&#x27;&#58; -99.65324&#125;&#125;                                                                                           | **contactsLocationsModule.locations.&#91;147&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Seoul&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 37.566, &#x27;lon&#x27;&#58; 126.9784&#125;&#125;                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;61&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Pontificia Universidad Catolica de Chile - Escuela De Medicina - Clinica UC San Carlos de Apoq&#x27;, &#x27;city&#x27;&#58; &#x27;Santiago&#x27;, &#x27;country&#x27;&#58; &#x27;Chile&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -33.45694, &#x27;lon&#x27;&#58; -70.64827&#125;&#125;                                                                             | **contactsLocationsModule.locations.&#91;61&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Zhengzhou&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.75778, &#x27;lon&#x27;&#58; 113.64861&#125;&#125;                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;88&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Evex Hospitals - Kutaisi Referral Hospital&#x27;, &#x27;city&#x27;&#58; &#x27;Kutaisi&#x27;, &#x27;zip&#x27;&#58; &#x27;4600&#x27;, &#x27;country&#x27;&#58; &#x27;Georgia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 42.26791, &#x27;lon&#x27;&#58; 42.69459&#125;&#125;                                                                                           | **contactsLocationsModule.locations.&#91;88&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Florence&#x27;, &#x27;country&#x27;&#58; &#x27;Italy&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.77925, &#x27;lon&#x27;&#58; 11.24626&#125;&#125;                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;4&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;UCLA Health - Santa Monica Cancer Care&#x27;, &#x27;city&#x27;&#58; &#x27;Santa Monica&#x27;, &#x27;state&#x27;&#58; &#x27;California&#x27;, &#x27;zip&#x27;&#58; &#x27;90404&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.01949, &#x27;lon&#x27;&#58; -118.49138&#125;&#125;                                   | **contactsLocationsModule.locations.&#91;4&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Santa Monica&#x27;, &#x27;state&#x27;&#58; &#x27;California&#x27;, &#x27;zip&#x27;&#58; &#x27;90404&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.01949, &#x27;lon&#x27;&#58; -118.49138&#125;&#125; |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;35&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Harris Health System&#x27;, &#x27;city&#x27;&#58; &#x27;Houston&#x27;, &#x27;state&#x27;&#58; &#x27;Texas&#x27;, &#x27;zip&#x27;&#58; &#x27;77054&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 29.76328, &#x27;lon&#x27;&#58; -95.36327&#125;&#125;                                                               | **contactsLocationsModule.locations.&#91;35&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Mar del Plata&#x27;, &#x27;country&#x27;&#58; &#x27;Argentina&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -38.00042, &#x27;lon&#x27;&#58; -57.5562&#125;&#125;                                                                                           |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;123&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Cancer Inst Hosp of JFCR&#x27;, &#x27;city&#x27;&#58; &#x27;Kōtō City&#x27;, &#x27;country&#x27;&#58; &#x27;Japan&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 32.77856, &#x27;lon&#x27;&#58; 130.74537&#125;&#125;                                                                                                                                                  | **contactsLocationsModule.locations.&#91;123&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;San Juán de Miraflores&#x27;, &#x27;country&#x27;&#58; &#x27;Peru&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -11.93531, &#x27;lon&#x27;&#58; -75.41647&#125;&#125;                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;39&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Hospital Británico de Buenos Aires&#x27;, &#x27;city&#x27;&#58; &#x27;Buenos Aires&#x27;, &#x27;country&#x27;&#58; &#x27;Argentina&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -34.61315, &#x27;lon&#x27;&#58; -58.37723&#125;&#125;                                                                                                                                 | **contactsLocationsModule.locations.&#91;39&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Ijuí&#x27;, &#x27;country&#x27;&#58; &#x27;Brazil&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -28.38778, &#x27;lon&#x27;&#58; -53.91472&#125;&#125;                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;82&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Hôpital de la Timone&#x27;, &#x27;city&#x27;&#58; &#x27;Marseille&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.29695, &#x27;lon&#x27;&#58; 5.38107&#125;&#125;                                                                                                                                                        | **contactsLocationsModule.locations.&#91;82&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Budapest&#x27;, &#x27;country&#x27;&#58; &#x27;Hungary&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 47.49835, &#x27;lon&#x27;&#58; 19.04045&#125;&#125;                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | Field &#96;contactsLocationsModule.locations.&#91;13&#93;&#96; changed from &#96;&#123;&#x27;facility&#x27;&#58; &#x27;Ochsner Cancer Institute&#x27;, &#x27;city&#x27;&#58; &#x27;New Orleans&#x27;, &#x27;state&#x27;&#58; &#x27;Louisian                                                                                                                                                                         |
| 2026-05-30 03&#58;31&#58;20 | **contactsLocationsModule.locations.&#91;117&#93;geoPoint.lat**: 29.02751                                                                                                                                                                                                                                                                                                                                                                                                      | **contactsLocationsModule.locations.&#91;117&#93;geoPoint.lat**: 14.90871                                                                                                                                                                                                                                                                                                                                           |
| 2026-05-30 03&#58;31&#58;20 | **contactsLocationsModule.locations.&#91;117&#93;geoPoint.lon**: -100.90108                                                                                                                                                                                                                                                                                                                                                                                                    | **contactsLocationsModule.locations.&#91;117&#93;geoPoint.lon**: -92.26131                                                                                                                                                                                                                                                                                                                                          |
| 2026-06-03 04&#58;13&#58;53 | **statusModule.lastUpdateSubmitDate**: 2026-05-06                                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.lastUpdateSubmitDate**: 2026-05-29                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-06-03 04&#58;13&#58;53 | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-08                                                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-02                                                                                                                                                                                                                                                                                                                                                          |
| 2026-06-24 14&#58;19&#58;40 | **contactsLocationsModule.locations.&#91;115&#93;geoPoint.lat**: 14.90871                                                                                                                                                                                                                                                                                                                                                                                                      | **contactsLocationsModule.locations.&#91;115&#93;geoPoint.lat**: 28.82333                                                                                                                                                                                                                                                                                                                                           |
| 2026-06-24 14&#58;19&#58;40 | **contactsLocationsModule.locations.&#91;115&#93;geoPoint.lon**: -92.26131                                                                                                                                                                                                                                                                                                                                                                                                     | **contactsLocationsModule.locations.&#91;115&#93;geoPoint.lon**: -111.94062                                                                                                                                                                                                                                                                                                                                         |
| 2026-06-24 14&#58;19&#58;40 | **contactsLocationsModule.locations.&#91;118&#93;geoPoint.lat**: 25.6604                                                                                                                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;118&#93;geoPoint.lat**: 25.66158                                                                                                                                                                                                                                                                                                                                           |
| 2026-06-24 14&#58;19&#58;40 | **contactsLocationsModule.locations.&#91;118&#93;geoPoint.lon**: -100.40651                                                                                                                                                                                                                                                                                                                                                                                                    | **contactsLocationsModule.locations.&#91;118&#93;geoPoint.lon**: -100.4034                                                                                                                                                                                                                                                                                                                                          |
