---
title: "NCT05702229 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | After                                                                                                                                                                                                                                                                                                                                                                                                            |
|:----------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-03-19 02&#58;24&#58;59 | **statusModule.statusVerifiedDate**: 2025-11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | **statusModule.primaryCompletionDateStruct.date**: 2026-07-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | **statusModule.primaryCompletionDateStruct.date**: 2027-11-30                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-19 02&#58;24&#58;59 | **statusModule.completionDateStruct.date**: 2027-09-28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.completionDateStruct.date**: 2029-05-31                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | **statusModule.lastUpdateSubmitDate**: 2025-11-14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | **statusModule.lastUpdateSubmitDate**: 2026-03-16                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | **statusModule.lastUpdatePostDateStruct.date**: 2025-11-17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-18                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | **descriptionModule.detailedDescription**: Approximately 240 participants will be assigned across 6 substudies, with approximately 40 evaluable participants of the confirmed recommend dose by SRC for study intervention in each corresponding substudy.                                                                                                                                                                                                                                                                                                          | **descriptionModule.detailedDescription**: Approximately 360 participants will be assigned across 4 substudies, with approximately 60 evaluable participants of the conﬁrmed recommend dose by SRC for study intervention in each corresponding substudy/cohort.                                                                                                                                                 |
| 2026-03-19 02&#58;24&#58;59 | **designModule.enrollmentInfo.count**: 240                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | **designModule.enrollmentInfo.count**: 163                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.armGroups.&#91;3&#93;label**: Substudy 4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | **armsInterventionsModule.armGroups.&#91;3&#93;label**: Substudy 4, Cohort 4a1                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.armGroups.&#91;3&#93;description**: AZD0901 plus rilvegostomig and 5-fluorouracil or capecitabine                                                                                                                                                                                                                                                                                                                                                                                                                                         | **armsInterventionsModule.armGroups.&#91;3&#93;description**: Sonesitatug vedotin (AZD0901) plus rilvegostomig and 5-fluorouracil or capecitabine                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.armGroups.&#91;5&#93;label**: Substudy 6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | **armsInterventionsModule.armGroups.&#91;5&#93;label**: Substudy 4, Cohort 4a2                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.armGroups.&#91;5&#93;description**: AZD0901 plus AZD7789 and 5-fluorouracil or capecitabine                                                                                                                                                                                                                                                                                                                                                                                                                                               | **armsInterventionsModule.armGroups.&#91;5&#93;description**: Sonesitatug vedotin (AZD0901) plus rilvegostomig and 5-fluorouracil                                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.armGroups.&#91;4&#93;label**: Substudy 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | **armsInterventionsModule.armGroups.&#91;4&#93;label**: Substudy 4, Cohort 4b                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.armGroups.&#91;4&#93;description**: AZD7789 plus XELOX (oxaliplatin and capecitabine) or FOLFOX (oxaliplatin and 5-FU/CF)                                                                                                                                                                                                                                                                                                                                                                                                                 | **armsInterventionsModule.armGroups.&#91;4&#93;description**: Sonesitatug vedotin (AZD0901) plus capecitabine                                                                                                                                                                                                                                                                                                    |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                  |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * 18 years or older at the time of signing the ICF.                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Body weight &#92;&gt; 35 kg.                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Previously untreated for unresectable or metastatic gastric or gastroesophageal junction adenocarcinoma.                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Has measurable target disease assessed by the Investigator based on RECIST 1.1.                                                                                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * ECOG PS zero or one.                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Life expectancy of at least 12 weeks.                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Adequate organ and bone marrow function.                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Has central lab confirmed Claudin18.2 status at screening from archival tumour collected within past 24 months or from a fresh biopsy when Substudy 3, Substudy 4 or Substudy 6 is open for recruitment.                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Participants with HER2-positive (3+ by IHC, or 2+ by IHC and positive by in situhybridisation) or indeterminate gastric or GEJ carcinoma.                                                                                                                                                                                                                                                                      |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Untreated or progressive CNS metastatic disease, any leptomeningeal disease, or cord compression.                                                                                                                                                                                                                                                                                                              |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Participants with ascites which cannot be controlled with appropriate interventions.                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Active infectious diseases, including tuberculosis, HIV infection, or hepatitis A/B/C.                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Uncontrolled intercurrent illness.                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Active or prior documented autoimmune or inflammatory disorders requiring systemic treatment with steroids or other immunosuppressive treatment.                                                                                                                                                                                                                                                               |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * History of another primary malignancy.                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Previous treatment with an immune-oncology agent.                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Previous treatment with any modalities of Claudin18.2 target therapy or MMAE exposure (when Substudy 3, Substudy 4, or Substudy 6 is open for recruitment).&#96; to &#96;Inclusion Criteria&#58;                                                                                                                                                                                                               |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * 18 years or older at the time of signing the ICF.                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Body weight &#92;&gt; 35 kg.                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Previously untreated for unresectable or metastatic gastric or gastroesophageal junction adenocarcinoma.                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Has measurable target disease assessed by the Investigator based on RECIST 1.1.                                                                                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * ECOG PS zero or one.                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Life expectancy of at least 12 weeks.                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Adequate organ and bone marrow function.                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Has central lab conﬁrmed Claudin18.2 status at screening from archival tumour collected within past 24 months or from a fresh biopsy when Substudy 3, Substudy 4 i s open for recruitment.                                                                                                                                                                                                                     |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Participants with HER2-positive (3+ by IHC, or 2+ by IHC and positive by in situhybridisation) or indeterminate gastric or GEJ carcinoma.                                                                                                                                                                                                                                                                      |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Untreated or progressive CNS metastatic disease, any leptomeningeal disease, or cord compression.                                                                                                                                                                                                                                                                                                              |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Participants with ascites which cannot be controlled with appropriate interventions.                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Active infectious diseases, including tuberculosis, HIV infection, or hepatitis B/C.                                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Uncontrolled intercurrent illness.                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Active or prior documented autoimmune or inflammatory disorders requiring systemic treatment with steroids or other immunosuppressive treatment.                                                                                                                                                                                                                                                               |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * History of another primary malignancy.                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Previous treatment with an immune-oncology agent.                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-19 02&#58;24&#58;59 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | * Previous treatment with any modalities of Claudin18.2 target therapy or MMAE exposure (when Substudy 3, Substudy 4 is open for recruitment).&#96;                                                                                                                                                                                                                                                              |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.interventions.&#91;0&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Rilvegostomig&#x27;, &#x27;description&#x27;&#58; &#x27;an anti PD-1 and anti-TIGIT bispecific antibody; IV infusion&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 2&#x27;, &#x27;Substudy 4&#x27;&#93;&#125;                                                                                                                                                                                                         | **armsInterventionsModule.interventions.&#91;0&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Rilvegostomig&#x27;, &#x27;description&#x27;&#58; &#x27;an anti PD-1 and anti-TIGIT bispecific antibody; IV infusion&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 2&#x27;, &#x27;Substudy 4, Cohort 4a1&#x27;, &#x27;Substudy 4, Cohort 4a2&#x27;&#93;&#125;      |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.interventions.&#91;2&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;FOLFOX&#x27;, &#x27;description&#x27;&#58; &#x27;5-fluorouracil 400 mg/m&#92;&#92;^2 IV, oxaliplatin 85 mg/m&#92;&#92;^2, leucovorin 400 mg/m&#92;&#92;^2 (or levoleucovorin 200 mg/m&#92;&#92;^2 when locally preferred and available), day 1, 5-fluorouracil 1200 mg/m&#92;&#92;^2 IV 24 h day 1-2&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 1&#x27;, &#x27;Substudy 2&#x27;, &#x27;Substudy 5&#x27;&#93;&#125; | **armsInterventionsModule.interventions.&#91;2&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;FOLFOX&#x27;, &#x27;description&#x27;&#58; &#x27;5-fluorouracil oxaliplatin, leucovorin (levoleucovorin when locally preferred and available)&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 1&#x27;, &#x27;Substudy 2&#x27;&#93;&#125;                             |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.interventions.&#91;6&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;5-Fluorouracil&#x27;, &#x27;description&#x27;&#58; &#x27;5-FU, IV infusion, Q3W&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 3&#x27;, &#x27;Substudy 4&#x27;, &#x27;Substudy 6&#x27;&#93;&#125;                                                                                                                                                                                                                      | **armsInterventionsModule.interventions.&#91;6&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Capecitabine&#x27;, &#x27;description&#x27;&#58; &#x27;Oral take&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 3&#x27;, &#x27;Substudy 4, Cohort 4a1&#x27;, &#x27;Substudy 4, Cohort 4b&#x27;&#93;&#125;                                                           |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.armGroups.&#91;4&#93;interventionNames.&#91;1&#93;**: Drug&#58; XELOX                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | **armsInterventionsModule.armGroups.&#91;4&#93;interventionNames.&#91;1&#93;**: Drug&#58; Capecitabine                                                                                                                                                                                                                                                                                                           |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.interventions.&#91;5&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;AZD0901&#x27;, &#x27;description&#x27;&#58; &#x27;an anti Claudin18.2 ADC; IV infusion&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 3&#x27;, &#x27;Substudy 4&#x27;, &#x27;Substudy 6&#x27;&#93;&#125;                                                                                                                                                                                                               | **armsInterventionsModule.interventions.&#91;5&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;5-Fluorouracil&#x27;, &#x27;description&#x27;&#58; &#x27;5-FU, IV infusion&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 3&#x27;, &#x27;Substudy 4, Cohort 4a1&#x27;, &#x27;Substudy 4, Cohort 4a2&#x27;&#93;&#125;                                                |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.armGroups.&#91;5&#93;interventionNames.&#91;0&#93;**: Drug&#58; AZD7789                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | **armsInterventionsModule.armGroups.&#91;5&#93;interventionNames.&#91;0&#93;**: Drug&#58; Rilvegostomig                                                                                                                                                                                                                                                                                                          |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.armGroups.&#91;4&#93;interventionNames.&#91;0&#93;**: Drug&#58; FOLFOX                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | **armsInterventionsModule.armGroups.&#91;4&#93;interventionNames.&#91;0&#93;**: Drug&#58; AZD0901                                                                                                                                                                                                                                                                                                                |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.interventions.&#91;4&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;AZD7789&#x27;, &#x27;description&#x27;&#58; &#x27;an anti PD 1 and anti TIM 3 bispecific antibody; IV infusion&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 5&#x27;, &#x27;Substudy 6&#x27;&#93;&#125;                                                                                                                                                                                                               | **armsInterventionsModule.interventions.&#91;4&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;AZD0901&#x27;, &#x27;description&#x27;&#58; &#x27;an anti Claudin18.2 ADC; IV infusion&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 3&#x27;, &#x27;Substudy 4, Cohort 4a1&#x27;, &#x27;Substudy 4, Cohort 4a2&#x27;, &#x27;Substudy 4, Cohort 4b&#x27;&#93;&#125; |
| 2026-03-19 02&#58;24&#58;59 | **armsInterventionsModule.interventions.&#91;3&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;XELOX&#x27;, &#x27;description&#x27;&#58; &#x27;capecitabine 1000 mg/m&#92;&#92;^2 BID, days 1 to 14, oxaliplatin 130 mg/m&#92;&#92;^2, day 1&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 1&#x27;, &#x27;Substudy 2&#x27;, &#x27;Substudy 5&#x27;&#93;&#125;                                                                                                                                                        | **armsInterventionsModule.interventions.&#91;3&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;XELOX&#x27;, &#x27;description&#x27;&#58; &#x27;capecitabine and oxaliplatin&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Substudy 1&#x27;, &#x27;Substudy 2&#x27;&#93;&#125;                                                                                              |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | **statusModule.statusVerifiedDate**: 2026-05                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2026-03-16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | **statusModule.lastUpdateSubmitDate**: 2026-05-13                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-14                                                                                                                                                                                                                                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;39&#93;city**: Taoyuan District                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;39&#93;city**: Taoyuan                                                                                                                                                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lat**: 24.9896                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lat**: 24.99368                                                                                                                                                                                                                                                                                                                                         |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lon**: 121.3187                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lon**: 121.29696                                                                                                                                                                                                                                                                                                                                        |
