---
title: "NCT05665595 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|:----------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-19 01&#58;00&#58;02 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | Minor formatting updates.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-18 02&#58;24&#58;04 | **referencesModule.references.&#91;0&#93;citation**: Dummer R, Guo J, Luke JJ, Carlino MS, Schadendorf D, Khattak MA, Hauschild A, Ascierto PA, Chen Y, Shin SJ, Rutkowski P, Luo Z, Chen J, Rivalland G, Coetzee C, Ribas A, Mujika K, Markel G, Villarroel RU, Dizdar O, Caglevic C, Grebennik D, Donovan K, Krepler C, Long GV. Vibostolimab coformulated with pembrolizumab versus pembrolizumab alone as adjuvant therapy for high-risk stage IIB-IV melanoma (KEYVIBE-010)&#58; a randomised, double-blind, phase 3 study. Lancet Oncol. 2026 Feb 13&#58;S1470-2045(25)00709-0. doi&#58; 10.1016/S1470-2045(25)00709-0. Online ahead of print. | **referencesModule.references.&#91;0&#93;citation**: Dummer R, Guo J, Luke JJ, Carlino MS, Schadendorf D, Khattak MA, Hauschild A, Ascierto PA, Chen Y, Shin SJ, Rutkowski P, Luo Z, Chen J, Rivalland G, Coetzee C, Ribas A, Mujika K, Markel G, Villarroel RU, Dizdar O, Caglevic C, Grebennik D, Donovan K, Krepler C, Long GV. Vibostolimab coformulated with pembrolizumab versus pembrolizumab alone as adjuvant therapy for high-risk stage IIB-IV melanoma (KEYVIBE-010)&#58; a randomised, double-blind, phase 3 study. Lancet Oncol. 2026 Mar;27(3)&#58;327-339. doi&#58; 10.1016/S1470-2045(25)00709-0. Epub 2026 Feb 13. |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;142&#93;city**: Napoli                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | **contactsLocationsModule.locations.&#91;142&#93;city**: Naples                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;142&#93;geoPoint.lat**: 40.87618                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;142&#93;geoPoint.lat**: 40.85216                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;142&#93;geoPoint.lon**: 14.5195                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;142&#93;geoPoint.lon**: 14.26811                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;51&#93;state**: Vienna                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | **contactsLocationsModule.locations.&#91;51&#93;state**: State of Vienna                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;73&#93;state**: Región de Valparaíso                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | **contactsLocationsModule.locations.&#91;73&#93;state**: Valparaiso                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;99&#93;city**: Ibagué                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;99&#93;city**: Ibague                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
