---
title: "NCT04465643 Change History"
---

| Timestamp                   | Before                                                                                                                                                                  | After                                                                                                                                                                                                        |
|:----------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-05-30 03&#58;31&#58;20 | **statusModule.statusVerifiedDate**: 2025-10                                                                                                                            | **statusModule.statusVerifiedDate**: 2026-05                                                                                                                                                                 |
| 2026-05-30 03&#58;31&#58;20 | **statusModule.lastUpdateSubmitDate**: 2025-10-02                                                                                                                       | **statusModule.lastUpdateSubmitDate**: 2026-05-27                                                                                                                                                            |
| 2026-05-30 03&#58;31&#58;20 | **statusModule.lastUpdatePostDateStruct.date**: 2025-10-08                                                                                                              | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-29                                                                                                                                                   |
| 2026-05-30 03&#58;31&#58;20 | **outcomesModule.primaryOutcomes.&#91;3&#93;measure**: Feasibility of combination nivolumab and ipilimumab as assessed by number of participants who achieve a response | **outcomesModule.primaryOutcomes.&#91;3&#93;measure**: Feasibility of combination nivolumab and ipilimumab as assessed by number of participants who start standard of care within standard treatment window |
| 2026-05-30 03&#58;31&#58;20 | **outcomesModule.primaryOutcomes.&#91;3&#93;description**: Number of participants who achieve a response (improved progression free survival).                          | **outcomesModule.primaryOutcomes.&#91;3&#93;description**: Number of participants who start standard of care treatment within 8 week                                                                         |
| 2026-05-30 03&#58;31&#58;20 | **outcomesModule.primaryOutcomes.&#91;3&#93;timeFrame**: Up to 2 years                                                                                                  | **outcomesModule.primaryOutcomes.&#91;3&#93;timeFrame**: Up to 8 weeks                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;04 | **statusModule.statusVerifiedDate**: 2026-05                                                                                                                            | **statusModule.statusVerifiedDate**: 2026-07                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;04 | **statusModule.lastUpdateSubmitDate**: 2026-05-27                                                                                                                       | **statusModule.lastUpdateSubmitDate**: 2026-07-09                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;04 | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-29                                                                                                              | **statusModule.lastUpdatePostDateStruct.date**: 2026-07-10                                                                                                                                                   |
