---
title: "NCT06692738 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                | After                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|:----------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-26 00&#58;55&#58;51 | **statusModule.statusVerifiedDate**: 2026-01                                                                                                                                                                                                                                                                                                                                                                                          | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-02-26 00&#58;55&#58;51 | **statusModule.lastUpdateSubmitDate**: 2026-01-20                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.lastUpdateSubmitDate**: 2026-02-24                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-02-26 00&#58;55&#58;51 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-21                                                                                                                                                                                                                                                                                                                                                                            | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-25                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-02-26 00&#58;55&#58;51 | **contactsLocationsModule.locations.&#91;54&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;54&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-02-26 00&#58;55&#58;51 | **contactsLocationsModule.locations.&#91;90&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;90&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-02-26 00&#58;55&#58;51 | **contactsLocationsModule.locations.&#91;156&#93;status**: SUSPENDED                                                                                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;156&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-26 00&#58;55&#58;51 | **contactsLocationsModule.locations.&#91;162&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;162&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-26 00&#58;55&#58;51 | **contactsLocationsModule.locations.&#91;190&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;190&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-02-26 00&#58;55&#58;51 | **contactsLocationsModule.locations.&#91;194&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                 | **contactsLocationsModule.locations.&#91;194&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-02-26 00&#58;55&#58;51 | **contactsLocationsModule.locations.&#91;195&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;195&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-02-26 00&#58;55&#58;51 | **contactsLocationsModule.locations.&#91;211&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;211&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-01 02&#58;42&#58;41 | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                                                                                          | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-04-01 02&#58;42&#58;41 | **statusModule.lastUpdateSubmitDate**: 2026-02-24                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.lastUpdateSubmitDate**: 2026-03-30                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-04-01 02&#58;42&#58;41 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-25                                                                                                                                                                                                                                                                                                                                                                            | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-31                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-04-01 02&#58;42&#58;41 | **contactsLocationsModule.locations.&#91;0&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;0&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-04-01 02&#58;42&#58;41 | **contactsLocationsModule.locations.&#91;49&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;49&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-04-01 02&#58;42&#58;41 | **contactsLocationsModule.locations.&#91;156&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;156&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-01 02&#58;42&#58;41 | **contactsLocationsModule.locations.&#91;227&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;227&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-01 02&#58;42&#58;41 | **contactsLocationsModule.locations.&#91;251&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;251&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-04-01 02&#58;42&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;274&#93;&#91;&#x27;zip&#x27;&#93;** (Added)                                                                                                                                                                                                                                                                                                                        |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;202&#93;city**: Padua                                                                                                                                                                                                                                                                                                                                                                        | **contactsLocationsModule.locations.&#91;202&#93;city**: Padova                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;202&#93;geoPoint.lat**: 45.40797                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;202&#93;geoPoint.lat**: 44.38225                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;202&#93;geoPoint.lon**: 11.88586                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;202&#93;geoPoint.lon**: 11.14261                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                                          | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.lastUpdateSubmitDate**: 2026-03-30                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.lastUpdateSubmitDate**: 2026-04-30                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-31                                                                                                                                                                                                                                                                                                                                                                            | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-01                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;4&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;4&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;130&#93;geoPoint.lat**: 22.8836                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;130&#93;geoPoint.lat**: 30.17415                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;130&#93;geoPoint.lon**: 107.264                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;130&#93;geoPoint.lon**: 120.97629                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;276&#93;city**: Taoyuan District                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;276&#93;city**: Taoyuan                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;276&#93;geoPoint.lat**: 24.9896                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;276&#93;geoPoint.lat**: 24.99368                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;276&#93;geoPoint.lon**: 121.3187                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;276&#93;geoPoint.lon**: 121.29696                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;279&#93;geoPoint.lat**: 13.7775                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;279&#93;geoPoint.lat**: 13.77706                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;279&#93;geoPoint.lon**: 100.51977                                                                                                                                                                                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;279&#93;geoPoint.lon**: 100.51958                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;282&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;282&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;283&#93;zip**: 07058                                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;283&#93;zip**: 07059                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-06-11 04&#58;04&#58;08 | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                                                                                          | **statusModule.statusVerifiedDate**: 2026-06                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-06-11 04&#58;04&#58;08 | **statusModule.lastUpdateSubmitDate**: 2026-04-30                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.lastUpdateSubmitDate**: 2026-06-09                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-06-11 04&#58;04&#58;08 | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-01                                                                                                                                                                                                                                                                                                                                                                            | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-10                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;23&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;23&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;50&#93;city**: Canton                                                                                                                                                                                                                                                                                                                                                                        | **contactsLocationsModule.locations.&#91;50&#93;city**: Fort Wayne                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;50&#93;state**: Ohio                                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;50&#93;state**: Indiana                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;50&#93;zip**: 44718                                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;50&#93;zip**: 46845                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;50&#93;geoPoint.lat**: 40.79895                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;50&#93;geoPoint.lat**: 41.1306                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;50&#93;geoPoint.lon**: -81.37845                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;50&#93;geoPoint.lon**: -85.12886                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;34&#93;city**: South Portland                                                                                                                                                                                                                                                                                                                                                                | **contactsLocationsModule.locations.&#91;34&#93;city**: Scarborough                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;34&#93;zip**: 04106                                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;34&#93;zip**: 04074                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lat**: 43.64147                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lat**: 43.57814                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lon**: -70.24088                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lon**: -70.32172                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;111&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;111&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;142&#93;status**: SUSPENDED                                                                                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;142&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;180&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;180&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-06-11 04&#58;04&#58;08 | **contactsLocationsModule.locations.&#91;220&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;220&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;06 | **identificationModule.briefTitle**: A Global Phase III Study of Rilvegostomig or Pembrolizumab Plus Chemotherapy for First-Line Treatment of Metastatic Squamous Non-small Cell Lung Cancer (NSCLC)                                                                                                                                                                                                                                  | **identificationModule.briefTitle**: A Global Phase III Study of Rilvegostomig or Pembrolizumab Plus Chemotherapy for First-Line Treatment of Locally Advanced or Metastatic Squamous Non-small Cell Lung Cancer (NSCLC)                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;06 | **identificationModule.officialTitle**: A Phase III, Randomized, Double-blind, Multicenter, Global Study of Rilvegostomig or Pembrolizumab in Combination With Platinum-based Chemotherapy for the First-line Treatment of Patients With Metastatic Squamous Non-small Cell Lung Cancer Whose Tumors Express PD-L1 (ARTEMIDE-Lung02)                                                                                                  | **identificationModule.officialTitle**: A Phase III, Randomized, Double-blind, Multicenter, Global Study of Rilvegostomig or Pembrolizumab in Combination With Platinum-based Chemotherapy for the First-line Treatment of Patients With Locally Advanced or Metastatic Squamous Non-small Cell Lung Cancer Whose Tumors Express PD-L1 (ARTEMIDE-Lung02)                                                                                                  |
| 2026-07-28 00&#58;26&#58;06 | **statusModule.statusVerifiedDate**: 2026-06                                                                                                                                                                                                                                                                                                                                                                                          | **statusModule.statusVerifiedDate**: 2026-07                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | **statusModule.primaryCompletionDateStruct.date**: 2029-02-05                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.primaryCompletionDateStruct.date**: 2030-07-01                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-07-28 00&#58;26&#58;06 | **statusModule.completionDateStruct.date**: 2029-10-08                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.completionDateStruct.date**: 2030-07-01                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **statusModule.lastUpdateSubmitDate**: 2026-06-09                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.lastUpdateSubmitDate**: 2026-07-13                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-10                                                                                                                                                                                                                                                                                                                                                                            | **statusModule.lastUpdatePostDateStruct.date**: 2026-07-14                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;06 | **descriptionModule.briefSummary**: The purpose of ARTEMIDE-Lung02 is to assess the efficacy and safety of rilvegostomig in combination with platinum-based chemotherapy for the first-line (1L) treatment of patients with metastatic squamous non-small cell lung cancer (mNSCLC) whose tumors express programmed death-ligand 1 (PD-L1).                                                                                           | **descriptionModule.briefSummary**: The purpose of ARTEMIDE-Lung02 is to assess the efficacy and safety of rilvegostomig in combination with platinum-based chemotherapy for the first-line (1L) treatment of patients with locally advanced or metastatic squamous non-small cell lung cancer (mNSCLC) whose tumors express programmed death-ligand 1 (PD-L1).                                                                                           |
| 2026-07-28 00&#58;26&#58;06 | **descriptionModule.detailedDescription**: This is a Phase III, two-arm, randomized, double-blind, global, multicenter study assessing the efficacy and safety of rilvegostomig compared to pembrolizumab, both in combination with platinum-based doublet chemotherapy, as a first-line (1L) treatment for patients with squamous metastatic non-small cell lung cancer (mNSCLC) whose tumors express PD-L1 (tumor cells (TC) ≥ 1%). | **descriptionModule.detailedDescription**: This is a Phase III, two-arm, randomized, double-blind, global, multicenter study assessing the efficacy and safety of rilvegostomig compared to pembrolizumab, both in combination with platinum-based doublet chemotherapy, as a first-line (1L) treatment for patients with squamous locally advanced or metastatic non-small cell lung cancer (mNSCLC) whose tumors express PD-L1 (tumor cells (TC) ≥ 1%). |
| 2026-07-28 00&#58;26&#58;06 | **designModule.enrollmentInfo.count**: 880                                                                                                                                                                                                                                                                                                                                                                                            | **designModule.enrollmentInfo.count**: 1160                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.primaryOutcomes.&#91;0&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                  | **outcomesModule.primaryOutcomes.&#91;0&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.primaryOutcomes.&#91;1&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                  | **outcomesModule.primaryOutcomes.&#91;1&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;0&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;0&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;1&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;1&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;2&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;2&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;3&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;3&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;4&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;4&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;5&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;5&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;6&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;6&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;7&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;7&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;8&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;8&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **outcomesModule.secondaryOutcomes.&#91;9&#93;timeFrame**: Up to approximately 5 years                                                                                                                                                                                                                                                                                                                                                | **outcomesModule.secondaryOutcomes.&#91;9&#93;timeFrame**: Up to approximately 6 years                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                           |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Histologically or cytologically documented squamous NSCLC.                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Stage IV mNSCLC (based on the American Joint Committee on Cancer Edition 8) not amenable to curative treatment.                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Absence of documented tumor genomic mutation results from tests conducted as part of standard local practice in any actionable driver oncogenes for which there are locally approved targeted 1L therapies.                                                                                                                                                                                                                                             |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Provision of acceptable tumor sample to confirm tumor PD-L1 expression TC ≥ 1%.                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * At least one lesion not previously irradiated that qualifies as a RECIST 1.1 TL at baseline and can be accurately measured at baseline as ≥ 10 mm in the longest diameter (except lymph nodes, which must have short axis ≥ 15 mm) with CT or MRI and is suitable for accurate repeated measurements.                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Adequate organ and bone marrow function.                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Presence of small cell and neuroendocrine histology components.                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Brain metastases unless asymptomatic, stable, and not requiring steroids or anticonvuls&#96; to &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Histologically or cytologically documented squamous NSCLC.                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Stage III B/C or IV mNSCLC (based on the American Joint Committee on Cancer Edition 8) not amenable to curative treatment.                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Absence of documented tumor genomic mutation results from tests conducted as part of standard local practice in any actionable driver oncogenes for which there are locally approved and available targeted 1L therapies.                                                                                                                                                                                                                               |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Provision of acceptable tumor sample to confirm tumor PD-L1 expression TC ≥ 1%.                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * At least one lesion not previously irradiated that qualifies as a RECIST 1.1 TL at baseline and can be accurately measured at baseline as ≥ 10 mm in the longest diameter (except lymph nodes, which must have short axis ≥ 15 mm) with CT or MRI and is suitable for accurate repeated measurements.                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Adequate organ and bone marrow function.                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Presence of small cell and neuroendocrine histology components.                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | * Brain metastases unless asymptomatic, stable, and not requirin&#96;                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;36&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;36&#93;status**: COMPLETED                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;40&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;40&#93;status**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;40&#93;city**: Duluth                                                                                                                                                                                                                                                                                                                                                                        | **contactsLocationsModule.locations.&#91;40&#93;city**: Saginaw                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;40&#93;state**: Minnesota                                                                                                                                                                                                                                                                                                                                                                    | **contactsLocationsModule.locations.&#91;40&#93;state**: Michigan                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;40&#93;zip**: 55802                                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;40&#93;zip**: 48602                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;40&#93;geoPoint.lat**: 46.78327                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;40&#93;geoPoint.lat**: 43.41947                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;40&#93;geoPoint.lon**: -92.10658                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;40&#93;geoPoint.lon**: -83.95081                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;41&#93;city**: Rochester                                                                                                                                                                                                                                                                                                                                                                     | **contactsLocationsModule.locations.&#91;41&#93;city**: Duluth                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;41&#93;zip**: 55905                                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;41&#93;zip**: 55802                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;41&#93;geoPoint.lat**: 44.02163                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;41&#93;geoPoint.lat**: 46.78327                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;41&#93;geoPoint.lon**: -92.4699                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;41&#93;geoPoint.lon**: -92.10658                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;42&#93;city**: Bridgeton                                                                                                                                                                                                                                                                                                                                                                     | **contactsLocationsModule.locations.&#91;42&#93;city**: Rochester                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;42&#93;state**: Missouri                                                                                                                                                                                                                                                                                                                                                                     | **contactsLocationsModule.locations.&#91;42&#93;state**: Minnesota                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;42&#93;zip**: 63044                                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;42&#93;zip**: 55905                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;42&#93;geoPoint.lat**: 38.767                                                                                                                                                                                                                                                                                                                                                                | **contactsLocationsModule.locations.&#91;42&#93;geoPoint.lat**: 44.02163                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;42&#93;geoPoint.lon**: -90.41151                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;42&#93;geoPoint.lon**: -92.4699                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;43&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                   | **contactsLocationsModule.locations.&#91;43&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;43&#93;city**: Columbia                                                                                                                                                                                                                                                                                                                                                                      | **contactsLocationsModule.locations.&#91;43&#93;city**: Bridgeton                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;43&#93;zip**: 65212                                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;43&#93;zip**: 63044                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lat**: 38.95171                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lat**: 38.767                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lon**: -92.33407                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lon**: -90.41151                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;44&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;44&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;44&#93;city**: Kansas City                                                                                                                                                                                                                                                                                                                                                                   | **contactsLocationsModule.locations.&#91;44&#93;city**: Columbia                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;44&#93;zip**: 64108                                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;44&#93;zip**: 65212                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;44&#93;geoPoint.lat**: 39.09973                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;44&#93;geoPoint.lat**: 38.95171                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;44&#93;geoPoint.lon**: -94.57857                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;44&#93;geoPoint.lon**: -92.33407                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;45&#93;city**: Lincoln                                                                                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;45&#93;city**: Kansas City                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;45&#93;state**: Nebraska                                                                                                                                                                                                                                                                                                                                                                     | **contactsLocationsModule.locations.&#91;45&#93;state**: Missouri                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;45&#93;zip**: 68506                                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;45&#93;zip**: 64108                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;45&#93;geoPoint.lat**: 40.8                                                                                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;45&#93;geoPoint.lat**: 39.09973                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;45&#93;geoPoint.lon**: -96.66696                                                                                                                                                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;45&#93;geoPoint.lon**: -94.57857                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;46&#93;city**: Camden                                                                                                                                                                                                                                                                                                                                                                        | **contactsLocationsModule.locations.&#91;46&#93;city**: Lincoln                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;46&#93;state**: New Jersey                                                                                                                                                                                                                                                                                                                                                                   | **contactsLocationsModule.locations.&#91;46&#93;state**: Nebraska                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;46&#93;zip**: 08103                                                                                                                                                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;46&#93;zip**: 68506                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;06 | **contactsLocationsModule.locations.&#91;46&#93;geoPoint.lat**: 39.92595                                                                                                                                                                                                                                                                                                                                                              | **contactsLocationsModule.locations.&#91;46&#93;geoPoint.lat**: 40.8                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-07-28 00&#58;26&#58;06 | -                                                                                                                                                                                                                                                                                                                                                                                                                                     | Field &#96;contactsLocationsModule.locations.&#91;46&#93;geoPoint.lon&#96; changed from &#96;-75.11962&#96; to &#96;-96.6                                                                                                                                                                                                                                                                                                                                 |
