---
title: "NCT06821503 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|:----------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-03-11 02&#58;05&#58;41 | **statusModule.statusVerifiedDate**: 2024-12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | **statusModule.statusVerifiedDate**: 2025-12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-11 02&#58;05&#58;41 | **statusModule.overallStatus**: NOT_YET_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **statusModule.overallStatus**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-11 02&#58;05&#58;41 | **statusModule.startDateStruct.date**: 2025-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **statusModule.startDateStruct.date**: 2025-04-11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-11 02&#58;05&#58;41 | **statusModule.startDateStruct.type**: ESTIMATED                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **statusModule.startDateStruct.type**: ACTUAL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-11 02&#58;05&#58;41 | **statusModule.lastUpdateSubmitDate**: 2025-02-13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **statusModule.lastUpdateSubmitDate**: 2026-03-06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-11 02&#58;05&#58;41 | **statusModule.lastUpdatePostDateStruct.date**: 2025-02-17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Age 18 or above.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * The Eastern Cooperative Oncology Group (ECOG) physical fitness status score is 0-1 points.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * There should be at least one measurable lesion.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * All acute toxic reactions caused by previous anti-tumor treatments or surgical procedures have been relieved to grade 0-1 or to the levels specified in the inclusion/exclusion criteria.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Have sufficient organ and bone marrow function                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Expected survival period ≥ 12 weeks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Infertility is defined as women who have reached menopause or have undergone bilateral oophorectomy with medical records. Male participants and female participants with fertility must agree to use one medically approved contraceptive measure during the trial period and within 6 months after the last administration of the trial drug or within 9 months after the last administration of chemotherapy drug (oxaliplatin) (whichever is later). The serum pregnancy test must be negative within 3 days before starting the study medication and not during lactation.                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * With my consent and signed informed consent form.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Patients diagnosed with Pancreatic ductal adenocarcinoma (PDAC) by pathology have evidence of advanced stage or metastasis that cannot be surgically removed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Have not received systematic treatment for unresectable locally advanced or metastatic PDAC in the past                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Known High-frequency microsatellite instability (MSI-H)/deficient mismatch repair (dMMR).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * There is uncontrolled or symptomatic active central nervous system metastasis, which can manifest as clinical symptoms, cerebral edema, spinal cord compression, cancerous meningitis, leptomeningeal disease, and/or progressive growth.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Within 14 days prior to enrollment, there were still uncontrollable pleural effusion and ascites despite treatment such as puncture and drainage; Pericardial effusion accompanied by clinical symptoms or moderate or above.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Within 14 days prior to enrollment, there is an unresolved biliary obstruction, or the clinical status has remained stable for less than 14 days after biliary stent implantation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Participants&#x27; weight has decreased by more than 20% or their body mass index (BMI) is less than 18 kg/m ² within the first 2 months of enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Received the following treatments or medications before enrollment&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 1. Prior to enrollment, received treatment with C-C chemokine Receptor 8 (CCR8) antibodies, cytotoxic T-lymphocyte associated protein-4 (CTLA-4) antibodies, or other drugs that act on Tregs.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 2. Having undergone major surgery within 28 days prior to enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 3. Used immunosuppressive drugs within 14 days prior to enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 4. Vaccination with attenuated live vaccine should be administered within 28 days prior to enrollment or planned within the study period and 60 days after completion of study drug treatment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 5. Received anti-tumor therapy (including chemotherapy, radiotherapy, immunotherapy, endocrine therapy, targeted therapy, biological therapy, or tumor embolization) within 28 days before enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Diagnosed with any other malignant tumor within the 5 years prior to enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * There are any active, known or suspected autoimmune diseases present.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Within the first 3 months of enrollment, there have been significant clinical bleeding symptoms or clear bleeding tendencies; Arterial/venous thrombotic events that occurred within the first 6 months of enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Significant vascular disease occurred within the first 6 months of enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Severe, unhealed, or cracked wounds, as well as active ulcers or untreated fractures.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * There is peripheral neuropathy of grade&#92;&gt;1 present.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Have experienced gastrointestinal perforation and/or gastrointestinal fistula within the 6 months prior to enrollment;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Within the 6 months prior to enrollment, there have been clinical signs or symptoms of intestinal obstruction and/or gastrointestinal obstruction.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Existence of interstitial lung disease, non infectious pneumonia, or uncontrolled systemic diseases.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Known to be allergic to the investigational drug or any of its excipients; Or have experienced severe allergic reactions to other monoclonal antibodies.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Human immunodeficiency virus (HIV) infection or known acquired immunodeficiency syndrome (AIDS), untreated active hepatitis or co infection with hepatitis B and hepatitis C.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Clinical symptoms or diseases of the heart that have not been well controlled&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Systemic use of antibiotics for at least 7 days within the 28 days prior to enrollment, or unexplained fever&#92;&gt;38.5 °C during screening/before first administration.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Known history of allogeneic organ transplantation or allogeneic hematopoietic stem cell transplantation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Have participated in any other drug clinical studies within 4 weeks prior to enrollment, or have not had more than 5 half lives since the last study medication.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Known history of abuse or drug use of psychotropic substances.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * There are other serious physical or mental illnesses or laboratory abnormalities that may increase the risk of participating in the study, or interfere with the study results, as well as patients who the researcher deems unsuitable to participate in this study.&#96; to &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Age 18 or above.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * The Eastern Cooperative Oncology Group (ECOG) physical fitness status score is 0-1 points.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * There should be at least one measurable lesion.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * All acute toxic reactions caused by previous anti-tumor treatments or surgical procedures have been relieved to grade 0-1 or to the levels specified in the inclusion/exclusion criteria.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Have sufficient organ and bone marrow function                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Expected survival period ≥ 12 weeks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Infertility is defined as women who have reached menopause or have undergone bilateral oophorectomy with medical records. Male participants and female participants with fertility must agree to use one medically approved contraceptive measure during the trial period and within 6 months after the last administration of the trial drug or within 9 months after the last administration of chemotherapy drug (oxaliplatin) (whichever is later). The serum pregnancy test must be negative within 3 days before starting the study medication and not during lactation.                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * With my consent and signed informed consent form.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Patients with a pathological diagnosis of pancreatic cancer (ductal adenocarcinoma or adenocarcinoma) have evidence of advanced or metastatic disease that is not resectable.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Previously received no systemic treatment for unresectable locally advanced or metastatic pancreatic cancer.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Known High-frequency microsatellite instability (MSI-H)/deficient mismatch repair (dMMR).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * There is uncontrolled or symptomatic active central nervous system metastasis, which can manifest as clinical symptoms, cerebral edema, spinal cord compression, cancerous meningitis, leptomeningeal disease, and/or progressive growth.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Within 14 days prior to enrollment, there were still uncontrollable pleural effusion and ascites despite treatment such as puncture and drainage; Pericardial effusion accompanied by clinical symptoms or moderate or above.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Within 14 days prior to enrollment, there is an unresolved biliary obstruction, or the clinical status has remained stable for less than 14 days after biliary stent implantation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Participants&#x27; weight has decreased by more than 20% or their body mass index (BMI) is less than 18 kg/m ² within the first 2 months of enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Received the following treatments or medications before enrollment&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 1. Prior to enrollment, received treatment with C-C chemokine Receptor 8 (CCR8) antibodies, cytotoxic T-lymphocyte associated protein-4 (CTLA-4) antibodies, or other drugs that act on Tregs.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 2. Having undergone major surgery within 28 days prior to enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 3. Used immunosuppressive drugs within 14 days prior to enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 4. Vaccination with attenuated live vaccine should be administered within 28 days prior to enrollment or planned within the study period and 60 days after completion of study drug treatment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 5. Received anti-tumor therapy (including chemotherapy, radiotherapy, immunotherapy, endocrine therapy, targeted therapy, biological therapy, or tumor embolization) within 28 days before enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Diagnosed with any other malignant tumor within the 5 years prior to enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * There are any active, known or suspected autoimmune diseases present.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Within the first 3 months of enrollment, there have been significant clinical bleeding symptoms or clear bleeding tendencies; Arterial/venous thrombotic events that occurred within the first 6 months of enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Significant vascular disease occurred within the first 6 months of enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Severe, unhealed, or cracked wounds, as well as active ulcers or untreated fractures.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * There is peripheral neuropathy of grade&#92;&gt;1 present.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Have experienced gastrointestinal perforation and/or gastrointestinal fistula within the 6 months prior to enrollment;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Within the 6 months prior to enrollment, there have been clinical signs or symptoms of intestinal obstruction and/or gastrointestinal obstruction.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Existence of interstitial lung disease, non infectious pneumonia, or uncontrolled systemic diseases.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Known to be allergic to the investigational drug or any of its excipients; Or have experienced severe allergic reactions to other monoclonal antibodies.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Human immunodeficiency virus (HIV) infection or known acquired immunodeficiency syndrome (AIDS), untreated active hepatitis or co infection with hepatitis B and hepatitis C.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Clinical symptoms or diseases of the heart that have not been well controlled&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Systemic use of antibiotics for at least 7 days within the 28 days prior to enrollment, or unexplained fever&#92;&gt;38.5 °C during screening/before first administration.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Known history of allogeneic organ transplantation or allogeneic hematopoietic stem cell transplantation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Have participated in any other drug clinical studies within 4 weeks prior to enrollment, or have not had more than 5 half lives since the last study medication.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * Known history of abuse or drug use of psychotropic substances.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-11 02&#58;05&#58;41 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | * There are other serious physical or mental illnesses or laboratory abnormalities that may increase the risk of participating in the study, or interfere with the study results, as well as patients who the researcher deems unsuitable to participate in this study.&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;15&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Tianjin Medical University Cancer Institute &amp; Hospital&#x27;, &#x27;city&#x27;&#58; &#x27;Tianjin&#x27;, &#x27;state&#x27;&#58; &#x27;Tianjin Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;300000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Jihui Hao, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;18622221120&#x27;, &#x27;email&#x27;&#58; &#x27;haojihui@tjmuch.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 39.14222, &#x27;lon&#x27;&#58; 117.17667&#125;&#125;                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;15&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Tianjin Medical University Cancer Institute &amp; Hospital&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Tianjin&#x27;, &#x27;state&#x27;&#58; &#x27;Tianjin Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;300000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Jihui Hao, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;18622221120&#x27;, &#x27;email&#x27;&#58; &#x27;haojihui@tjmuch.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 39.14222, &#x27;lon&#x27;&#58; 117.17667&#125;&#125;                                                                                                                                                                                                       |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;3&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Chongqing Qeneral Hospital&#x27;, &#x27;city&#x27;&#58; &#x27;Chongqing&#x27;, &#x27;state&#x27;&#58; &#x27;Chongqing Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;400013&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Huaizhi Wang, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13996950719&#x27;, &#x27;email&#x27;&#58; &#x27;whuaizhi@qq.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 29.56026, &#x27;lon&#x27;&#58; 106.55771&#125;&#125;                                                                                                                                                                                                                                     | **contactsLocationsModule.locations.&#91;3&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Chongqing Qeneral Hospital&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Chongqing&#x27;, &#x27;state&#x27;&#58; &#x27;Chongqing Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;400013&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Huaizhi Wang, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13996950719&#x27;, &#x27;email&#x27;&#58; &#x27;whuaizhi@qq.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 29.56026, &#x27;lon&#x27;&#58; 106.55771&#125;&#125;                                                                                                                                                                                                                                     |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;6&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Huazhong University of Science and Technology Tongji Medical College of Huazhong University of Science and Technology&#x27;, &#x27;city&#x27;&#58; &#x27;Wuhan&#x27;, &#x27;state&#x27;&#58; &#x27;Hubei&#x27;, &#x27;zip&#x27;&#58; &#x27;430000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Jun Xue, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;15071258754&#x27;, &#x27;email&#x27;&#58; &#x27;xjunion@126.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 30.58333, &#x27;lon&#x27;&#58; 114.26667&#125;&#125;                                                                                                                                                                    | **contactsLocationsModule.locations.&#91;6&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Huazhong University of Science and Technology Tongji Medical College of Huazhong University of Science and Technology&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Wuhan&#x27;, &#x27;state&#x27;&#58; &#x27;Hubei&#x27;, &#x27;zip&#x27;&#58; &#x27;430000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Jun Xue, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;15071258754&#x27;, &#x27;email&#x27;&#58; &#x27;xjunion@126.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 30.58333, &#x27;lon&#x27;&#58; 114.26667&#125;&#125;                                                                                                                                                                    |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;8&#93;**: &#123;&#x27;facility&#x27;&#58; &quot;Jiangsu Provincial People&#x27;s Hospital&quot;, &#x27;city&#x27;&#58; &#x27;Nanjing&#x27;, &#x27;state&#x27;&#58; &#x27;Jiangsu&#x27;, &#x27;zip&#x27;&#58; &#x27;210000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Kuirong Jiang, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;15312995688&#x27;, &#x27;email&#x27;&#58; &#x27;jiangkuirong@163.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 32.06167, &#x27;lon&#x27;&#58; 118.77778&#125;&#125;                                                                                                                                                                                                                                 | **contactsLocationsModule.locations.&#91;8&#93;**: &#123;&#x27;facility&#x27;&#58; &quot;Jiangsu Provincial People&#x27;s Hospital&quot;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Nanjing&#x27;, &#x27;state&#x27;&#58; &#x27;Jiangsu&#x27;, &#x27;zip&#x27;&#58; &#x27;210000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Kuirong Jiang, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;15312995688&#x27;, &#x27;email&#x27;&#58; &#x27;jiangkuirong@163.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 32.06167, &#x27;lon&#x27;&#58; 118.77778&#125;&#125;                                                                                                                                                                                                                                 |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;2&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Beijing Cancer Hospital&#x27;, &#x27;city&#x27;&#58; &#x27;Beijing&#x27;, &#x27;state&#x27;&#58; &#x27;Beijing Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;100142&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Lin Shen, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;010-88196561&#x27;, &#x27;email&#x27;&#58; &#x27;doctorshenlin@sina.cn&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 39.9075, &#x27;lon&#x27;&#58; 116.39723&#125;&#125;                                                                                                                                                                                                                                          | **contactsLocationsModule.locations.&#91;2&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Beijing Cancer Hospital&#x27;, &#x27;status&#x27;&#58; &#x27;RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Beijing&#x27;, &#x27;state&#x27;&#58; &#x27;Beijing Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;100142&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Lin Shen, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;010-88196561&#x27;, &#x27;email&#x27;&#58; &#x27;doctorshenlin@sina.cn&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 39.9075, &#x27;lon&#x27;&#58; 116.39723&#125;&#125;                                                                                                                                                                                                                                                  |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;4&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Harbin Medical University Cancer Hospital&#x27;, &#x27;city&#x27;&#58; &#x27;Harbin&#x27;, &#x27;state&#x27;&#58; &#x27;Heilongjiang&#x27;, &#x27;zip&#x27;&#58; &#x27;150081&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Zhiwei Li, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;15004683651&#x27;, &#x27;email&#x27;&#58; &#x27;lzhw0451@163.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 45.75, &#x27;lon&#x27;&#58; 126.65&#125;&#125;                                                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;4&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Harbin Medical University Cancer Hospital&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Harbin&#x27;, &#x27;state&#x27;&#58; &#x27;Heilongjiang&#x27;, &#x27;zip&#x27;&#58; &#x27;150081&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Zhiwei Li, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;15004683651&#x27;, &#x27;email&#x27;&#58; &#x27;lzhw0451@163.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 45.75, &#x27;lon&#x27;&#58; 126.65&#125;&#125;                                                                                                                                                                                                                                           |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;12&#93;**: &#123;&#x27;facility&#x27;&#58; &quot;The First Affiliated Hospital of Xi&#x27;an Jiaotong University Medical College&quot;, &#x27;city&#x27;&#58; &quot;Xi&#x27;an&quot;, &#x27;state&#x27;&#58; &#x27;Shaanxi&#x27;, &#x27;zip&#x27;&#58; &#x27;710000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Zheng Wu, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13609195898&#x27;, &#x27;email&#x27;&#58; &#x27;woozheng@xjtu.edu.cn&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.25833, &#x27;lon&#x27;&#58; 108.92861&#125;&#125;                                                                                                                                                                                            | **contactsLocationsModule.locations.&#91;12&#93;**: &#123;&#x27;facility&#x27;&#58; &quot;The First Affiliated Hospital of Xi&#x27;an Jiaotong University Medical College&quot;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &quot;Xi&#x27;an&quot;, &#x27;state&#x27;&#58; &#x27;Shaanxi&#x27;, &#x27;zip&#x27;&#58; &#x27;710000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Zheng Wu, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13609195898&#x27;, &#x27;email&#x27;&#58; &#x27;woozheng@xjtu.edu.cn&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.25833, &#x27;lon&#x27;&#58; 108.92861&#125;&#125;                                                                                                                                                                                            |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;14&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Tianjin Cancer Hospital Airport Hospital&#x27;, &#x27;city&#x27;&#58; &#x27;Tianjin&#x27;, &#x27;state&#x27;&#58; &#x27;Tianjin Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;300000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Huikai Li, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;18622228639&#x27;, &#x27;email&#x27;&#58; &#x27;tjchlhk@126.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 39.14222, &#x27;lon&#x27;&#58; 117.17667&#125;&#125;                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;14&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Tianjin Cancer Hospital Airport Hospital&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Tianjin&#x27;, &#x27;state&#x27;&#58; &#x27;Tianjin Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;300000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Huikai Li, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;18622228639&#x27;, &#x27;email&#x27;&#58; &#x27;tjchlhk@126.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 39.14222, &#x27;lon&#x27;&#58; 117.17667&#125;&#125;                                                                                                                                                                                                                             |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;13&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;The First Affiliated Hospital of Naval Medical University&#x27;, &#x27;city&#x27;&#58; &#x27;Shanghai&#x27;, &#x27;state&#x27;&#58; &#x27;Shanghai Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;200336&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Gang Jin, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13601635681&#x27;, &#x27;email&#x27;&#58; &#x27;Jigang@sohu.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 31.22222, &#x27;lon&#x27;&#58; 121.45806&#125;&#125;                                                                                                                                                                                                           | **contactsLocationsModule.locations.&#91;13&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;The First Affiliated Hospital of Naval Medical University&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Shanghai&#x27;, &#x27;state&#x27;&#58; &#x27;Shanghai Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;200336&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Gang Jin, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13601635681&#x27;, &#x27;email&#x27;&#58; &#x27;Jigang@sohu.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 31.22222, &#x27;lon&#x27;&#58; 121.45806&#125;&#125;                                                                                                                                                                                                           |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;9&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;The First Affiliated Hospital of Nanchang University&#x27;, &#x27;city&#x27;&#58; &#x27;Nanchang&#x27;, &#x27;state&#x27;&#58; &#x27;Jiangxi&#x27;, &#x27;zip&#x27;&#58; &#x27;330006&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Yong Li, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;15879155066&#x27;, &#x27;email&#x27;&#58; &#x27;liyong1553@163.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 28.68396, &#x27;lon&#x27;&#58; 115.85306&#125;&#125;                                                                                                                                                                                                                             | **contactsLocationsModule.locations.&#91;9&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;The First Affiliated Hospital of Nanchang University&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Nanchang&#x27;, &#x27;state&#x27;&#58; &#x27;Jiangxi&#x27;, &#x27;zip&#x27;&#58; &#x27;330006&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Yong Li, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;15879155066&#x27;, &#x27;email&#x27;&#58; &#x27;liyong1553@163.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 28.68396, &#x27;lon&#x27;&#58; 115.85306&#125;&#125;                                                                                                                                                                                                                             |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;5&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;The First Affiliated Hospital of Zhengzhou University&#x27;, &#x27;city&#x27;&#58; &#x27;Zhengzhou&#x27;, &#x27;state&#x27;&#58; &#x27;Henan&#x27;, &#x27;zip&#x27;&#58; &#x27;450000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Feng Wang, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13938244776&#x27;, &#x27;email&#x27;&#58; &#x27;fengw010@163.com&#x27;&#125;, &#123;&#x27;name&#x27;&#58; &#x27;Aili Suo Suo, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;18991232561&#x27;, &#x27;email&#x27;&#58; &#x27;Ailisuo@mail.xjtu.edu.cn&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.75778, &#x27;lon&#x27;&#58; 113.64861&#125;&#125; | **contactsLocationsModule.locations.&#91;5&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;The First Affiliated Hospital of Zhengzhou University&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Zhengzhou&#x27;, &#x27;state&#x27;&#58; &#x27;Henan&#x27;, &#x27;zip&#x27;&#58; &#x27;450000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Feng Wang, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13938244776&#x27;, &#x27;email&#x27;&#58; &#x27;fengw010@163.com&#x27;&#125;, &#123;&#x27;name&#x27;&#58; &#x27;Aili Suo Suo, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;18991232561&#x27;, &#x27;email&#x27;&#58; &#x27;Ailisuo@mail.xjtu.edu.cn&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.75778, &#x27;lon&#x27;&#58; 113.64861&#125;&#125; |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;7&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Jiangsu Cancer Hospital&#x27;, &#x27;city&#x27;&#58; &#x27;Nanjing&#x27;, &#x27;state&#x27;&#58; &#x27;Jiangsu&#x27;, &#x27;zip&#x27;&#58; &#x27;210000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Xiaofeng Sun, Master&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13505156959&#x27;, &#x27;email&#x27;&#58; &#x27;jssxfgcp@163.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 32.06167, &#x27;lon&#x27;&#58; 118.77778&#125;&#125;                                                                                                                                                                                                                                                        | **contactsLocationsModule.locations.&#91;7&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Jiangsu Cancer Hospital&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Nanjing&#x27;, &#x27;state&#x27;&#58; &#x27;Jiangsu&#x27;, &#x27;zip&#x27;&#58; &#x27;210000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Xiaofeng Sun, Master&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13505156959&#x27;, &#x27;email&#x27;&#58; &#x27;jssxfgcp@163.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 32.06167, &#x27;lon&#x27;&#58; 118.77778&#125;&#125;                                                                                                                                                                                                                                                        |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;10&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;The First Affiliated Hospital of China Medical University&#x27;, &#x27;city&#x27;&#58; &#x27;Shenyang&#x27;, &#x27;state&#x27;&#58; &#x27;Liaoning&#x27;, &#x27;zip&#x27;&#58; &#x27;110000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Xiujuan Qu, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13604031355&#x27;, &#x27;email&#x27;&#58; &#x27;qu_xiujuan@hotmail.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.79222, &#x27;lon&#x27;&#58; 123.43278&#125;&#125;                                                                                                                                                                                                               | **contactsLocationsModule.locations.&#91;10&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;The First Affiliated Hospital of China Medical University&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Shenyang&#x27;, &#x27;state&#x27;&#58; &#x27;Liaoning&#x27;, &#x27;zip&#x27;&#58; &#x27;110000&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Xiujuan Qu, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13604031355&#x27;, &#x27;email&#x27;&#58; &#x27;qu_xiujuan@hotmail.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.79222, &#x27;lon&#x27;&#58; 123.43278&#125;&#125;                                                                                                                                                                                                               |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;1&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Cancer Hospital Chinese Academy of Medical Science&#x27;, &#x27;city&#x27;&#58; &#x27;Beijing&#x27;, &#x27;state&#x27;&#58; &#x27;Beijing Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;100021&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Yongkun Sun, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13141276041&#x27;, &#x27;email&#x27;&#58; &#x27;hsunyk@126.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 39.9075, &#x27;lon&#x27;&#58; 116.39723&#125;&#125;                                                                                                                                                                                                                    | **contactsLocationsModule.locations.&#91;1&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Cancer Hospital Chinese Academy of Medical Science&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Beijing&#x27;, &#x27;state&#x27;&#58; &#x27;Beijing Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;100021&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Yongkun Sun, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13141276041&#x27;, &#x27;email&#x27;&#58; &#x27;hsunyk@126.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 39.9075, &#x27;lon&#x27;&#58; 116.39723&#125;&#125;                                                                                                                                                                                                                    |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;11&#93;**: &#123;&#x27;facility&#x27;&#58; &quot;The Sixth People&#x27;s Hospital of Shenyang&quot;, &#x27;city&#x27;&#58; &#x27;Shenyang&#x27;, &#x27;state&#x27;&#58; &#x27;Liaoning&#x27;, &#x27;zip&#x27;&#58; &#x27;110002&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Jin Xu, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13236666950&#x27;, &#x27;email&#x27;&#58; &#x27;xvjin2024@sina.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.79222, &#x27;lon&#x27;&#58; 123.43278&#125;&#125;                                                                                                                                                                                                                                    | **contactsLocationsModule.locations.&#91;11&#93;**: &#123;&#x27;facility&#x27;&#58; &quot;The Sixth People&#x27;s Hospital of Shenyang&quot;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Shenyang&#x27;, &#x27;state&#x27;&#58; &#x27;Liaoning&#x27;, &#x27;zip&#x27;&#58; &#x27;110002&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Jin Xu, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13236666950&#x27;, &#x27;email&#x27;&#58; &#x27;xvjin2024@sina.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.79222, &#x27;lon&#x27;&#58; 123.43278&#125;&#125;                                                                                                                                                                                                                                    |
| 2026-03-11 02&#58;05&#58;41 | **contactsLocationsModule.locations.&#91;0&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Peking Union Medical College Hospital&#x27;, &#x27;city&#x27;&#58; &#x27;Beijing&#x27;, &#x27;state&#x27;&#58; &#x27;Beijing Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;100005&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Xicheng Wang, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13439563949&#x27;, &#x27;email&#x27;&#58; &#x27;xicheng_wang@hotmail.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 39.9075, &#x27;lon&#x27;&#58; 116.39723&#125;&#125;                                                                                                                                                                                                                      | **contactsLocationsModule.locations.&#91;0&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Peking Union Medical College Hospital&#x27;, &#x27;status&#x27;&#58; &#x27;NOT_YET_RECRUITING&#x27;, &#x27;city&#x27;&#58; &#x27;Beijing&#x27;, &#x27;state&#x27;&#58; &#x27;Beijing Municipality&#x27;, &#x27;zip&#x27;&#58; &#x27;100005&#x27;, &#x27;country&#x27;&#58; &#x27;China&#x27;, &#x27;contacts&#x27;&#58; &#91;&#123;&#x27;name&#x27;&#58; &#x27;Xicheng Wang, Doctor&#x27;, &#x27;role&#x27;&#58; &#x27;CONTACT&#x27;, &#x27;phone&#x27;&#58; &#x27;13439563949&#x27;, &#x27;email&#x27;&#58; &#x27;xicheng_wang@hotmail.com&#x27;&#125;&#93;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 39.9075, &#x27;lon&#x27;&#58; 116.39723&#125;&#125;                                                                                                                                                                                                                      |
