---
title: "NCT04543617 Change History"
---

| Timestamp                   | Before                                                                          | After                                                                                                       |
|:----------------------------|:--------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------|
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;76&#93;city**: Napoli                  | **contactsLocationsModule.locations.&#91;76&#93;city**: Naples                                              |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;76&#93;geoPoint.lat**: 40.87618        | **contactsLocationsModule.locations.&#91;76&#93;geoPoint.lat**: 40.85216                                    |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;76&#93;geoPoint.lon**: 14.5195         | **contactsLocationsModule.locations.&#91;76&#93;geoPoint.lon**: 14.26811                                    |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;79&#93;city**: Padua                   | **contactsLocationsModule.locations.&#91;79&#93;city**: Padova                                              |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;79&#93;geoPoint.lat**: 45.40797        | **contactsLocationsModule.locations.&#91;79&#93;geoPoint.lat**: 45.26618                                    |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;79&#93;geoPoint.lon**: 11.88586        | **contactsLocationsModule.locations.&#91;79&#93;geoPoint.lon**: 11.77208                                    |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.statusVerifiedDate**: 2026-01                                    | **statusModule.statusVerifiedDate**: 2026-04                                                                |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.lastUpdateSubmitDate**: 2026-01-16                               | **statusModule.lastUpdateSubmitDate**: 2026-04-16                                                           |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-20                      | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-17                                                  |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;164&#93;facility**: New Cross Hospital | **contactsLocationsModule.locations.&#91;164&#93;facility**: Goztepe Prof.Dr. Suleyman Yalcin City Hospital |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;164&#93;city**: Wolverhampton          | **contactsLocationsModule.locations.&#91;164&#93;city**: Kadiköy                                            |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;164&#93;zip**: WV10 0QP                | **contactsLocationsModule.locations.&#91;164&#93;zip**: 34722                                               |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;164&#93;country**: United Kingdom      | **contactsLocationsModule.locations.&#91;164&#93;country**: Turkey (Türkiye)                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;164&#93;geoPoint.lat**: 52.58547       | **contactsLocationsModule.locations.&#91;164&#93;geoPoint.lat**: 41.06639                                   |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;164&#93;geoPoint.lon**: -2.12296       | **contactsLocationsModule.locations.&#91;164&#93;geoPoint.lon**: 41.01294                                   |
