---
title: "NCT06790706 Change History"
---

| Timestamp                   | Before                                                                                                                                   | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|:----------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-07-28 00&#58;26&#58;05 | **statusModule.statusVerifiedDate**: 2025-10                                                                                             | **statusModule.statusVerifiedDate**: 2026-06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.overallStatus**: RECRUITING                                                                                               | **statusModule.overallStatus**: ACTIVE_NOT_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.lastUpdateSubmitDate**: 2025-10-01                                                                                        | **statusModule.lastUpdateSubmitDate**: 2026-06-22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.lastUpdatePostDateStruct.date**: 2025-10-06                                                                               | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | Field &#96;descriptionModule.briefSummary&#96; changed from &#96;Immune checkpoint inhibitors (ICI) have revolutionized the management of advanced cancers. However, most rare cancers have been excluded from this progress due to the lack of clinical trials involving these diseases. After the standard first-line treatment, there are no other validated treatments for most of them. The management of these patients in ≥ 2nd line treatment relies on historic poorly effective regimens.                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | This creates an inequity between patients with frequent cancers beneficiating from medical progresses and approvals of innovative drugs, and patients with rare cancers are still treated with old and toxic drugs.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | Few available data on case reports and early phase studies indicate a beneficial role of the immunotherapy in rare cancers.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | The investigators assume that the combination of Domvanalimab and Zimberelimab is more effective than historical standard treatments in patients with 5 types of advanced rare cancers, after failure of at least one line of standard treatment i&#96; to &#96;Immune checkpoint inhibitors (ICI) have revolutionized the management of advanced cancers. However, most rare cancers have been excluded from this progress due to the lack of clinical trials involving these diseases. After the standard first-line treatment, there are no other validated treatments for most of them. The management of these patients in ≥ 2nd line treatment relies on historic poorly effective regimens. |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | This creates an inequity between patients with frequent cancers beneficiating from medical progresses and approvals of innovative drugs, and patients with rare cancers are still treated with old and toxic drugs.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | Few available data on case reports and early phase studies indicate a beneficial role of the immunotherapy in rare cancers.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | The investigators assume that the combination of Domvanalimab and Zimberelimab is more effective than historical standard treatments in patients with 5 types of advanced rare cancers, after failure of at least one line of standard treatment i&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;05 | **conditionsModule.keywords.&#91;4&#93;**: Thymomas and Thymic Carcinomas                                                                | **conditionsModule.keywords.&#91;4&#93;**: Thymic Carcinomas                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;05 | **designModule.enrollmentInfo.count**: 154                                                                                               | **designModule.enrollmentInfo.count**: 27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-07-28 00&#58;26&#58;05 | **designModule.enrollmentInfo.type**: ESTIMATED                                                                                          | **designModule.enrollmentInfo.type**: ACTUAL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;05 | **armsInterventionsModule.armGroups.&#91;2&#93;label**: Cohort 3&#58; B3 thymomas and thymic carcinomas                                  | **armsInterventionsModule.armGroups.&#91;2&#93;label**: Cohort 3&#58; Thymic carcinomas                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;05 | **armsInterventionsModule.interventions.&#91;0&#93;armGroupLabels.&#91;2&#93;**: Cohort 3&#58; B3 thymomas and thymic carcinomas         | **armsInterventionsModule.interventions.&#91;0&#93;armGroupLabels.&#91;2&#93;**: Cohort 3&#58; Thymic carcinomas                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | General inclusion criteria for all cohorts                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * Histologically proven advanced solid tumors that progressed/resisted after minimum one line of standard systemic treatment, or resisted during the first-line of treatment                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * No indication of curative surgery for this disease at inclusion (For cohort 1 only (peritoneal mesothelioma), debulking surgery could be considered after minimum 6 months of study treatment in the case of important tumor response)                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * Evaluable lesions (target or non-target lesions) for radiological response according to RECIST 1.1 (cohorts 3, 4, 5), or mRECIST (cohort 1), or assessable for biological response with serum hCG (cohort 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * Patients older than 18 years                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * Patients with Eastern Cooperative Oncology Group (ECOG) performance status ≤ 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * Patients must be willing to provide an archival tumor tissue block or slides, or undergo procedure to obtain a new biopsy in absence of medical contraindication (If either a fresh biopsy or archival material &#96; to &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | General inclusion criteria for all cohorts                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * Histologically proven advanced solid tumors that progressed/resisted after minimum one line of standard systemic treatment, or resisted during the first-line of treatment                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * Participation in IMMUNORARE5 trial testing DOMVANALIMAB and ZIMBERELIMAB, validated by a multidisciplinary tumor board recognized by the national reference center, or validated by at least one national coordinator of the cohort                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * No indication of curative surgery for this disease at inclusion (For cohort 1 only (peritoneal mesothelioma), debulking surgery could be considered after minimum 6 months of study treatment in the case of important tumor response)                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * Evaluable lesions (target or non-target lesions) for radiological response according to RECIST 1.1 (cohorts 3, 4, 5), or mRECIST (cohort 1), or assessable for biological response with serum hCG (cohort 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * Patients older than 18 years                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                        | * Patients with Eastern Cooperative Oncology Group (ECOG) per&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;centralContacts&#x27;&#93;** (Removed)                                     | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;status&#x27;&#93;** (Removed)    | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;1&#93;&#91;&#x27;status&#x27;&#93;** (Removed)    | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;1&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;2&#93;&#91;&#x27;status&#x27;&#93;** (Removed)    | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;2&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;3&#93;&#91;&#x27;status&#x27;&#93;** (Removed)    | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;3&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;4&#93;&#91;&#x27;status&#x27;&#93;** (Removed)    | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;4&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;5&#93;&#91;&#x27;status&#x27;&#93;** (Removed)    | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;5&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;6&#93;&#91;&#x27;status&#x27;&#93;** (Removed)    | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;6&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;7&#93;&#91;&#x27;status&#x27;&#93;** (Removed)    | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;7&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;8&#93;&#91;&#x27;status&#x27;&#93;** (Removed)    | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;8&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;9&#93;&#91;&#x27;status&#x27;&#93;** (Removed)    | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;9&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;10&#93;&#91;&#x27;status&#x27;&#93;** (Removed)   | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;10&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed) | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;11&#93;&#91;&#x27;status&#x27;&#93;** (Removed)   | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;11&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed) | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;12&#93;&#91;&#x27;status&#x27;&#93;** (Removed)   | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;12&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed) | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;13&#93;&#91;&#x27;status&#x27;&#93;** (Removed)   | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;13&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed) | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;14&#93;&#91;&#x27;status&#x27;&#93;** (Removed)   | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-07-28 00&#58;26&#58;05 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;14&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed) | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
