---
title: "NCT05581004 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|:----------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-18 01&#58;00&#58;46 | **statusModule.statusVerifiedDate**: 2026-01                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-02-18 01&#58;00&#58;46 | **statusModule.lastUpdateSubmitDate**: 2026-01-16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | **statusModule.lastUpdateSubmitDate**: 2026-02-16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-02-18 01&#58;00&#58;46 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-02-18 01&#58;00&#58;46 | **contactsLocationsModule.locations.&#91;22&#93;city**: N. Efkapria-Pavlos Melas                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;22&#93;city**: Pavlos Melas                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-02-18 01&#58;00&#58;46 | **contactsLocationsModule.locations.&#91;30&#93;facility**: ICO l?Hospitalet ? Hospital Duran i Reynals                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;30&#93;facility**: ICO Hospitalet- Hospital Duran i Reynals                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;39 | **identificationModule.briefTitle**: A Study to Evaluate the Safety, Pharmacokinetics, and Activity of RO7502175 as a Single Agent and in Combination With Checkpoint Inhibitor in Participants With Locally Advanced or Metastatic Solid Tumors                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | **identificationModule.briefTitle**: A Study to Evaluate the Safety, Pharmacokinetics, and Activity of Enzelkitug as a Single Agent and in Combination With Checkpoint Inhibitor in Participants With Locally Advanced or Metastatic Solid Tumors                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-05-26 02&#58;38&#58;39 | **identificationModule.officialTitle**: A Phase Ia/Ib, Open Label, Multicenter, Dose-escalation Study to Evaluate the Safety, Pharmacokinetics, and Activity of RO7502175 as a Single Agent and in Combination With Checkpoint Inhibitor in Patients With Locally Advanced or Metastatic Solid Tumors                                                                                                                                                                                                                                                                                                                                                                                                                                                    | **identificationModule.officialTitle**: A Phase Ia/Ib, Open Label, Multicenter, Dose-escalation Study to Evaluate the Safety, Pharmacokinetics, and Activity of Enzelkitug as a Single Agent and in Combination With Checkpoint Inhibitor in Patients With Locally Advanced or Metastatic Solid Tumors                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **statusModule.statusVerifiedDate**: 2026-05                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.primaryCompletionDateStruct.date**: 2027-02-28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **statusModule.primaryCompletionDateStruct.date**: 2028-07-31                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.completionDateStruct.date**: 2027-02-28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | **statusModule.completionDateStruct.date**: 2028-07-31                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.lastUpdateSubmitDate**: 2026-02-16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | **statusModule.lastUpdateSubmitDate**: 2026-05-08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;39 | **descriptionModule.briefSummary**: This is a first-in-human study to evaluate the safety, tolerability, pharmacokinetics (PK), and anti-tumor activity of RO7502175 when administered as a single agent and in combination with atezolizumab or pembrolizumab in adult participants with locally advanced or metastatic solid tumors, including non-small-cell lung cancer (NSCLC), head and neck squamous cell carcinoma (HNSCC), melanoma, triple-negative breast cancer (TNBC), esophageal cancer, gastric cancer, cervical cancer, colorectal cancer (CRC), urothelial carcinoma (UC), clear cell renal cell carcinoma (RCC) and hepatocellular carcinoma (HCC). Participants will be enrolled in 2 stages&#58; dose escalation and dose expansion. | **descriptionModule.briefSummary**: This is a first-in-human study to evaluate the safety, tolerability, pharmacokinetics (PK), and anti-tumor activity of enzelkitug when administered as a single agent and in combination with atezolizumab or pembrolizumab in adult participants with locally advanced or metastatic solid tumors, including non small cell lung cancer (NSCLC), head and neck squamous cell carcinoma (HNSCC), melanoma, triple-negative breast cancer (TNBC), esophageal cancer, gastric cancer, cervical cancer, colorectal cancer (CRC), urothelial carcinoma (UC), clear cell renal cell carcinoma (RCC) and hepatocellular carcinoma (HCC). Participants will be enrolled in 2 stages&#58; dose escalation and dose expansion. |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Life expectancy at least 12 weeks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Eastern Cooperative Oncology Group (ECOG) performance status of 0 or 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Measurable disease according to Response Evaluation criteria in Solid Tumors (RECIST) Version 1.1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Histologically confirmed locally advanced, recurrent, or metastatic incurable solid tumor malignancy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Tumor Specimen availability                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Pregnant or breastfeeding or intention of becoming pregnant during the study or within 4 months after the final dose of RO7501275, or 4 months after the final dose of pembrolizumab, or 5 months after the final dose of atezolizumab                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Any anti-cancer therapy, whether investigational or approved, including chemotherapy, hormonal therapy, or radiotherapy, within 3 weeks prior to initiation of study treatment                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Active hepatitis B or C or tuberculosis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Positive test for human immunodeficiency virus (HIV) infection                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Acute or chronic active Epstein-Barr virus (EBV) infection at screening                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Administration of a li&#96; to &#96;Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Life expectancy of at least 12 weeks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Eastern Cooperative Oncology Group (ECOG) performance status of 0 or 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Measurable disease according to Response Evaluation Criteria in Solid Tumors Version 1.1 (RECIST v1.1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Histologically confirmed locally advanced, recurrent, or metastatic incurable solid tumor malignancy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Tumor specimen availability                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Pregnant or breastfeeding or intention of becoming pregnant during the study or within 4 months after the final dose of enzelkitug, or 4 months after the final dose of pembrolizumab, or 5 months after the final dose of atezolizumab                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Any anti-cancer therapy, whether investigational or approved, including chemotherapy, hormonal therapy, and/or radiotherapy, within 3 weeks prior to initiation of study treatment                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Active hepatitis B (HBV) or hepatitis C (HCV) or tuberculosis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Positive test for human immunodeficiency virus (HIV) infection                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | * Acute or chronic active Epstein-Barr virus (EBV) infection at&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;39 | **outcomesModule.secondaryOutcomes.&#91;0&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Phase Ia and Phase Ib&#58; Maximum Serum Concentration (Cmax) of RO7502175&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From Cycle 1 (each cycle is 21 days) Day1 and at multiple timepoints up to each follow-up visits (up to approximately 5 years)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                     | **outcomesModule.secondaryOutcomes.&#91;0&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Phase Ia and Phase Ib&#58; Maximum Serum Concentration (Cmax) of Enzelkitug&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From Cycle 1 (each cycle is 21 days) Day 1, and at multiple timepoints up to each follow-up visits (up to approximately 52 months)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-05-26 02&#58;38&#58;39 | **armsInterventionsModule.armGroups.&#91;2&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Phase Ib&#58; Dose Escalation&#x27;, &#x27;type&#x27;&#58; &#x27;EXPERIMENTAL&#x27;, &#x27;description&#x27;&#58; &#x27;Participants in successive cohorts will receive escalating doses of RO7502175, as an IV infusion, in combination with a fixed dose of atezolizumab, as an IV infusion on Day 1 of each 21-day cycle until disease progression or unacceptable toxicity.&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; RO7502175&#x27;, &#x27;Drug&#58; Atezolizumab&#x27;&#93;&#125;                                                                                                                                                      | **armsInterventionsModule.armGroups.&#91;2&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Phase Ib&#58; Dose Escalation&#x27;, &#x27;type&#x27;&#58; &#x27;EXPERIMENTAL&#x27;, &#x27;description&#x27;&#58; &#x27;Participants in successive cohorts will receive escalating doses of enzelkitug, as an IV infusion, in combination with a fixed dose of atezolizumab, as an IV infusion on Day 1 of each 21-day cycle until disease progression or unacceptable toxicity.&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; Enzelkitug&#x27;, &#x27;Drug&#58; Atezolizumab&#x27;&#93;&#125;                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;39 | **armsInterventionsModule.interventions.&#91;2&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Pembrolizumab&#x27;, &#x27;description&#x27;&#58; &#x27;Pembrolizumab will be administered as per the schedules specified in the respective arms.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Phase Ib&#58; Expansion&#x27;&#93;&#125;                                                                                                                                                                                                                                                                                                                                                                            | **armsInterventionsModule.interventions.&#91;2&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Pembrolizumab&#x27;, &#x27;description&#x27;&#58; &#x27;Pembrolizumab will be administered as per the schedule specified in the respective arms.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Phase Ib&#58; Expansion&#x27;&#93;, &#x27;otherNames&#x27;&#58; &#91;&#x27;Keytruda&#x27;&#93;&#125;                                                                                                                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;39 | **armsInterventionsModule.armGroups.&#91;1&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Phase Ia&#58; Expansion&#x27;, &#x27;type&#x27;&#58; &#x27;EXPERIMENTAL&#x27;, &#x27;description&#x27;&#58; &#x27;Participants with select solid tumors will receive a recommended dose of RO7502175, determined in Phase Ia Dose Escalation phase as an IV infusion on Day 1 of each 21-day cycle until disease progression or unacceptable toxicity.&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; RO7502175&#x27;&#93;&#125;                                                                                                                                                                                                                   | **armsInterventionsModule.armGroups.&#91;1&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Phase Ia&#58; Expansion&#x27;, &#x27;type&#x27;&#58; &#x27;EXPERIMENTAL&#x27;, &#x27;description&#x27;&#58; &#x27;Participants with select solid tumors will receive a recommended dose of enzelkitug, determined in Phase Ia dose escalation phase as an IV infusion on Day 1 of each 21-day cycle until disease progression or unacceptable toxicity.&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; Enzelkitug&#x27;&#93;&#125;                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;39 | **outcomesModule.secondaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Phase Ia and Phase Ib&#58; Duration of Response (DOR)&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From Cycle 1 (each cycle is 21 days) Day 1, until disease progression, death, or end of study (up to approximately 5 years)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                             | **outcomesModule.secondaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Phase Ia and Phase Ib&#58; Duration of Response (DOR)&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From Cycle 1 (each cycle is 21 days) Day 1, until disease progression, death, or end of study (up to approximately 52 months)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;39 | **outcomesModule.secondaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Phase Ia and Phase Ib&#58; Objective Response Rate (ORR)&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From Cycle 1(each cycle is 21 days) Day 1, until disease progression, death, or end of study (up to approximately 5 years)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                           | **outcomesModule.secondaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Phase Ia and Phase Ib&#58; Objective Response Rate (ORR)&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From Cycle 1(each cycle is 21 days) Day 1, until disease progression, death, or end of study (up to approximately 52 months)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;39 | **outcomesModule.primaryOutcomes.&#91;3&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Phase Ib&#58; Number of Participants with Treatment Emergent Adverse Events&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to approximately 5 years&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | **outcomesModule.primaryOutcomes.&#91;3&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Phase Ib&#58; Number of Participants With TEAEs&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to approximately 52 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-05-26 02&#58;38&#58;39 | **outcomesModule.primaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Phase Ia&#58; Number of Participants with Treatment Emergent Adverse Events&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to approximately 5 years&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | **outcomesModule.primaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Phase Ia&#58; Number of Participants With Treatment-emergent Adverse Events (TEAEs)&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to approximately 52 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;39 | **armsInterventionsModule.interventions.&#91;1&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Atezolizumab&#x27;, &#x27;description&#x27;&#58; &#x27;Atezolizumab will be administered as per the schedules specified in the respective arms.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Phase Ib&#58; Dose Escalation&#x27;, &#x27;Phase Ib&#58; Expansion&#x27;&#93;&#125;                                                                                                                                                                                                                                                                                                                                   | **armsInterventionsModule.interventions.&#91;1&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;DRUG&#x27;, &#x27;name&#x27;&#58; &#x27;Atezolizumab&#x27;, &#x27;description&#x27;&#58; &#x27;Atezolizumab will be administered as per the schedule specified in the respective arms.&#x27;, &#x27;armGroupLabels&#x27;&#58; &#91;&#x27;Phase Ib&#58; Dose Escalation&#x27;, &#x27;Phase Ib&#58; Expansion&#x27;&#93;, &#x27;otherNames&#x27;&#58; &#91;&#x27;Tecentriq&#x27;&#93;&#125;                                                                                                                                                                                                                                                                        |
| 2026-05-26 02&#58;38&#58;39 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Field &#96;outcomesModule.secondaryOutcomes.&#91;4&#93;&#96; changed from &#96;&#123;&#x27;measure&#x27;&#58; &#x27;Phase Ia and Phase Ib&#58; Percentage of Participants With Anti-Drug Antibody (ADA) to RO7502175&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From Cycle 1 (each cycle is 21 days) Day 1 and at multiple timepoints up to tre                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-06-10 03&#58;50&#58;42 | **statusModule.statusVerifiedDate**: 2026-05                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **statusModule.statusVerifiedDate**: 2026-06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-06-10 03&#58;50&#58;42 | **statusModule.lastUpdateSubmitDate**: 2026-05-08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | **statusModule.lastUpdateSubmitDate**: 2026-06-05                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-06-10 03&#58;50&#58;42 | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-09                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-06-10 03&#58;50&#58;42 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | **root&#91;&#x27;referencesModule&#x27;&#93;** (Added)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
