---
title: "NCT05645692 Change History"
---

| Timestamp                   | Before                                                                   | After                                                                    |
|:----------------------------|:-------------------------------------------------------------------------|:-------------------------------------------------------------------------|
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;24&#93;city**: Napoli           | **contactsLocationsModule.locations.&#91;24&#93;city**: Naples           |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;24&#93;geoPoint.lat**: 40.87618 | **contactsLocationsModule.locations.&#91;24&#93;geoPoint.lat**: 40.85216 |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;24&#93;geoPoint.lon**: 14.5195  | **contactsLocationsModule.locations.&#91;24&#93;geoPoint.lon**: 14.26811 |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;30&#93;city**: Padua            | **contactsLocationsModule.locations.&#91;30&#93;city**: Padova           |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;30&#93;geoPoint.lat**: 45.40797 | **contactsLocationsModule.locations.&#91;30&#93;geoPoint.lat**: 45.26618 |
| 2026-04-04 02&#58;21&#58;52 | **contactsLocationsModule.locations.&#91;30&#93;geoPoint.lon**: 11.88586 | **contactsLocationsModule.locations.&#91;30&#93;geoPoint.lon**: 11.77208 |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2026-01                             | **statusModule.statusVerifiedDate**: 2026-04                             |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2026-01-28                        | **statusModule.lastUpdateSubmitDate**: 2026-04-28                        |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-30               | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-29               |
| 2026-07-29 02&#58;41&#58;00 | **statusModule.statusVerifiedDate**: 2026-04                             | **statusModule.statusVerifiedDate**: 2026-07                             |
| 2026-07-29 02&#58;41&#58;00 | **statusModule.lastUpdateSubmitDate**: 2026-04-28                        | **statusModule.lastUpdateSubmitDate**: 2026-07-27                        |
| 2026-07-29 02&#58;41&#58;00 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-29               | **statusModule.lastUpdatePostDateStruct.date**: 2026-07-28               |
