---
title: "NCT05329766 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                      | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|:----------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-28 00&#58;50&#58;47 | **statusModule.lastUpdateSubmitDate**: 2026-01-27                                                                                                                                                                                                                                                                                                                                                                                           | **statusModule.lastUpdateSubmitDate**: 2026-02-25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-02-28 00&#58;50&#58;47 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-29                                                                                                                                                                                                                                                                                                                                                                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-03-31 02&#58;31&#58;37 | **statusModule.lastUpdateSubmitDate**: 2026-02-25                                                                                                                                                                                                                                                                                                                                                                                           | **statusModule.lastUpdateSubmitDate**: 2026-03-27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-31 02&#58;31&#58;37 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-27                                                                                                                                                                                                                                                                                                                                                                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-30                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2025-03                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2026-03-27                                                                                                                                                                                                                                                                                                                                                                                           | **statusModule.lastUpdateSubmitDate**: 2026-04-28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-30                                                                                                                                                                                                                                                                                                                                                                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;9&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Columbia University&#x27;, &#x27;city&#x27;&#58; &#x27;New York&#x27;, &#x27;state&#x27;&#58; &#x27;New York&#x27;, &#x27;zip&#x27;&#58; &#x27;10032&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 40.71427, &#x27;lon&#x27;&#58; -74.00597&#125;&#125;                          | **contactsLocationsModule.locations.&#91;9&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;New York&#x27;, &#x27;state&#x27;&#58; &#x27;New York&#x27;, &#x27;zip&#x27;&#58; &#x27;10032&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 40.71427, &#x27;lon&#x27;&#58; -74.00597&#125;&#125;                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;8&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Memorial Sloan Kettering Cancer Center&#x27;, &#x27;city&#x27;&#58; &#x27;New York&#x27;, &#x27;state&#x27;&#58; &#x27;New York&#x27;, &#x27;zip&#x27;&#58; &#x27;10021-0005&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 40.71427, &#x27;lon&#x27;&#58; -74.00597&#125;&#125;  | **contactsLocationsModule.locations.&#91;8&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;New York&#x27;, &#x27;state&#x27;&#58; &#x27;New York&#x27;, &#x27;zip&#x27;&#58; &#x27;10021-0005&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 40.71427, &#x27;lon&#x27;&#58; -74.00597&#125;&#125;                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;30&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;CHU de Toulouse_Oncopole&#x27;, &#x27;city&#x27;&#58; &#x27;Toulouse&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.60426, &#x27;lon&#x27;&#58; 1.44367&#125;&#125;                                                                                                                  | **contactsLocationsModule.locations.&#91;30&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Rouen&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 49.44313, &#x27;lon&#x27;&#58; 1.09932&#125;&#125;                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;25&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Centre Léon Bérard _ Lyon&#x27;, &#x27;city&#x27;&#58; &#x27;Lyon&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 45.74906, &#x27;lon&#x27;&#58; 4.84789&#125;&#125;                                                                                                                     | **contactsLocationsModule.locations.&#91;25&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Lyon&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 45.74906, &#x27;lon&#x27;&#58; 4.84789&#125;&#125;                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;28&#93;**: &#123;&#x27;facility&#x27;&#58; &quot;Centre Armoricain de Radiothérapie, d&#x27;Imagerie Médicale et d&#x27;Oncologie&quot;, &#x27;city&#x27;&#58; &#x27;Plérin&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 48.53451, &#x27;lon&#x27;&#58; -2.76975&#125;&#125;                                                           | **contactsLocationsModule.locations.&#91;28&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Plérin&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 48.53451, &#x27;lon&#x27;&#58; -2.76975&#125;&#125;                                                                                                                                                                                                                                        |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;1&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;USC/Norris Comprehensive Cancer Center&#x27;, &#x27;city&#x27;&#58; &#x27;Los Angeles&#x27;, &#x27;state&#x27;&#58; &#x27;California&#x27;, &#x27;zip&#x27;&#58; &#x27;90033&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.05223, &#x27;lon&#x27;&#58; -118.24368&#125;&#125; | **contactsLocationsModule.locations.&#91;1&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Los Angeles&#x27;, &#x27;state&#x27;&#58; &#x27;California&#x27;, &#x27;zip&#x27;&#58; &#x27;90033&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.05223, &#x27;lon&#x27;&#58; -118.24368&#125;&#125;                                                                                                                                    |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;3&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Yale Cancer Center&#x27;, &#x27;city&#x27;&#58; &#x27;Derby&#x27;, &#x27;state&#x27;&#58; &#x27;Connecticut&#x27;, &#x27;zip&#x27;&#58; &#x27;06418&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.32065, &#x27;lon&#x27;&#58; -73.089&#125;&#125;                             | **contactsLocationsModule.locations.&#91;3&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Derby&#x27;, &#x27;state&#x27;&#58; &#x27;Connecticut&#x27;, &#x27;zip&#x27;&#58; &#x27;06418&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 41.32065, &#x27;lon&#x27;&#58; -73.089&#125;&#125;                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;36&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Clinical Center Kragujevac&#x27;, &#x27;city&#x27;&#58; &#x27;Kragujevac&#x27;, &#x27;country&#x27;&#58; &#x27;Serbia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 44.01667, &#x27;lon&#x27;&#58; 20.91667&#125;&#125;                                                                                                             | **contactsLocationsModule.locations.&#91;36&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Busan&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.10168, &#x27;lon&#x27;&#58; 129.03004&#125;&#125;                                                                                                                                                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;12&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;OU - Stephenson Cancer Center&#x27;, &#x27;city&#x27;&#58; &#x27;Oklahoma City&#x27;, &#x27;state&#x27;&#58; &#x27;Oklahoma&#x27;, &#x27;zip&#x27;&#58; &#x27;73104&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.46756, &#x27;lon&#x27;&#58; -97.51643&#125;&#125;          | **contactsLocationsModule.locations.&#91;12&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Oklahoma City&#x27;, &#x27;state&#x27;&#58; &#x27;Oklahoma&#x27;, &#x27;zip&#x27;&#58; &#x27;73104&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.46756, &#x27;lon&#x27;&#58; -97.51643&#125;&#125;                                                                                                                                    |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;7&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Massachusetts General Hospital&#x27;, &#x27;city&#x27;&#58; &#x27;Boston&#x27;, &#x27;state&#x27;&#58; &#x27;Massachusetts&#x27;, &#x27;zip&#x27;&#58; &#x27;02109&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 42.35843, &#x27;lon&#x27;&#58; -71.05977&#125;&#125;            | **contactsLocationsModule.locations.&#91;7&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Boston&#x27;, &#x27;state&#x27;&#58; &#x27;Massachusetts&#x27;, &#x27;zip&#x27;&#58; &#x27;02109&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 42.35843, &#x27;lon&#x27;&#58; -71.05977&#125;&#125;                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;31&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Gustave Roussy - Villejuif&#x27;, &#x27;city&#x27;&#58; &#x27;Villejuif&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 48.7939, &#x27;lon&#x27;&#58; 2.35992&#125;&#125;                                                                                                                | **contactsLocationsModule.locations.&#91;31&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Toulouse&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.60426, &#x27;lon&#x27;&#58; 1.44367&#125;&#125;                                                                                                                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;40&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;CHA Bundang Medical Center&#x27;, &#x27;city&#x27;&#58; &#x27;Seongnam-si&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 37.43861, &#x27;lon&#x27;&#58; 127.13778&#125;&#125;                                                                                                      | **contactsLocationsModule.locations.&#91;40&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Seoul&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 37.566, &#x27;lon&#x27;&#58; 126.9784&#125;&#125;                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;2&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Ronald Reagan UCLA Medical Center&#x27;, &#x27;city&#x27;&#58; &#x27;Santa Monica&#x27;, &#x27;state&#x27;&#58; &#x27;California&#x27;, &#x27;zip&#x27;&#58; &#x27;90024&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.01949, &#x27;lon&#x27;&#58; -118.49138&#125;&#125;     | **contactsLocationsModule.locations.&#91;2&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Santa Monica&#x27;, &#x27;state&#x27;&#58; &#x27;California&#x27;, &#x27;zip&#x27;&#58; &#x27;90024&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 34.01949, &#x27;lon&#x27;&#58; -118.49138&#125;&#125;                                                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;34&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;University Hospital Medical Center (KBC) Bezanijska Kosa&#x27;, &#x27;city&#x27;&#58; &#x27;Belgrade&#x27;, &#x27;country&#x27;&#58; &#x27;Serbia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 44.80401, &#x27;lon&#x27;&#58; 20.46513&#125;&#125;                                                                                 | **contactsLocationsModule.locations.&#91;34&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Kamenitz&#x27;, &#x27;country&#x27;&#58; &#x27;Serbia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 45.22334, &#x27;lon&#x27;&#58; 19.84263&#125;&#125;                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;16&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;UHN - Princess Margaret Cancer Centre&#x27;, &#x27;city&#x27;&#58; &#x27;Toronto&#x27;, &#x27;country&#x27;&#58; &#x27;Canada&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.70643, &#x27;lon&#x27;&#58; -79.39864&#125;&#125;                                                                                                    | **contactsLocationsModule.locations.&#91;16&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Toronto&#x27;, &#x27;country&#x27;&#58; &#x27;Canada&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.70643, &#x27;lon&#x27;&#58; -79.39864&#125;&#125;                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;17&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Clínica San Carlos de Apoquindo&#x27;, &#x27;city&#x27;&#58; &#x27;Las Condes&#x27;, &#x27;country&#x27;&#58; &#x27;Chile&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -33.41636, &#x27;lon&#x27;&#58; -70.56413&#125;&#125;                                                                                                       | **contactsLocationsModule.locations.&#91;17&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Las Condes&#x27;, &#x27;country&#x27;&#58; &#x27;Chile&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -33.41636, &#x27;lon&#x27;&#58; -70.56413&#125;&#125;                                                                                                                                                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;10&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Duke University&#x27;, &#x27;city&#x27;&#58; &#x27;Durham&#x27;, &#x27;state&#x27;&#58; &#x27;North Carolina&#x27;, &#x27;zip&#x27;&#58; &#x27;27710&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.99403, &#x27;lon&#x27;&#58; -78.89862&#125;&#125;                         | **contactsLocationsModule.locations.&#91;10&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Durham&#x27;, &#x27;state&#x27;&#58; &#x27;North Carolina&#x27;, &#x27;zip&#x27;&#58; &#x27;27710&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.99403, &#x27;lon&#x27;&#58; -78.89862&#125;&#125;                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;26&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Hôpital Timone - Marseille&#x27;, &#x27;city&#x27;&#58; &#x27;Marseille&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.29695, &#x27;lon&#x27;&#58; 5.38107&#125;&#125;                                                                                                               | **contactsLocationsModule.locations.&#91;26&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Marseille&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 43.29695, &#x27;lon&#x27;&#58; 5.38107&#125;&#125;                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;37&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Dong-A University Hospital&#x27;, &#x27;city&#x27;&#58; &#x27;Busan&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.10168, &#x27;lon&#x27;&#58; 129.03004&#125;&#125;                                                                                                            | **contactsLocationsModule.locations.&#91;37&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Daegu&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.87028, &#x27;lon&#x27;&#58; 128.59111&#125;&#125;                                                                                                                                                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;19&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Centro de Estudios Clínicos SAGA&#x27;, &#x27;city&#x27;&#58; &#x27;Santiago&#x27;, &#x27;country&#x27;&#58; &#x27;Chile&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -33.45694, &#x27;lon&#x27;&#58; -70.64827&#125;&#125;                                                                                                        | **contactsLocationsModule.locations.&#91;19&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Santiago&#x27;, &#x27;country&#x27;&#58; &#x27;Chile&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; -33.45694, &#x27;lon&#x27;&#58; -70.64827&#125;&#125;                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;5&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Mayo Clinic - Jacksonville&#x27;, &#x27;city&#x27;&#58; &#x27;Jacksonville&#x27;, &#x27;state&#x27;&#58; &#x27;Florida&#x27;, &#x27;zip&#x27;&#58; &#x27;32224&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 30.33218, &#x27;lon&#x27;&#58; -81.65565&#125;&#125;                | **contactsLocationsModule.locations.&#91;5&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Jacksonville&#x27;, &#x27;state&#x27;&#58; &#x27;Florida&#x27;, &#x27;zip&#x27;&#58; &#x27;32224&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 30.33218, &#x27;lon&#x27;&#58; -81.65565&#125;&#125;                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;14&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Vanderbilt-Ingram Cancer Center&#x27;, &#x27;city&#x27;&#58; &#x27;Nashville&#x27;, &#x27;state&#x27;&#58; &#x27;Tennessee&#x27;, &#x27;zip&#x27;&#58; &#x27;37232&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 36.16589, &#x27;lon&#x27;&#58; -86.78444&#125;&#125;           | **contactsLocationsModule.locations.&#91;14&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Nashville&#x27;, &#x27;state&#x27;&#58; &#x27;Tennessee&#x27;, &#x27;zip&#x27;&#58; &#x27;37232&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 36.16589, &#x27;lon&#x27;&#58; -86.78444&#125;&#125;                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;33&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;University Clinical Center of Serbia&#x27;, &#x27;city&#x27;&#58; &#x27;Belgrade&#x27;, &#x27;country&#x27;&#58; &#x27;Serbia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 44.80401, &#x27;lon&#x27;&#58; 20.46513&#125;&#125;                                                                                                     | **contactsLocationsModule.locations.&#91;33&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Belgrade&#x27;, &#x27;country&#x27;&#58; &#x27;Serbia&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 44.80401, &#x27;lon&#x27;&#58; 20.46513&#125;&#125;                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;38&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Kyungpook National University Chilgok Hospital&#x27;, &#x27;city&#x27;&#58; &#x27;Daegu&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.87028, &#x27;lon&#x27;&#58; 128.59111&#125;&#125;                                                                                        | **contactsLocationsModule.locations.&#91;38&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Hwasun&#x27;, &#x27;country&#x27;&#58; &#x27;South Korea&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 35.06125, &#x27;lon&#x27;&#58; 126.98746&#125;&#125;                                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;23&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Centre Baclesse - CAEN&#x27;, &#x27;city&#x27;&#58; &#x27;Caen&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 49.18585, &#x27;lon&#x27;&#58; -0.35912&#125;&#125;                                                                                                                       | **contactsLocationsModule.locations.&#91;23&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Caen&#x27;, &#x27;country&#x27;&#58; &#x27;France&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 49.18585, &#x27;lon&#x27;&#58; -0.35912&#125;&#125;                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;4&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Florida Cancer Specialist - South&#x27;, &#x27;city&#x27;&#58; &#x27;Fort Myers&#x27;, &#x27;state&#x27;&#58; &#x27;Florida&#x27;, &#x27;zip&#x27;&#58; &#x27;33901&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 26.62168, &#x27;lon&#x27;&#58; -81.84059&#125;&#125;           | **contactsLocationsModule.locations.&#91;4&#93;**: &#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; &#x27;Fort Myers&#x27;, &#x27;state&#x27;&#58; &#x27;Florida&#x27;, &#x27;zip&#x27;&#58; &#x27;33901&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 26.62168, &#x27;lon&#x27;&#58; -81.84059&#125;&#125;                                                                                                                                         |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                           | Field &#96;contactsLocationsModule.locations.&#91;15&#93;&#96; changed from &#96;&#123;&#x27;facility&#x27;&#58; &#x27;Virginia Cancer Specialists&#x27;, &#x27;city&#x27;&#58; &#x27;Fairfax&#x27;, &#x27;state&#x27;&#58; &#x27;Virginia&#x27;, &#x27;zip&#x27;&#58; &#x27;22031&#x27;, &#x27;country&#x27;&#58; &#x27;United States&#x27;, &#x27;geoPoint&#x27;&#58; &#123;&#x27;lat&#x27;&#58; 38.84622, &#x27;lon&#x27;&#58; -77.30637&#125;&#125;&#96; to &#96;&#123;&#x27;facility&#x27;&#58; &#x27;Research Site&#x27;, &#x27;city&#x27;&#58; |
| 2026-06-02 04&#58;04&#58;22 | **statusModule.lastUpdateSubmitDate**: 2026-04-28                                                                                                                                                                                                                                                                                                                                                                                           | **statusModule.lastUpdateSubmitDate**: 2026-05-28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-06-02 04&#58;04&#58;22 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-29                                                                                                                                                                                                                                                                                                                                                                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-01                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-06-03 04&#58;13&#58;53 | **statusModule.lastUpdateSubmitDate**: 2026-05-28                                                                                                                                                                                                                                                                                                                                                                                           | **statusModule.lastUpdateSubmitDate**: 2026-05-29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-06-03 04&#58;13&#58;53 | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-01                                                                                                                                                                                                                                                                                                                                                                                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
