---
title: "NCT05414032 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                          | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-26 00&#58;55&#58;49 | **statusModule.statusVerifiedDate**: 2025-03                                                                                                                                                                                                                                                                                                                                                                                                                    | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-02-26 00&#58;55&#58;49 | **statusModule.primaryCompletionDateStruct.date**: 2026-07                                                                                                                                                                                                                                                                                                                                                                                                      | **statusModule.primaryCompletionDateStruct.date**: 2027-09                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-02-26 00&#58;55&#58;49 | **statusModule.completionDateStruct.date**: 2026-07                                                                                                                                                                                                                                                                                                                                                                                                             | **statusModule.completionDateStruct.date**: 2028-07                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-02-26 00&#58;55&#58;49 | **statusModule.lastUpdateSubmitDate**: 2025-03-25                                                                                                                                                                                                                                                                                                                                                                                                               | **statusModule.lastUpdateSubmitDate**: 2026-02-23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-02-26 00&#58;55&#58;49 | **statusModule.lastUpdatePostDateStruct.date**: 2025-03-30                                                                                                                                                                                                                                                                                                                                                                                                      | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-02-26 00&#58;55&#58;49 | **descriptionModule.briefSummary**: This is a phase II, open-label study to assess the efficacy of AZD2936 in terms of molecular residual disease (MRD) clearance and treatment outcome in patients with MRD after definitive treatment for high risk locoregionally advanced head and neck squamous cell carcinoma (LA-HNSCC). MRD is defined as ctDNA detection in plasma after definitive treatment. Approximately 200 patients are expected to be enrolled. | **descriptionModule.briefSummary**: This is a phase II, open-label study to assess the efficacy of AZD2936 in terms of molecular residual disease (MRD) clearance and treatment outcome in patients with MRD after definitive treatment for high risk locoregionally advanced head and neck squamous cell carcinoma (LA-HNSCC). MRD is defined as ctDNA detection in plasma after definitive treatment. Approximately 100 patients are expected to be enrolled.                                                                                                                                                                                                                                                                                                                                                        |
| 2026-02-26 00&#58;55&#58;49 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Field &#96;descriptionModule.detailedDescription&#96; changed from &#96;This is a phase II, open-label study to assess the efficacy of AZD2936 in terms of molecular residual disease (MRD) clearance and treatment outcome in patients with MRD after definitive treatment for high risk locoregionally advanced head and neck squamous cell carcinoma (LA-HNSCC). MRD is defined as ctDNA detection in plasma after definitive treatment. Approximately 200 patients are expected to be enrolled.                                                                                                                                                                                                                                                                                                                    |
| 2026-02-26 00&#58;55&#58;49 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                               | The study is divided in 5 parts&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-02-26 00&#58;55&#58;49 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Part A and Part B are common for all patients in the study, which are defined as the periods of definitive treatment and post definitive treatment. Definitive treatment will be either surgery followed by radiation or chemoradiation; definitive radiation or definitive chemoradiation according to standard of care (SOC) in our institution. A baseline ctDNA sample collection and CT staging will be done before treatment. ctDNA analysis will be performed in Part B at approximately week 5 and at week 10 of this period, and patients will be classified as MRD positive or MRD negative based on the week 10 results. If a patient has equivocal results, a new sample will be taken around week 14. Patients who receive surgery as part of their treatment, will also get ctDNA analysis post-surgery. |
| 2026-02-26 00&#58;55&#58;49 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Part C is the randomized and interventional part of the study (n&#61;60) for patients with MRD. The patient will be randomized 3&#58;1 to Arm A (treatment with AZD2936) or Arm B (observation). Patients in Arm A will continue treatment until the occurrence of any of these circumstances&#58; after completion of 6 cycles, intolerable toxicity or patient decision. ctDNA analysis will be done at week 10 of Part C.                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-02-26 00&#58;55&#58;49 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Part D is the follow up part for patients with MRD. Two ctDNA samples will be analyzed at week 2 and at week 10 of Part D. Plasma samples will be collected every 6 months for the first 3 years and a final sample will be also collected if the patient has radiological or clinical progression. A CT/MRI scan will be performed at week 2 of Part D and, if clinically needed, according to SOC.                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-02-26 00&#58;55&#58;49 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Part E is the observational follow up part for patients without MRD. A ctDNA sample will be collected at the time of the first follow up and at radiological or clinical progression if applicable.&#96; to &#96;This is a phase II, open-label study to assess the efficacy of AZD2936 in terms of molecular residual disease (MRD) clearance and treatment outcome in patients with MRD after definitive treatment for high risk locoregionally advanced head and neck squamous cell carcinoma (LA-HNSCC). MRD is defined as ctDNA detection in plasma after definitive treatment. Approximately 100 patients are expected to be enrolled.                                                                                                                                                                           |
| 2026-02-26 00&#58;55&#58;49 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                               | The study is divided in 5 parts&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-02-26 00&#58;55&#58;49 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Part A and Part B are common for all patients in the study, which are defined as the periods of definitive treatment and post definitive treatment. Definitive treatment will be either surgery followed by radiation or chemoradiation; definitive radiation or definitive chemoradiation according to standard of care (SOC) in our institution. A baseline ctDNA sample collection and CT staging will be done before treatment. ctDNA analysis will be performed in Part B at approximately week 5, week 10, week 26 and week 52 of this period, and patients will be classified as MRD positive or MRD negative. Patients who receive surgery as part of their treatment, will also get ctDNA analysis post-surgery.                                                                                              |
| 2026-02-26 00&#58;55&#58;49 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Part C is the interventional part of the study (n&#61;14) for patients with MRD or radiological/clinical progression. Patients will continue treatment until the occurrence of any of these circumstances&#58; after completion of 6 cycles, intolerable toxicity or patient decision. ctDNA analysis will be done at week 10 of Part C.                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-02-26 00&#58;55&#58;49 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Part D is the follow up part for patients with MRD or radiological/clinical progression. Two ctDNA samples will be analyzed at week 2 and at week 10 of Part D. Plasma samples will be collected every 6 months for the first 3 years and a final sample will be also collected if the patient has radiological or clinical progression. A CT/MRI scan will be performed at week 2 of Part D and, if clinically needed, according to SOC.                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-02-26 00&#58;55&#58;49 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Part E is the observational follow up part for patients without MRD at the completion of part B or with MRD but fail screening to enter Parts C and D. ctDNA samples will be collected at radiological or clinical progression. Additional plasma samples at 6 and 12 months after completion of part B are strongly recommended.&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-02-26 00&#58;55&#58;49 | **designModule.enrollmentInfo.count**: 200                                                                                                                                                                                                                                                                                                                                                                                                                      | **designModule.enrollmentInfo.count**: 102                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-02-26 00&#58;55&#58;49 | **armsInterventionsModule.armGroups.&#91;0&#93;label**: MRD positive Cohort - Arm A (treatment)                                                                                                                                                                                                                                                                                                                                                                 | **armsInterventionsModule.armGroups.&#91;0&#93;label**: MRD positive and/or radiological/clinical progression Cohort                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-02-26 00&#58;55&#58;49 | **armsInterventionsModule.interventions.&#91;0&#93;armGroupLabels.&#91;0&#93;**: MRD positive Cohort - Arm A (treatment)                                                                                                                                                                                                                                                                                                                                        | **armsInterventionsModule.interventions.&#91;0&#93;armGroupLabels.&#91;0&#93;**: MRD positive and/or radiological/clinical progression Cohort                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
