---
title: "NCT04732494 Change History"
---

| Timestamp                   | Before                                                                    | After                                                                     |
|:----------------------------|:--------------------------------------------------------------------------|:--------------------------------------------------------------------------|
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;32&#93;geoPoint.lat**: 26.6636   | **contactsLocationsModule.locations.&#91;32&#93;geoPoint.lat**: 25.93504  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;32&#93;geoPoint.lon**: 114.148   | **contactsLocationsModule.locations.&#91;32&#93;geoPoint.lon**: 116.17968 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lat**: 28.26048  | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lat**: 27.60412  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lon**: 103.93137 | **contactsLocationsModule.locations.&#91;34&#93;geoPoint.lon**: 103.50288 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;35&#93;geoPoint.lat**: 39.46731  | **contactsLocationsModule.locations.&#91;35&#93;geoPoint.lat**: 37.92189  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;35&#93;geoPoint.lon**: 115.13706 | **contactsLocationsModule.locations.&#91;35&#93;geoPoint.lon**: 112.22494 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;36&#93;geoPoint.lat**: 39.46731  | **contactsLocationsModule.locations.&#91;36&#93;geoPoint.lat**: 37.92189  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;36&#93;geoPoint.lon**: 115.13706 | **contactsLocationsModule.locations.&#91;36&#93;geoPoint.lon**: 112.22494 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;37&#93;geoPoint.lat**: 39.46731  | **contactsLocationsModule.locations.&#91;37&#93;geoPoint.lat**: 37.92189  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;37&#93;geoPoint.lon**: 115.13706 | **contactsLocationsModule.locations.&#91;37&#93;geoPoint.lon**: 112.22494 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;38&#93;geoPoint.lat**: 34.01329  | **contactsLocationsModule.locations.&#91;38&#93;geoPoint.lat**: 29.08114  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;38&#93;geoPoint.lon**: 118.87165 | **contactsLocationsModule.locations.&#91;38&#93;geoPoint.lon**: 120.41732 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lat**: 34.01329  | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lat**: 29.08114  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lon**: 118.87165 | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lon**: 120.41732 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;40&#93;geoPoint.lat**: 33.9693   | **contactsLocationsModule.locations.&#91;40&#93;geoPoint.lat**: 32.92741  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;40&#93;geoPoint.lon**: 118.85431 | **contactsLocationsModule.locations.&#91;40&#93;geoPoint.lon**: 120.18021 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lat**: 26.82656  | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lat**: 40.28464  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lon**: 114.95747 | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lon**: 120.48412 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;44&#93;geoPoint.lat**: 26.82656  | **contactsLocationsModule.locations.&#91;44&#93;geoPoint.lat**: 40.28464  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;44&#93;geoPoint.lon**: 114.95747 | **contactsLocationsModule.locations.&#91;44&#93;geoPoint.lon**: 120.48412 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;50&#93;geoPoint.lat**: 22.4143   | **contactsLocationsModule.locations.&#91;50&#93;geoPoint.lat**: 25.3238   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;50&#93;geoPoint.lon**: 108.78745 | **contactsLocationsModule.locations.&#91;50&#93;geoPoint.lon**: 105.583   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;51&#93;geoPoint.lat**: 22.4143   | **contactsLocationsModule.locations.&#91;51&#93;geoPoint.lat**: 25.3238   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;51&#93;geoPoint.lon**: 108.78745 | **contactsLocationsModule.locations.&#91;51&#93;geoPoint.lon**: 105.583   |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;79&#93;city**: Taoyuan District  | **contactsLocationsModule.locations.&#91;79&#93;city**: Taoyuan           |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;79&#93;geoPoint.lat**: 24.9896   | **contactsLocationsModule.locations.&#91;79&#93;geoPoint.lat**: 24.99368  |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;79&#93;geoPoint.lon**: 121.3187  | **contactsLocationsModule.locations.&#91;79&#93;geoPoint.lon**: 121.29696 |
