---
title: "NCT06868277 Change History"
---

| Timestamp                   | Before                                                                        | After                                                                                                                               |
|:----------------------------|:------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------|
| 2026-03-03 00&#58;59&#58;14 | **statusModule.statusVerifiedDate**: 2026-01                                  | **statusModule.statusVerifiedDate**: 2026-02                                                                                        |
| 2026-03-03 00&#58;59&#58;14 | **statusModule.lastUpdateSubmitDate**: 2026-01-12                             | **statusModule.lastUpdateSubmitDate**: 2026-02-27                                                                                   |
| 2026-03-03 00&#58;59&#58;14 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-13                    | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-02                                                                          |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;28&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;28&#93;status**: RECRUITING                                                                |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;29&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;29&#93;status**: RECRUITING                                                                |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;31&#93;zip**: 2000                   | **contactsLocationsModule.locations.&#91;31&#93;zip**: S2000CVB                                                                     |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;42&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;42&#93;status**: RECRUITING                                                                |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;49&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;49&#93;status**: RECRUITING                                                                |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;50&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;50&#93;status**: RECRUITING                                                                |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;52&#93;city**: Santo André           | **contactsLocationsModule.locations.&#91;52&#93;city**: São Paulo                                                                   |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;52&#93;zip**: 09060-650              | **contactsLocationsModule.locations.&#91;52&#93;zip**: 03102-006                                                                    |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;52&#93;geoPoint.lat**: -23.66389     | **contactsLocationsModule.locations.&#91;52&#93;geoPoint.lat**: -23.5475                                                            |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;52&#93;geoPoint.lon**: -46.53833     | **contactsLocationsModule.locations.&#91;52&#93;geoPoint.lon**: -46.63611                                                           |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;54&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;54&#93;status**: RECRUITING                                                                |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;55&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;55&#93;status**: RECRUITING                                                                |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;69&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;69&#93;status**: RECRUITING                                                                |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;122&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;122&#93;status**: RECRUITING                                                               |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;139&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;139&#93;status**: RECRUITING                                                               |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;143&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;143&#93;status**: RECRUITING                                                               |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;148&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;148&#93;status**: RECRUITING                                                               |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;153&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;153&#93;status**: RECRUITING                                                               |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;155&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;155&#93;status**: RECRUITING                                                               |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;157&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;157&#93;status**: RECRUITING                                                               |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;160&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;160&#93;status**: RECRUITING                                                               |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;165&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;165&#93;status**: RECRUITING                                                               |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;224&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;224&#93;status**: RECRUITING                                                               |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;272&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;272&#93;status**: RECRUITING                                                               |
| 2026-03-03 00&#58;59&#58;14 | **contactsLocationsModule.locations.&#91;273&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;273&#93;status**: RECRUITING                                                               |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;197&#93;city**: Napoli               | **contactsLocationsModule.locations.&#91;197&#93;city**: Naples                                                                     |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;197&#93;geoPoint.lat**: 40.87618     | **contactsLocationsModule.locations.&#91;197&#93;geoPoint.lat**: 40.85216                                                           |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;197&#93;geoPoint.lon**: 14.5195      | **contactsLocationsModule.locations.&#91;197&#93;geoPoint.lon**: 14.26811                                                           |
| 2026-05-26 02&#58;38&#58;42 | **statusModule.statusVerifiedDate**: 2026-02                                  | **statusModule.statusVerifiedDate**: 2026-05                                                                                        |
| 2026-05-26 02&#58;38&#58;42 | **statusModule.lastUpdateSubmitDate**: 2026-02-27                             | **statusModule.lastUpdateSubmitDate**: 2026-05-13                                                                                   |
| 2026-05-26 02&#58;38&#58;42 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-02                    | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-14                                                                          |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;0&#93;status**: NOT_YET_RECRUITING   | **contactsLocationsModule.locations.&#91;0&#93;status**: RECRUITING                                                                 |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;5&#93;status**: NOT_YET_RECRUITING   | **contactsLocationsModule.locations.&#91;5&#93;status**: RECRUITING                                                                 |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;19&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;19&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;35&#93;city**: Rosario               | **contactsLocationsModule.locations.&#91;35&#93;city**: Renton                                                                      |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;35&#93;zip**: S2000CVB               | **contactsLocationsModule.locations.&#91;35&#93;zip**: 98055                                                                        |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;35&#93;country**: Argentina          | **contactsLocationsModule.locations.&#91;35&#93;country**: United States                                                            |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;35&#93;geoPoint.lat**: -32.94682     | **contactsLocationsModule.locations.&#91;35&#93;geoPoint.lat**: 47.48288                                                            |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;35&#93;geoPoint.lon**: -60.63932     | **contactsLocationsModule.locations.&#91;35&#93;geoPoint.lon**: -122.21707                                                          |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;29&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;29&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;32&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;32&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;36&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;36&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;45&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;45&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;47&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;47&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;48&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;48&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;49&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;49&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;50&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;50&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;51&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;51&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;52&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;52&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;55&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;55&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;57&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;57&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;57&#93;city**: São Paulo             | **contactsLocationsModule.locations.&#91;57&#93;city**: Santo André                                                                 |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;57&#93;zip**: 03102-006              | **contactsLocationsModule.locations.&#91;57&#93;zip**: 09060-650                                                                    |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;57&#93;geoPoint.lat**: -23.5475      | **contactsLocationsModule.locations.&#91;57&#93;geoPoint.lat**: -23.66389                                                           |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;57&#93;geoPoint.lon**: -46.63611     | **contactsLocationsModule.locations.&#91;57&#93;geoPoint.lon**: -46.53833                                                           |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;56&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;56&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;66&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;66&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;70&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;70&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;76&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;76&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;100&#93;city**: Liuchow              | **contactsLocationsModule.locations.&#91;100&#93;city**: Liuzhou                                                                    |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;126&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;126&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;128&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;128&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;129&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;129&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;131&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;131&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;132&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;132&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;133&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;133&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;134&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;134&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;135&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;135&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;136&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;136&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;142&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;142&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;146&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;146&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;150&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;150&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;152&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;152&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;155&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;155&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;157&#93;city**: Mainz                | **contactsLocationsModule.locations.&#91;157&#93;city**: Remscheid                                                                  |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;157&#93;zip**: 55131                 | **contactsLocationsModule.locations.&#91;157&#93;zip**: 42859                                                                       |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;157&#93;geoPoint.lat**: 49.98185     | **contactsLocationsModule.locations.&#91;157&#93;geoPoint.lat**: 51.17983                                                           |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;157&#93;geoPoint.lon**: 8.28008      | **contactsLocationsModule.locations.&#91;157&#93;geoPoint.lon**: 7.1925                                                             |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;165&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;165&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;168&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;168&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;169&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;169&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;171&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;171&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;179&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;179&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;186&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;186&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;192&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;192&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;193&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;193&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;194&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;194&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;195&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;195&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;197&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;197&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;198&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;198&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;199&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;199&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;200&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;200&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;201&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;201&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;202&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;202&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;203&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;203&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;236&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;236&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;237&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;237&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;257&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;257&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;283&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;283&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;285&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;285&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;286&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;286&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | **contactsLocationsModule.locations.&#91;287&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;287&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;42 | -                                                                             | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;35&#93;&#91;&#x27;state&#x27;&#93;** (Added) |
