---
title: "NCT03563716 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|:----------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2025-12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.completionDateStruct.date**: 2025-11-24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.completionDateStruct.date**: 2025-11-14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2025-12-30                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.lastUpdateSubmitDate**: 2026-04-13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-04                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;39&#93;city**: Taoyuan District                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;39&#93;city**: Taoyuan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lat**: 24.9896                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lat**: 24.99368                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lon**: 121.3187                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;39&#93;geoPoint.lon**: 121.29696                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.primaryOutcomes.&#91;0&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Objective Response Rate (ORR)&#x27;, &#x27;description&#x27;&#58; &#x27;ORR, defined as a complete response (CR) or partial response (PR) on two consecutive occasions &#92;&#92;&gt;/&#61;4 weeks apart, as determined by the investigator according to RECIST v1.1. CR&#58; Disappearance of all target lesions. PR&#58; At least a 30% decrease in the sum of diameters of all target lesions, taking as reference the baseline sum of diameters, in the absence of CR.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From baseline until a total of 80 progression free survival (PFS) events have occurred (up to approximately 11 months)&#x27;&#125;                                                                                                                     | **outcomesModule.primaryOutcomes.&#91;0&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Objective Response Rate (ORR)&#x27;, &#x27;description&#x27;&#58; &#x27;ORR was defined as a complete response (CR) or partial response (PR) on two consecutive occasions ≥ 4 weeks apart, as determined by the investigator according to RECIST v1.1. CR was defined as disappearance of all target and non-target lesions and normalization of tumor marker levels. Any pathological lymph nodes (whether target or non-target lesions) must have a reduction in short axis to &#92;&#92;&lt;10 millimeters (mm). PR was defined as at least a 30% decrease in the sum of diameters (SOD) of all target lesions, taking as reference the baseline SOD, in the absence of CR. Percentages have been rounded off.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From baseline until a total of 80 progression-free survival (PFS) events have occurred (up to approximately 11 months)&#x27;&#125;                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;5&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Percentage of Participants With Treatment-Emergent Anti-Drug Antibodies (ADAs)&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Cycle 1 Day 1, Cycle 2 Day 1, Cycle 4 Day 1, Cycle 12 Day 1 (each cycle is 21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | **outcomesModule.secondaryOutcomes.&#91;5&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Number of Participants With Treatment-Emergent Anti-drug Antibodies (ADAs) to Tiragolumab&#x27;, &#x27;description&#x27;&#58; &#x27;Participants who received tiragolumab were considered to be treatment-emergent ADA-positive if they were ADA-negative or had missing data at baseline but developed an ADA response following tiragolumab exposure (treatment-induced ADA response), or if they were ADA-positive at baseline and the titer of one or more post-baseline samples was at least 0.60 titer units (t.u.) greater than the titer of the baseline sample (treatment-enhanced ADA response). Participants with a positive post-baseline sample has been reported here.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to approximately 36 months&#x27;&#125;                                                                                                                                                                                                                                                                                         |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Percentage of Participants With Adverse Events&#x27;, &#x27;description&#x27;&#58; &#x27;An adverse event is any untoward medical occurrence in a subject administered a pharmaceutical product and which does not necessarily have to have a causal relationship with the treatment. An adverse event can therefore be any unfavorable and unintended sign (including an abnormal laboratory finding, for example), symptom, or disease temporally associated with the use of a pharmaceutical product, whether or not considered related to the pharmaceutical product. Preexisting conditions which worsen during a study are also considered as adverse events.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to 6 years&#x27;&#125;                                   | **outcomesModule.secondaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Number of Participants With Adverse Events (AEs)&#x27;, &#x27;description&#x27;&#58; &#x27;An AE was any untoward medical occurrence in a clinical investigation participant administered a pharmaceutical product, regardless of causal attribution. An AE can therefore be any unfavorable and unintended sign (including an abnormal laboratory finding), symptom, or disease temporally associated with the use of a medicinal product, whether or not considered related to the medicinal product.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From initiation of study drug up to approximately 83.7 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Overall Survival (OS)&#x27;, &#x27;description&#x27;&#58; &#x27;OS, defined as the time from randomization to death from any cause.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to 6 years&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | **outcomesModule.secondaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Overall Survival (OS)&#x27;, &#x27;description&#x27;&#58; &#x27;OS was defined as the time from randomization to death from any cause. KM methodology was used to estimate the median OS.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to approximately 36 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.primaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Progression Free Survival (PFS)&#x27;, &#x27;description&#x27;&#58; &#x27;PFS, defined as the time from randomization to the first occurrence of disease progression (PD), as determined by the investigator according to RECIST v1.1, or death from any cause, whichever occurs first. PD&#58; At least a 20% increase in the sum of diameters of target lesions, taking as reference the smallest sum of diameters at prior timepoints (including baseline).&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From baseline until a total of 80 PFS events have occurred (up to approximately 11 months)&#x27;&#125;                                                                                                                                                             | **outcomesModule.primaryOutcomes.&#91;1&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Progression-free Survival (PFS)&#x27;, &#x27;description&#x27;&#58; &#x27;PFS was defined as the time from randomization to the first occurrence of PD, as determined by the investigator according to RECIST v1.1, or death from any cause, whichever occurred first. PD was defined as at least a 20% increase in the SOD of target lesions, taking as reference the smallest SOD at prior timepoints (including baseline) or unequivocal progression of existing non-target lesions. In addition to the relative increase of 20%, the SOD must also demonstrate an absolute increase of ≥5 mm. Kaplan-Meier (KM) methodology was used to estimate the median PFS.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From baseline until a total of 80 PFS events have occurred (up to approximately 11 months)&#x27;&#125;                                                                                                                                                                                                                                              |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;3&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Serum Concentrations of Tiragolumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Cycle 1 Day 1, Cycle 2 Day 1, Cycle 4 Day 1, Cycle 12 Day 1 (each cycle is 21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **outcomesModule.secondaryOutcomes.&#91;3&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Minimum Serum Concentration (Cmin) of Tiragolumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Predose on Day 1 of Cycles 1, 3 and 11 (Cycle length &#61; 21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;0&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Duration of Objective Response (DOR)&#x27;, &#x27;description&#x27;&#58; &#x27;DOR, defined as the time from the first occurrence of a documented objective response (CR or PR) to disease progression (PD), as determined by the investigator according to RECIST v1.1, or death from any cause, whichever occurs first. CR&#58; Disappearance of all target lesions. PR&#58; At least a 30% decrease in the sum of diameters of all target lesions, taking as reference the baseline sum of diameters, in the absence of CR. PD&#58; At least a 20% increase in the sum of diameters of target lesions, taking as reference the smallest sum of diameters at prior timepoints (including baseline).&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to 6 years&#x27;&#125; | **outcomesModule.secondaryOutcomes.&#91;0&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Duration of Objective Response (DOR)&#x27;, &#x27;description&#x27;&#58; &#x27;DOR was defined as the time from the first occurrence of a documented objective response (OR) (CR or PR) to PD, as determined by the investigator according to RECIST v1.1, or death from any cause, whichever occurred first. CR was defined as the disappearance of all target and non-target lesions and normalization of tumor marker levels. Any pathological lymph nodes (whether target or non-target lesions) must have a reduction in short axis to &#92;&#92;&lt;10 mm. PR was defined as at least a 30% decrease in the SOD of all target lesions, taking as reference the baseline SOD, in the absence of CR. PD was defined as at least a 20% increase in the SOD of target lesions, taking as reference the smallest SOD at prior timepoints (including baseline) or unequivocal progression of existing non-target lesions. In addition to the relative increase of 20%, the SOD must also demonstrate an absolute increase of ≥5 mm. KM methodology was used to |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;4&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Serum Concentrations of Atezolizumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Cycle 1 Day 1, Cycle 2 Day 1, Cycle 4 Day 1, Cycle 12 Day 1 (each cycle is 21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **outcomesModule.secondaryOutcomes.&#91;4&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Cmin of Atezolizumab&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Predose on Day 1 of Cycles 1, 3 and 11 (Cycle length &#61; 21 days)&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
