---
title: "NCT04693234 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|:----------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;30&#93;geoPoint.lat**: 26.82656                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | **contactsLocationsModule.locations.&#91;30&#93;geoPoint.lat**: 40.28464                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;30&#93;geoPoint.lon**: 114.95747                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | **contactsLocationsModule.locations.&#91;30&#93;geoPoint.lon**: 120.48412                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-05-26 02&#58;38&#58;40 | **referencesModule.references.&#91;0&#93;**: &#123;&#x27;pmid&#x27;&#58; &#x27;40411966&#x27;, &#x27;type&#x27;&#58; &#x27;BACKGROUND&#x27;, &#x27;citation&#x27;&#58; &#x27;Lee JY, Boonyapipat S, Yuan G, Kim HS, Lee JW, Wang L, Wang T, Wang D, Yao D, Liu H, Chang CL, Andabekov TT, Zhang X, Wang W, Kim YM, Sinielnikov IV, Wang K, Gao Y, Mu X, Wu L. AdvanTIG-202&#58; Phase 2 open-label, two-cohort multicenter study of ociperlimab plus tislelizumab and tislelizumab alone in patients with previously treated recurrent or metastatic cervical cancer. Gynecol Oncol. 2025 Jul;198&#58;25-32. doi&#58; 10.1016/j.ygyno.2025.04.579. Epub 2025 May 23.&#x27;&#125; | **referencesModule.references.&#91;0&#93;**: &#123;&#x27;type&#x27;&#58; &#x27;BACKGROUND&#x27;, &#x27;citation&#x27;&#58; &#x27;Wu L, Wang PH, Hsiao SY, et al. AdvanTIG-202&#58; A phase 2 study investigating anti-T cell immunoglobulin and ITIM domain monoclonal antibody ociperlimab plus tislelizumab in patients with previously treated recurrent or metastatic cervical cancer (333). Gynecol Oncol. 2022;166&#58;S172. doi&#58;10.1016/S0090-8258(22)01555-4&#x27;&#125; |
| 2026-06-06 03&#58;35&#58;40 | **contactsLocationsModule.locations.&#91;17&#93;city**: Jilin                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | **contactsLocationsModule.locations.&#91;17&#93;city**: Jilin City                                                                                                                                                                                                                                                                                                                                                                                                                   |
