---
title: "NCT06819735 Change History"
---

| Timestamp                   | Before                                                                      | After                                                               |
|:----------------------------|:----------------------------------------------------------------------------|:--------------------------------------------------------------------|
| 2026-03-11 02&#58;05&#58;41 | **statusModule.statusVerifiedDate**: 2025-11                                | **statusModule.statusVerifiedDate**: 2026-03                        |
| 2026-03-11 02&#58;05&#58;41 | **statusModule.lastUpdateSubmitDate**: 2025-11-14                           | **statusModule.lastUpdateSubmitDate**: 2026-03-06                   |
| 2026-03-11 02&#58;05&#58;41 | **statusModule.lastUpdatePostDateStruct.date**: 2025-11-18                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-10          |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.statusVerifiedDate**: 2026-03                                | **statusModule.statusVerifiedDate**: 2026-05                        |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.lastUpdateSubmitDate**: 2026-03-06                           | **statusModule.lastUpdateSubmitDate**: 2026-05-04                   |
| 2026-05-26 02&#58;38&#58;39 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-10                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-06          |
| 2026-05-26 02&#58;38&#58;39 | **oversightModule.isFdaRegulatedDrug**: False                               | **oversightModule.isFdaRegulatedDrug**: True                        |
| 2026-05-26 02&#58;38&#58;39 | **contactsLocationsModule.locations.&#91;5&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;5&#93;status**: RECRUITING |
