---
title: "NCT06713798 Change History"
---

| Timestamp                   | Before                                                          | After                                                                              |
|:----------------------------|:----------------------------------------------------------------|:-----------------------------------------------------------------------------------|
| 2026-03-24 02&#58;11&#58;00 | **statusModule.statusVerifiedDate**: 2025-06                    | **statusModule.statusVerifiedDate**: 2026-03                                       |
| 2026-03-24 02&#58;11&#58;00 | **statusModule.overallStatus**: NOT_YET_RECRUITING              | **statusModule.overallStatus**: WITHDRAWN                                          |
| 2026-03-24 02&#58;11&#58;00 | **statusModule.startDateStruct.date**: 2025-07                  | **statusModule.startDateStruct.date**: 2025-01-30                                  |
| 2026-03-24 02&#58;11&#58;00 | **statusModule.startDateStruct.type**: ESTIMATED                | **statusModule.startDateStruct.type**: ACTUAL                                      |
| 2026-03-24 02&#58;11&#58;00 | **statusModule.primaryCompletionDateStruct.date**: 2028-01      | **statusModule.primaryCompletionDateStruct.date**: 2025-09-15                      |
| 2026-03-24 02&#58;11&#58;00 | **statusModule.primaryCompletionDateStruct.type**: ESTIMATED    | **statusModule.primaryCompletionDateStruct.type**: ACTUAL                          |
| 2026-03-24 02&#58;11&#58;00 | **statusModule.completionDateStruct.date**: 2030-01             | **statusModule.completionDateStruct.date**: 2025-09-15                             |
| 2026-03-24 02&#58;11&#58;00 | **statusModule.completionDateStruct.type**: ESTIMATED           | **statusModule.completionDateStruct.type**: ACTUAL                                 |
| 2026-03-24 02&#58;11&#58;00 | **statusModule.lastUpdateSubmitDate**: 2025-06-23               | **statusModule.lastUpdateSubmitDate**: 2026-03-19                                  |
| 2026-03-24 02&#58;11&#58;00 | **statusModule.lastUpdatePostDateStruct.date**: 2025-06-24      | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-23                         |
| 2026-03-24 02&#58;11&#58;00 | **designModule.enrollmentInfo.count**: 115                      | **designModule.enrollmentInfo.count**: 0                                           |
| 2026-03-24 02&#58;11&#58;00 | **designModule.enrollmentInfo.type**: ESTIMATED                 | **designModule.enrollmentInfo.type**: ACTUAL                                       |
| 2026-03-24 02&#58;11&#58;00 | -                                                               | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;whyStopped&#x27;&#93;** (Added) |
| 2026-03-24 02&#58;11&#58;00 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;** (Removed) | -                                                                                  |
