---
title: "NCT06911827 Change History"
---

| Timestamp                   | Before                                                     | After                                                                                        |
|:----------------------------|:-----------------------------------------------------------|:---------------------------------------------------------------------------------------------|
| 2026-02-26 00&#58;55&#58;48 | **statusModule.statusVerifiedDate**: 2025-03               | **statusModule.statusVerifiedDate**: 2026-02                                                 |
| 2026-02-26 00&#58;55&#58;48 | **statusModule.overallStatus**: NOT_YET_RECRUITING         | **statusModule.overallStatus**: RECRUITING                                                   |
| 2026-02-26 00&#58;55&#58;48 | **statusModule.startDateStruct.date**: 2025-04             | **statusModule.startDateStruct.date**: 2025-05-09                                            |
| 2026-02-26 00&#58;55&#58;48 | **statusModule.startDateStruct.type**: ESTIMATED           | **statusModule.startDateStruct.type**: ACTUAL                                                |
| 2026-02-26 00&#58;55&#58;48 | **statusModule.lastUpdateSubmitDate**: 2025-04-07          | **statusModule.lastUpdateSubmitDate**: 2026-02-24                                            |
| 2026-02-26 00&#58;55&#58;48 | **statusModule.lastUpdatePostDateStruct.date**: 2025-04-09 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-25                                   |
| 2026-02-26 00&#58;55&#58;48 | -                                                          | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;** (Added) |
| 2026-04-08 02&#58;33&#58;18 | **statusModule.statusVerifiedDate**: 2026-02               | **statusModule.statusVerifiedDate**: 2026-04                                                 |
| 2026-04-08 02&#58;33&#58;18 | **statusModule.lastUpdateSubmitDate**: 2026-02-24          | **statusModule.lastUpdateSubmitDate**: 2026-04-01                                            |
| 2026-04-08 02&#58;33&#58;18 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-25 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-07                                   |
| 2026-04-08 02&#58;33&#58;18 | **designModule.enrollmentInfo.count**: 90                  | **designModule.enrollmentInfo.count**: 149                                                   |
