---
title: "NCT07011550 Change History"
---

| Timestamp                   | Before                                                                                                                                  | After                                                                              |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------|
| 2026-02-20 00&#58;56&#58;09 | **statusModule.statusVerifiedDate**: 2025-08                                                                                            | **statusModule.statusVerifiedDate**: 2026-02                                       |
| 2026-02-20 00&#58;56&#58;09 | **statusModule.overallStatus**: RECRUITING                                                                                              | **statusModule.overallStatus**: SUSPENDED                                          |
| 2026-02-20 00&#58;56&#58;09 | **statusModule.startDateStruct.date**: 2025-11-30                                                                                       | **statusModule.startDateStruct.date**: 2025-08-15                                  |
| 2026-02-20 00&#58;56&#58;09 | **statusModule.startDateStruct.type**: ESTIMATED                                                                                        | **statusModule.startDateStruct.type**: ACTUAL                                      |
| 2026-02-20 00&#58;56&#58;09 | **statusModule.lastUpdateSubmitDate**: 2025-08-20                                                                                       | **statusModule.lastUpdateSubmitDate**: 2026-02-17                                  |
| 2026-02-20 00&#58;56&#58;09 | **statusModule.lastUpdatePostDateStruct.date**: 2025-08-27                                                                              | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-19                         |
| 2026-02-20 00&#58;56&#58;09 | **designModule.enrollmentInfo.count**: 40                                                                                               | **designModule.enrollmentInfo.count**: 7                                           |
| 2026-02-20 00&#58;56&#58;09 | **designModule.enrollmentInfo.type**: ESTIMATED                                                                                         | **designModule.enrollmentInfo.type**: ACTUAL                                       |
| 2026-02-20 00&#58;56&#58;09 | -                                                                                                                                       | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;whyStopped&#x27;&#93;** (Added) |
| 2026-02-20 00&#58;56&#58;09 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;centralContacts&#x27;&#93;** (Removed)                                    | -                                                                                  |
| 2026-02-20 00&#58;56&#58;09 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;status&#x27;&#93;** (Removed)   | -                                                                                  |
| 2026-02-20 00&#58;56&#58;09 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed) | -                                                                                  |
| 2026-02-25 01&#58;02&#58;23 | **statusModule.lastUpdateSubmitDate**: 2026-02-17                                                                                       | **statusModule.lastUpdateSubmitDate**: 2026-02-20                                  |
| 2026-02-25 01&#58;02&#58;23 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-19                                                                              | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-24                         |
| 2026-02-25 01&#58;02&#58;23 | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;expandedAccessInfo&#x27;&#93;** (Removed)                                            | -                                                                                  |
| 2026-03-12 02&#58;11&#58;52 | **statusModule.statusVerifiedDate**: 2026-02                                                                                            | **statusModule.statusVerifiedDate**: 2026-03                                       |
| 2026-03-12 02&#58;11&#58;52 | **statusModule.lastUpdateSubmitDate**: 2026-02-20                                                                                       | **statusModule.lastUpdateSubmitDate**: 2026-03-10                                  |
| 2026-03-12 02&#58;11&#58;52 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-24                                                                              | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-11                         |
| 2026-03-21 02&#58;05&#58;09 | **statusModule.whyStopped**: FDA                                                                                                        | **statusModule.whyStopped**: PI Request                                            |
| 2026-03-21 02&#58;05&#58;09 | **statusModule.lastUpdateSubmitDate**: 2026-03-10                                                                                       | **statusModule.lastUpdateSubmitDate**: 2026-03-17                                  |
| 2026-03-21 02&#58;05&#58;09 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-11                                                                              | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-20                         |
