---
title: "NCT05130177 Change History"
---

| Timestamp                   | Before                                                                                                                                  | After                                                         |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------|
| 2026-04-01 02&#58;42&#58;41 | **statusModule.statusVerifiedDate**: 2025-05                                                                                            | **statusModule.statusVerifiedDate**: 2026-03                  |
| 2026-04-01 02&#58;42&#58;41 | **statusModule.overallStatus**: RECRUITING                                                                                              | **statusModule.overallStatus**: ACTIVE_NOT_RECRUITING         |
| 2026-04-01 02&#58;42&#58;41 | **statusModule.primaryCompletionDateStruct.date**: 2028-01                                                                              | **statusModule.primaryCompletionDateStruct.date**: 2026-02-06 |
| 2026-04-01 02&#58;42&#58;41 | **statusModule.primaryCompletionDateStruct.type**: ESTIMATED                                                                            | **statusModule.primaryCompletionDateStruct.type**: ACTUAL     |
| 2026-04-01 02&#58;42&#58;41 | **statusModule.completionDateStruct.date**: 2031-01                                                                                     | **statusModule.completionDateStruct.date**: 2030-01-31        |
| 2026-04-01 02&#58;42&#58;41 | **statusModule.lastUpdateSubmitDate**: 2025-05-02                                                                                       | **statusModule.lastUpdateSubmitDate**: 2026-03-25             |
| 2026-04-01 02&#58;42&#58;41 | **statusModule.lastUpdatePostDateStruct.date**: 2025-05-07                                                                              | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-31    |
| 2026-04-01 02&#58;42&#58;41 | **designModule.enrollmentInfo.count**: 26                                                                                               | **designModule.enrollmentInfo.count**: 8                      |
| 2026-04-01 02&#58;42&#58;41 | **designModule.enrollmentInfo.type**: ESTIMATED                                                                                         | **designModule.enrollmentInfo.type**: ACTUAL                  |
| 2026-04-01 02&#58;42&#58;41 | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;expandedAccessInfo&#x27;&#93;** (Removed)                                            | -                                                             |
| 2026-04-01 02&#58;42&#58;41 | **root&#91;&#x27;oversightModule&#x27;&#93;&#91;&#x27;isUsExport&#x27;&#93;** (Removed)                                                 | -                                                             |
| 2026-04-01 02&#58;42&#58;41 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;centralContacts&#x27;&#93;** (Removed)                                    | -                                                             |
| 2026-04-01 02&#58;42&#58;41 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;status&#x27;&#93;** (Removed)   | -                                                             |
| 2026-04-01 02&#58;42&#58;41 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed) | -                                                             |
