---
title: "NCT04262856 Change History"
---

| Timestamp                   | Before                                                                   | After                                                                                           |
|:----------------------------|:-------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------|
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;43&#93;city**: Taoyuan District | **contactsLocationsModule.locations.&#91;43&#93;city**: Taoyuan                                 |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lat**: 24.9896  | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lat**: 24.99368                        |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lon**: 121.3187 | **contactsLocationsModule.locations.&#91;43&#93;geoPoint.lon**: 121.29696                       |
| 2026-06-11 04&#58;04&#58;07 | **statusModule.primaryCompletionDateStruct.date**: 2025-06-05            | **statusModule.primaryCompletionDateStruct.date**: 2025-07-09                                   |
| 2026-06-11 04&#58;04&#58;07 | **statusModule.lastUpdateSubmitDate**: 2025-08-25                        | **statusModule.lastUpdateSubmitDate**: 2026-06-09                                               |
| 2026-06-11 04&#58;04&#58;07 | **statusModule.lastUpdatePostDateStruct.date**: 2025-08-26               | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-10                                      |
| 2026-06-13 03&#58;52&#58;39 | -                                                                        | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;dispFirstSubmitDate&#x27;&#93;** (Added)     |
| 2026-06-16 04&#58;16&#58;42 | **statusModule.lastUpdateSubmitDate**: 2026-06-09                        | **statusModule.lastUpdateSubmitDate**: 2026-06-11                                               |
| 2026-06-16 04&#58;16&#58;42 | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-10               | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-15                                      |
| 2026-06-16 04&#58;16&#58;42 | -                                                                        | **root&#91;&#x27;statusModule&#x27;&#93;&#91;&#x27;dispFirstPostDateStruct&#x27;&#93;** (Added) |
