---
title: "NCT04746924 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-05-26 02&#58;38&#58;40 | **identificationModule.organization.fullName**: BeiGene                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | **identificationModule.organization.fullName**: BeOne Medicines                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2025-06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.overallStatus**: ACTIVE_NOT_RECRUITING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.overallStatus**: TERMINATED                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.startDateStruct.date**: 2021-06-08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.startDateStruct.date**: 2021-05-24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.completionDateStruct.date**: 2026-03-31                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | **statusModule.completionDateStruct.date**: 2026-03-18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.completionDateStruct.type**: ESTIMATED                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | **statusModule.completionDateStruct.type**: ACTUAL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2025-06-23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-04-20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2025-06-24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-05-26 02&#58;38&#58;40 | **descriptionModule.briefSummary**: The purpose of this study is to evaluate the efficacy and safety of ociperlimab + tislelizumab compared with that of pembrolizumab in adults with PD-L1 high, locally advanced/recurrent or untreated metastatic NSCLC.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **descriptionModule.briefSummary**: The purpose of this study is to evaluate the efficacy and safety of ociperlimab + tislelizumab compared with that of pembrolizumab in adults with high levels of programmed cell death ligand-1 (PD-L1), locally advanced/recurrent or untreated metastatic non-small cell lung cancer (NSCLC).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **designModule.enrollmentInfo.count**: 662                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | **designModule.enrollmentInfo.count**: 669                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Key Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 1. Histologically or cytologically documented locally advanced or recurrent non-small cell lung cancer (NSCLC) that is not eligible for curative surgery and/or definitive radiotherapy with or without chemoradiotherapy, or metastatic-nonsquamous or squamous NSCLC.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 2. No prior systemic treatment for metastatic NSCLC.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 3. Agreement to provide archival tissue or fresh biopsy (if archival tissue is not available).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 4. Tumors with PD-L1 expressed in ≥ 50% tumor cells.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 5. At least 1 measurable lesion as defined per RECIST v1.1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 6. ECOG Performance Status ≤ 1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Key Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 1. Known mutations in the epidermal growth factor receptor (EGFR) gene, anaplastic lymphoma kinase (ALK) fusion oncogene, BRAF V600E, or ROS1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 2. Prior therapy with an anti-programmed cell death protein (anti-PD)-1, anti-PD-ligand (L)-1, anti-PD-ligand-2, anti-T-cell immunoglobulin and ITIM (anti-TIGIT) domain, or any other antibody or drug specifically targeting T-cell costimulation or ch&#96; to &#96;Key Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 1. Histologically or cytologically documented locally advanced or recurrent non-small cell lung cancer (NSCLC) that is not eligible for curative surgery and/or definitive radiotherapy with or without chemoradiotherapy, or metastatic-nonsquamous or squamous NSCLC.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 2. No prior systemic treatment for metastatic NSCLC.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 3. Agreement to provide archival tissue or fresh biopsy (if archival tissue is not available).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 4. Tumors with PD-L1 expressed in ≥ 50% tumor cells.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 5. At least 1 measurable lesion as defined per Response Evaluation Criteria in Solid Tumors (RECIST) v1.1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 6. Eastern Cooperative Oncology Group (ECOG) Performance Status ≤ 1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Key Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 1. Known mutations in the epidermal growth factor receptor (EGFR) gene, anaplastic lymphoma kinase (ALK) fusion oncogene, BRAF V600E, or ROS1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 2. Prior therapy with an anti-programmed cell death protein (anti-PD)-1, anti-PD-ligand (L)-1, anti-PD-ligand-2, anti-T-cell immunoglobulin and ITIM (anti-TIGIT) dom&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;194&#93;city**: Taoyuan District                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | **contactsLocationsModule.locations.&#91;194&#93;city**: Taoyuan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;194&#93;geoPoint.lat**: 24.9896                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;194&#93;geoPoint.lat**: 24.99368                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;40 | **contactsLocationsModule.locations.&#91;194&#93;geoPoint.lon**: 121.3187                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | **contactsLocationsModule.locations.&#91;194&#93;geoPoint.lon**: 121.29696                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-05-26 02&#58;38&#58;40 | **ipdSharingStatementModule**: &#123;&#x27;ipdSharing&#x27;&#58; &#x27;YES&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | **ipdSharingStatementModule**: &#123;&#x27;ipdSharing&#x27;&#58; &#x27;YES&#x27;, &#x27;description&#x27;&#58; &#x27;BeiGene shares data on completed studies responsibly and provides qualified scientific and medical researchers access to data and supporting documentation for clinical trials in dossiers for medicines and indications after submission and approval in the United States, China, and Europe. Clinical trials supporting subsequent local approvals, new indications, or combination products are eligible for sharing once corresponding regulatory approvals are achieved.&#92;n&#92;nBeiGene shares data only when permitted by applicable data privacy and security laws and regulations, when it is feasible to do so without compromising the privacy of study participants, and other considerations.&#92;n&#92;nQualified researchers with appropriate competencies who are engaged in novel scientific research may submit a request for participant-level data with a research proposal for BeiGene review. Research teams must include a biostatistician and sign a Data Sharing Agreement prior to r                                                                                                                                                                                                                                                                  |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.primaryOutcomes.&#91;0&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Overall Survival (OS)&#x27;, &#x27;description&#x27;&#58; &#x27;OS will be defined as the time from the date of randomization to the date of death due to any cause.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to approximately 58 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **outcomesModule.primaryOutcomes.&#91;0&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Overall Survival (OS) in Arms A and B&#x27;, &#x27;description&#x27;&#58; &#x27;OS is defined as the time from the date of randomization to the date of death due to any cause. Median OS was estimated using the Kaplan-Meier method. OS was a pre-specified primary endpoint for Arms A and B only.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;From randomization until the end of the study. Maximum time on study was 45.0 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-05-26 02&#58;38&#58;40 | **armsInterventionsModule.interventions.&#91;1&#93;armGroupLabels.&#91;0&#93;**: Arm A&#58; Tislelizumab plus Ociperlimab                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | **armsInterventionsModule.interventions.&#91;1&#93;armGroupLabels.&#91;0&#93;**: Arm A&#58; Ociperlimab plus Tislelizumab                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;5&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;HRQoL&#58; European Quality of Life-5 Level- 5 Dimension (EQ-5D-5L) Questionnaire&#x27;, &#x27;description&#x27;&#58; &#x27;HRQoL will be assessed via PRO using the EQ-5D-5L. The EQ-5D-5L comprises five dimensions&#58; mobility, self-care, usual activities, pain/discomfort and anxiety/depression, and a visual analog scale (VAS). Each dimension has 5 levels&#58; no problems, slight problems, moderate problems, severe problems, and extreme problems. The VAS records the respondent&#92;&#x27;s self-rated health on a 0 to 100 scale, with 100 &#61; &quot;the best health you can imagine&quot; and 0 &#61; &quot;&#92;&#x27;the worst health you can imagine&quot;. Lower scores in descriptive dimension indicate better HRQoL and higher VAS scores indicates better health state.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Within 7 days after permanent treatment discontinuation&#x27;&#125; | **outcomesModule.secondaryOutcomes.&#91;5&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Duration Of Response (DOR) for Safety Run-In Substudy As Assessed By the Investigator&#x27;, &#x27;description&#x27;&#58; &#x27;DOR is defined as the time from the first determination of an objective response per RECIST v1.1 until the first documentation of progression or death, whichever occurs first. Median DOR was estimated using the Kaplan-Meier method.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to 38.9 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-05-26 02&#58;38&#58;40 | **armsInterventionsModule.armGroups.&#91;1&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Arm B&#58; Pembrolizumab plus Placebo&#x27;, &#x27;type&#x27;&#58; &#x27;ACTIVE_COMPARATOR&#x27;, &#x27;description&#x27;&#58; &#x27;Participants will receive pembrolizumab 200 mg intravenously followed by placebo intravenously once every 3 weeks.&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; Pembrolizumab&#x27;, &#x27;Drug&#58; Placebo&#x27;&#93;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | **armsInterventionsModule.armGroups.&#91;1&#93;**: &#123;&#x27;label&#x27;&#58; &#x27;Arm B&#58; Pembrolizumab plus Placebo&#x27;, &#x27;type&#x27;&#58; &#x27;ACTIVE_COMPARATOR&#x27;, &#x27;description&#x27;&#58; &#x27;Participants received pembrolizumab 200 mg and placebo intravenously every 3 weeks. Treatment continued until lack of benefit, unacceptable toxicity, or withdrawal for other reasons.&#x27;, &#x27;interventionNames&#x27;&#58; &#91;&#x27;Drug&#58; Pembrolizumab&#x27;, &#x27;Drug&#58; Placebo&#x27;&#93;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-05-26 02&#58;38&#58;40 | **armsInterventionsModule.interventions.&#91;0&#93;armGroupLabels.&#91;0&#93;**: Arm A&#58; Tislelizumab plus Ociperlimab                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | **armsInterventionsModule.interventions.&#91;0&#93;armGroupLabels.&#91;0&#93;**: Arm A&#58; Ociperlimab plus Tislelizumab                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;40 | **outcomesModule.secondaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Duration Of Response (DOR) As Assessed By Investigators&#x27;, &#x27;description&#x27;&#58; &#x27;DOR will be defined as the time from the first determination of an objective response per RECIST v1.1 until the first documentation of progression or death, whichever occurs first.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Up to approximately 58 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **outcomesModule.secondaryOutcomes.&#91;2&#93;**: &#123;&#x27;measure&#x27;&#58; &#x27;Overall Response Rate (ORR) for Arm A Versus Arm B As Assessed By the Investigator&#x27;, &#x27;description&#x27;&#58; &#x27;ORR is defined as the percentage of participants with a documented, confirmed complete response or partial response per RECIST v1.1. ORR was a pre-specified secondary endpoint for Arms A and B only.&#92;n&#92;nComplete response is defined as disappearance of all target lesions, disappearance of all nontarget lesions and normalization of tumor marker level, and no new lesions.&#92;n&#92;nPartial response is defined as at least a 30% decrease in the sum of diameters of target lesions, no unequivocal progression of non-target lesions, and no new lesions.&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;Response was assessed every 9 weeks from randomization for the first 52 weeks and then every 12 weeks thereafter, up to 45.0 months&#x27;&#125;                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-05-26 02&#58;38&#58;40 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Field &#96;outcomesModule.secondaryOutcomes.&#91;7&#93;&#96; changed from &#96;&#123;&#x27;measure&#x27;&#58; &#x27;Number Of Participants Experiencing Adverse Events (AEs)&#x27;, &#x27;description&#x27;&#58; &#x27;The incidence and severity of AEs will be determined according to National Cancer Institute Common Terminology Criteria for Adverse Events Version 5.0 (NCI CTCAE v5.0).&#x27;, &#x27;timeFrame&#x27;&#58; &#x27;90 days (±14) after last dose&#x27;&#125;&#96; to &#96;&#123;&#x27;measure&#x27;&#58; &#x27;Change From Baseline in EORTC Lung Cancer Module Quality of Life Questionnaire Lung Cancer 13 (QLQ-LC13) Index Score, Dyspnea, Coughing, Hemoptysis, Pain in Chest, Pain in Arms/Shoulders, and Peripheral Neuropathy Scores in Arms A and B&#x27;, &#x27;description&#x27;&#58; &#x27;The EORTC QLQ-LC13 is the lung cancer module of the QLQ-C30 and measures lung cancer-specific disease and treatment symptoms. It includes 13 questions about specific symptoms in which participants respond based on a 4-point scale, where 1 is &quot;not at all&quot; and 4 is &quot;very much&quot;. Raw scores are transformed into a 0 to 100 scale via linear transformation. The symptom index scale was calculated by taking the mean of all symptom scale scores, and ranges from 0 to 100. Lower scores indicate an improvement in symptoms.&#92;n&#92;nThis was a |
| 2026-07-28 00&#58;26&#58;05 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | **root&#91;&#x27;referencesModule&#x27;&#93;** (Added)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
