---
title: "NCT06996782 Change History"
---

| Timestamp                   | Before                                                                       | After                                                                     |
|:----------------------------|:-----------------------------------------------------------------------------|:--------------------------------------------------------------------------|
| 2026-02-25 01&#58;02&#58;25 | **statusModule.statusVerifiedDate**: 2026-01                                 | **statusModule.statusVerifiedDate**: 2026-02                              |
| 2026-02-25 01&#58;02&#58;25 | **statusModule.lastUpdateSubmitDate**: 2026-01-13                            | **statusModule.lastUpdateSubmitDate**: 2026-02-23                         |
| 2026-02-25 01&#58;02&#58;25 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-14                   | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-24                |
| 2026-02-25 01&#58;02&#58;25 | **contactsLocationsModule.locations.&#91;7&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;7&#93;status**: RECRUITING       |
| 2026-02-25 01&#58;02&#58;25 | **contactsLocationsModule.locations.&#91;8&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;8&#93;status**: WITHDRAWN        |
| 2026-02-25 01&#58;02&#58;25 | **contactsLocationsModule.locations.&#91;47&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;47&#93;status**: WITHDRAWN       |
| 2026-02-25 01&#58;02&#58;25 | **contactsLocationsModule.locations.&#91;79&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;79&#93;status**: RECRUITING      |
| 2026-03-31 02&#58;31&#58;37 | **statusModule.statusVerifiedDate**: 2026-02                                 | **statusModule.statusVerifiedDate**: 2026-03                              |
| 2026-03-31 02&#58;31&#58;37 | **statusModule.lastUpdateSubmitDate**: 2026-02-23                            | **statusModule.lastUpdateSubmitDate**: 2026-03-27                         |
| 2026-03-31 02&#58;31&#58;37 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-24                   | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-30                |
| 2026-03-31 02&#58;31&#58;37 | **contactsLocationsModule.locations.&#91;46&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;46&#93;status**: WITHDRAWN       |
| 2026-03-31 02&#58;31&#58;37 | **contactsLocationsModule.locations.&#91;55&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;55&#93;status**: RECRUITING      |
| 2026-03-31 02&#58;31&#58;37 | **contactsLocationsModule.locations.&#91;56&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;56&#93;status**: RECRUITING      |
| 2026-03-31 02&#58;31&#58;37 | **contactsLocationsModule.locations.&#91;58&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;58&#93;status**: RECRUITING      |
| 2026-03-31 02&#58;31&#58;37 | **contactsLocationsModule.locations.&#91;60&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;60&#93;status**: RECRUITING      |
| 2026-03-31 02&#58;31&#58;37 | **contactsLocationsModule.locations.&#91;62&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;62&#93;status**: RECRUITING      |
| 2026-03-31 02&#58;31&#58;37 | **contactsLocationsModule.locations.&#91;82&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;82&#93;status**: RECRUITING      |
| 2026-03-31 02&#58;31&#58;37 | **contactsLocationsModule.locations.&#91;97&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;97&#93;status**: RECRUITING      |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.statusVerifiedDate**: 2026-03                                 | **statusModule.statusVerifiedDate**: 2026-04                              |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.lastUpdateSubmitDate**: 2026-03-27                            | **statusModule.lastUpdateSubmitDate**: 2026-04-30                         |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-30                   | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-01                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;77&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;77&#93;status**: WITHDRAWN       |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;78&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;78&#93;status**: WITHDRAWN       |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;103&#93;geoPoint.lat**: 39.94548    | **contactsLocationsModule.locations.&#91;103&#93;geoPoint.lat**: 37.05738 |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;103&#93;geoPoint.lon**: 32.87302    | **contactsLocationsModule.locations.&#91;103&#93;geoPoint.lon**: 34.58903 |
| 2026-06-18 04&#58;04&#58;37 | **statusModule.statusVerifiedDate**: 2026-04                                 | **statusModule.statusVerifiedDate**: 2026-06                              |
| 2026-06-18 04&#58;04&#58;37 | **statusModule.lastUpdateSubmitDate**: 2026-04-30                            | **statusModule.lastUpdateSubmitDate**: 2026-06-16                         |
| 2026-06-18 04&#58;04&#58;37 | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-01                   | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-17                |
| 2026-06-18 04&#58;04&#58;37 | **contactsLocationsModule.locations.&#91;3&#93;status**: NOT_YET_RECRUITING  | **contactsLocationsModule.locations.&#91;3&#93;status**: RECRUITING       |
| 2026-06-18 04&#58;04&#58;37 | **contactsLocationsModule.locations.&#91;39&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;39&#93;status**: RECRUITING      |
| 2026-06-18 04&#58;04&#58;37 | **contactsLocationsModule.locations.&#91;42&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;42&#93;status**: RECRUITING      |
| 2026-06-18 04&#58;04&#58;37 | **contactsLocationsModule.locations.&#91;43&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;43&#93;status**: RECRUITING      |
| 2026-06-24 14&#58;19&#58;41 | **contactsLocationsModule.locations.&#91;101&#93;geoPoint.lat**: 37.05738    | **contactsLocationsModule.locations.&#91;101&#93;geoPoint.lat**: 41.0225  |
| 2026-06-24 14&#58;19&#58;41 | **contactsLocationsModule.locations.&#91;101&#93;geoPoint.lon**: 34.58903    | **contactsLocationsModule.locations.&#91;101&#93;geoPoint.lon**: 28.94083 |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.statusVerifiedDate**: 2026-06                                 | **statusModule.statusVerifiedDate**: 2026-07                              |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.lastUpdateSubmitDate**: 2026-06-16                            | **statusModule.lastUpdateSubmitDate**: 2026-07-20                         |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-17                   | **statusModule.lastUpdatePostDateStruct.date**: 2026-07-21                |
| 2026-07-28 00&#58;26&#58;05 | **contactsLocationsModule.locations.&#91;25&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;25&#93;status**: RECRUITING      |
| 2026-07-28 00&#58;26&#58;05 | **contactsLocationsModule.locations.&#91;26&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;26&#93;status**: RECRUITING      |
| 2026-07-28 00&#58;26&#58;05 | **contactsLocationsModule.locations.&#91;99&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;99&#93;status**: RECRUITING      |
