---
title: "NCT06989112 Change History"
---

| Timestamp                   | Before                                                                                                         | After                                                                                                                               |
|:----------------------------|:---------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-12 14&#58;01&#58;41 | **statusModule.statusVerifiedDate**: 2026-01                                                                   | **statusModule.statusVerifiedDate**: 2026-02                                                                                        |
| 2026-02-12 14&#58;01&#58;41 | **statusModule.lastUpdateSubmitDate**: 2026-01-14                                                              | **statusModule.lastUpdateSubmitDate**: 2026-02-09                                                                                   |
| 2026-02-12 14&#58;01&#58;41 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-15                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-10                                                                          |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;11&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;11&#93;status**: RECRUITING                                                                |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;46&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;46&#93;status**: RECRUITING                                                                |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;57&#93;zip**: 53705                                                   | **contactsLocationsModule.locations.&#91;57&#93;zip**: 53792                                                                        |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;70&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;70&#93;status**: RECRUITING                                                                |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;76&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;76&#93;status**: RECRUITING                                                                |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;78&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;78&#93;status**: RECRUITING                                                                |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;79&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;79&#93;status**: RECRUITING                                                                |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;121&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;121&#93;status**: RECRUITING                                                               |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;149&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;149&#93;status**: RECRUITING                                                               |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;182&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;182&#93;status**: RECRUITING                                                               |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;190&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;190&#93;status**: RECRUITING                                                               |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;223&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;223&#93;status**: RECRUITING                                                               |
| 2026-02-12 14&#58;01&#58;41 | **contactsLocationsModule.locations.&#91;245&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;245&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **statusModule.statusVerifiedDate**: 2026-02                                                                   | **statusModule.statusVerifiedDate**: 2026-03                                                                                        |
| 2026-03-13 02&#58;09&#58;20 | **statusModule.lastUpdateSubmitDate**: 2026-02-09                                                              | **statusModule.lastUpdateSubmitDate**: 2026-03-11                                                                                   |
| 2026-03-13 02&#58;09&#58;20 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-10                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-12                                                                          |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;5&#93;status**: NOT_YET_RECRUITING                                    | **contactsLocationsModule.locations.&#91;5&#93;status**: SUSPENDED                                                                  |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;16&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;16&#93;status**: RECRUITING                                                                |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;18&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;18&#93;status**: RECRUITING                                                                |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;19&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;19&#93;status**: RECRUITING                                                                |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;28&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;28&#93;status**: RECRUITING                                                                |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;45&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;45&#93;status**: RECRUITING                                                                |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;51&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;51&#93;status**: RECRUITING                                                                |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;67&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;67&#93;status**: RECRUITING                                                                |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;73&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;73&#93;status**: RECRUITING                                                                |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;81&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;81&#93;status**: RECRUITING                                                                |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;103&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;103&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;139&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;139&#93;status**: WITHDRAWN                                                                |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;141&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;141&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;143&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;143&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;144&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;144&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;146&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;146&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;160&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;160&#93;status**: WITHDRAWN                                                                |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;168&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;168&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;172&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;172&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;177&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;177&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;208&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;208&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;220&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;220&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;227&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;227&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;229&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;229&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;230&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;230&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;232&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;232&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;233&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;233&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;243&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;243&#93;status**: RECRUITING                                                               |
| 2026-03-13 02&#58;09&#58;20 | **contactsLocationsModule.locations.&#91;244&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;244&#93;status**: RECRUITING                                                               |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;173&#93;city**: Napoli                                                | **contactsLocationsModule.locations.&#91;173&#93;city**: Naples                                                                     |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;173&#93;geoPoint.lat**: 40.87618                                      | **contactsLocationsModule.locations.&#91;173&#93;geoPoint.lat**: 40.85216                                                           |
| 2026-03-21 02&#58;05&#58;10 | **contactsLocationsModule.locations.&#91;173&#93;geoPoint.lon**: 14.5195                                       | **contactsLocationsModule.locations.&#91;173&#93;geoPoint.lon**: 14.26811                                                           |
| 2026-04-09 02&#58;28&#58;32 | **statusModule.statusVerifiedDate**: 2026-03                                                                   | **statusModule.statusVerifiedDate**: 2026-04                                                                                        |
| 2026-04-09 02&#58;28&#58;32 | **statusModule.lastUpdateSubmitDate**: 2026-03-11                                                              | **statusModule.lastUpdateSubmitDate**: 2026-04-07                                                                                   |
| 2026-04-09 02&#58;28&#58;32 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-12                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-08                                                                          |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;4&#93;status**: NOT_YET_RECRUITING                                    | **contactsLocationsModule.locations.&#91;4&#93;status**: RECRUITING                                                                 |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;70&#93;city**: Ghent                                                  | **contactsLocationsModule.locations.&#91;70&#93;city**: Oklahoma City                                                               |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;70&#93;zip**: 9000                                                    | **contactsLocationsModule.locations.&#91;70&#93;zip**: 73104                                                                        |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;70&#93;country**: Belgium                                             | **contactsLocationsModule.locations.&#91;70&#93;country**: United States                                                            |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lat**: 51.05                                          | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lat**: 35.46756                                                            |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lon**: 3.71667                                        | **contactsLocationsModule.locations.&#91;70&#93;geoPoint.lon**: -97.51643                                                           |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;54&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;54&#93;status**: RECRUITING                                                                |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;88&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;88&#93;status**: WITHDRAWN                                                                 |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;139&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;139&#93;status**: RECRUITING                                                               |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;143&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;143&#93;status**: RECRUITING                                                               |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;149&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;149&#93;status**: RECRUITING                                                               |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;167&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;167&#93;status**: RECRUITING                                                               |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;208&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;208&#93;status**: RECRUITING                                                               |
| 2026-04-09 02&#58;28&#58;32 | **contactsLocationsModule.locations.&#91;229&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;229&#93;status**: RECRUITING                                                               |
| 2026-04-09 02&#58;28&#58;32 | -                                                                                                              | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;70&#93;&#91;&#x27;state&#x27;&#93;** (Added) |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.statusVerifiedDate**: 2026-04                                                                   | **statusModule.statusVerifiedDate**: 2026-05                                                                                        |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.lastUpdateSubmitDate**: 2026-04-07                                                              | **statusModule.lastUpdateSubmitDate**: 2026-05-05                                                                                   |
| 2026-05-26 02&#58;38&#58;41 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-08                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-06                                                                          |
| 2026-05-26 02&#58;38&#58;41 | **sponsorCollaboratorsModule.collaborators.&#91;1&#93;name**: Gynecologic Oncology Group (GOG) Foundation Inc. | **sponsorCollaboratorsModule.collaborators.&#91;1&#93;name**: European Network of Gynaecological Oncological Trial Groups (ENGOT)   |
| 2026-05-26 02&#58;38&#58;41 | **sponsorCollaboratorsModule.collaborators.&#91;1&#93;class**: UNKNOWN                                         | **sponsorCollaboratorsModule.collaborators.&#91;1&#93;class**: OTHER                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;1&#93;status**: NOT_YET_RECRUITING                                    | **contactsLocationsModule.locations.&#91;1&#93;status**: RECRUITING                                                                 |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;55&#93;city**: Saint Johnsbury                                        | **contactsLocationsModule.locations.&#91;55&#93;city**: Lebanon                                                                     |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;55&#93;state**: Vermont                                               | **contactsLocationsModule.locations.&#91;55&#93;state**: New Hampshire                                                              |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;55&#93;zip**: 05819                                                   | **contactsLocationsModule.locations.&#91;55&#93;zip**: 03756                                                                        |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;55&#93;geoPoint.lat**: 44.41922                                       | **contactsLocationsModule.locations.&#91;55&#93;geoPoint.lat**: 43.64229                                                            |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;55&#93;geoPoint.lon**: -72.01509                                      | **contactsLocationsModule.locations.&#91;55&#93;geoPoint.lon**: -72.25176                                                           |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;27&#93;city**: Jackson                                                | **contactsLocationsModule.locations.&#91;27&#93;city**: Winston-Salem                                                               |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;27&#93;state**: Mississippi                                           | **contactsLocationsModule.locations.&#91;27&#93;state**: North Carolina                                                             |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;27&#93;zip**: 39216                                                   | **contactsLocationsModule.locations.&#91;27&#93;zip**: 27157                                                                        |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;27&#93;geoPoint.lat**: 32.29876                                       | **contactsLocationsModule.locations.&#91;27&#93;geoPoint.lat**: 36.09986                                                            |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;27&#93;geoPoint.lon**: -90.18481                                      | **contactsLocationsModule.locations.&#91;27&#93;geoPoint.lon**: -80.24422                                                           |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;46&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;46&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;49&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;49&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;59&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;59&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;73&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;73&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;91&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;91&#93;status**: RECRUITING                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;117&#93;status**: RECRUITING                                          | **contactsLocationsModule.locations.&#91;117&#93;status**: WITHDRAWN                                                                |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;136&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;136&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;138&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;138&#93;status**: RECRUITING                                                               |
| 2026-05-26 02&#58;38&#58;41 | **contactsLocationsModule.locations.&#91;177&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;177&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **statusModule.statusVerifiedDate**: 2026-05                                                                   | **statusModule.statusVerifiedDate**: 2026-06                                                                                        |
| 2026-06-24 14&#58;19&#58;42 | **statusModule.lastUpdateSubmitDate**: 2026-05-05                                                              | **statusModule.lastUpdateSubmitDate**: 2026-06-19                                                                                   |
| 2026-06-24 14&#58;19&#58;42 | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-06                                                     | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-23                                                                          |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;22&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;22&#93;status**: RECRUITING                                                                |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;27&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;27&#93;status**: RECRUITING                                                                |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;32&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;32&#93;status**: SUSPENDED                                                                 |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;41&#93;status**: NOT_YET_RECRUITING                                   | **contactsLocationsModule.locations.&#91;41&#93;status**: RECRUITING                                                                |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;132&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;132&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;134&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;134&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;135&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;135&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;137&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;137&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;141&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;141&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;150&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;150&#93;status**: SUSPENDED                                                                |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;154&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;154&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;172&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;172&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;174&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;174&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;183&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;183&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;190&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;190&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;211&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;211&#93;status**: RECRUITING                                                               |
| 2026-06-24 14&#58;19&#58;42 | **contactsLocationsModule.locations.&#91;236&#93;status**: NOT_YET_RECRUITING                                  | **contactsLocationsModule.locations.&#91;236&#93;status**: RECRUITING                                                               |
