---
title: "NCT06657144 Change History"
---

| Timestamp                   | Before                                                                                                                                                                                                                                                                                                                                                                                                                                                    | After                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2026-02-10 07&#58;03&#58;39 | **statusModule.statusVerifiedDate**: 2026-01                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-02-10 07&#58;03&#58;39 | **statusModule.lastUpdateSubmitDate**: 2026-01-12                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-02-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-02-10 07&#58;03&#58;39 | **statusModule.lastUpdatePostDateStruct.date**: 2026-01-13                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-05                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-02-21 00&#58;54&#58;37 | **statusModule.lastUpdateSubmitDate**: 2026-02-03                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-02-19                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-02-21 00&#58;54&#58;37 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-05                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-02-21 00&#58;54&#58;37 | **contactsLocationsModule.locations.&#91;6&#93;contacts.&#91;0&#93;phone**: 702-952-3406                                                                                                                                                                                                                                                                                                                                                                  | **contactsLocationsModule.locations.&#91;6&#93;contacts.&#91;0&#93;phone**: 702-487-9428                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-03 00&#58;59&#58;11 | **statusModule.lastUpdateSubmitDate**: 2026-02-19                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-02-26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-03 00&#58;59&#58;11 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-20                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-31 02&#58;31&#58;36 | **identificationModule.briefTitle**: A Study of CHS-114 in Combination With Toripalimab and/or Other Treatments in Participants With Advanced Solid Tumors                                                                                                                                                                                                                                                                                                | **identificationModule.briefTitle**: A Study of CHS-114 (Tagmokitug) in Combination With Toripalimab and/or Other Treatments in Participants With Advanced Solid Tumors                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | **identificationModule.officialTitle**: A Phase 1B, Multicenter, Open-Label Study of the Safety and Efficacy of CHS-114 in Combination With Toripalimab With or Without Other Treatments in Participants With Advanced or Metastatic Solid Tumors                                                                                                                                                                                                         | **identificationModule.officialTitle**: A Phase 1B, Multicenter, Open-Label Study of the Safety and Efficacy of CHS-114 in Combination With Toripalimab With or Without Other Treatments in Participants With Advanced or Metastatic Solid Tumors (TREGCHECK 102)                                                                                                                                                                                                                                                                             |
| 2026-03-31 02&#58;31&#58;36 | **statusModule.statusVerifiedDate**: 2026-02                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-31 02&#58;31&#58;36 | **statusModule.primaryCompletionDateStruct.date**: 2027-05                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.primaryCompletionDateStruct.date**: 2028-01                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-31 02&#58;31&#58;36 | **statusModule.completionDateStruct.date**: 2027-05                                                                                                                                                                                                                                                                                                                                                                                                       | **statusModule.completionDateStruct.date**: 2028-01                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-31 02&#58;31&#58;36 | **statusModule.lastUpdateSubmitDate**: 2026-02-26                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-03-25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-31 02&#58;31&#58;36 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-02                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-30                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Field &#96;eligibilityModule.eligibilityCriteria&#96; changed from &#96;Key Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * At least 1 measurable lesion based on RECIST v1.1 as determined by the Investigator.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Resolved acute effects of any prior therapy to baseline severity or Grade 1 in accordance with National Cancer Institute (NCI)-Common Terminology Criteria for Adverse Events (CTCAE) v5.0, except for adverse events (AEs) not constituting a safety risk per Investigator judgement.                                                                                                                                                                                                                                                      |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort A (2L Gastric, Gastro-esophageal-junction &#92;&#91;GEJ&#92;&#93;, Esophageal Adenocarcinoma &#92;&#91;EAC&#92;&#93;) Specific Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Histologically or cytologically documented unresectable, locally advanced or metastatic gastric, GEJ, or esophageal adenocarcinoma that is human epidermal growth factor receptor 2 (HER2) - negative and microsatellite stable (MSS)/proficient mismatch repair (pMMR).                                                                                                                                                                                                                                                                    |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Progressed during or after first line systemic therapy that includes a platinum and fluoropyrimidine doublet with or without anti-programmed death receptor 1 (PD-1)/programmed death ligand 1 (PD-L1)-directed therapy (that is, in the second line setting).                                                                                                                                                                                                                                                                              |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide tumor tissue samples (baseline and on-treatment) is required for enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort B (2L Esophageal Squamous Cell Carcinoma &#92;&#91;ESCC&#92;&#93;) - Specific Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Histologically or cytologically documented unresectable, locally advanced or metastatic ESCC.                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Progressed during or after first line systemic therapy including a doublet of platinum and fluoropyrimidine or paclitaxel with or without anti-PD-1/PD-L1-directed therapy or anti-CTLA-4 and anti-PD-1/PD-L1-directed combination therapy.                                                                                                                                                                                                                                                                                                 |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide results from prior PD-L1 IHC assay score by FDA-approved or equivalent PD-L1 IHC diagnostic tests.                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide archival tumor tissue sample (baseline) is required for enrolment.                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort C (1L Esophageal Squamous Cell Carcinoma &#92;&#91;ESCC&#92;&#93;) - Specific Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Histologically or cytologically documented unresectable, locally advanced or metastatic ESCC.                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide baseline tumor tissue is required.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide results from prior PD-L1 IHC assay score by FDA-approved or equivalent PD-L1 IHC diagnostic tests.                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Calculated creatinine clearance ≥60 mL/min.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort D (4L+ Colorectal Carcinoma &#92;&#91;CRC&#92;&#93;) - Specific Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Histologically and/or cytologically documented unresectable advanced or metastatic colorectal adenocarcinoma. RAS, BRAF, and microsatellite instability/mismatch repair status for each participant must be documented, according to country level guidelines.                                                                                                                                                                                                                                                                              |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants who have no approved standard therapies with a proven clinical benefit available in the participant&#x27;s country. These therapies include fluoropyrimidine, oxaliplatin, irinotecan-based chemotherapy, anti-VEGF biological therapy (eg, bevacizumab, aflibercept, ramucirumab), an anti-EGFR therapy (eg, cetuximab, panitumumab) if RAS wildtype unless right-sided, trifluridine/tipiracil or regorafenib, and a BRAF inhibitor (ie, encorafenib) in BRAF V600E mutant).                                                 |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants who received oxaliplatin in the adjuvant setting and developed metastatic disease during or within 6 months of completing adjuvant therapy are considered eligible without receiving oxalipatin-based therapy in the metastatic setting.                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide baseline tumor tissue sample is required for enrolment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Key Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * History of prior malignancy other than the cancer under study that is progressing or has required active treatment within the past 3 years.                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Symptomatic or untreated central nervous system metastases, including leptomeningeal metastases, requiring concurrent treatment, including but not limited to surgery, radiation, and/or corticosteroids.                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Major surgery requiring general anesthesia within 28 days prior to the first dose of study treatment, still recovering from prior surgery, or with surgery scheduled during the study.                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Prior exposure to anti-C-C motif chemokine receptor 8 (CCR8) antibody.                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * History of Grade 4 allergic or anaphylactic reaction to any monoclonal antibody (mAb) therapy or any excipient in the study treatment.                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Active uncontrolled bacterial, fungal, or viral infection including hepatitis B virus (HBV), hepatitis C virus (HCV), known human immunodeficiency virus (HIV) or acquired immunodeficiency syndrome (AIDS)-related illness.                                                                                                                                                                                                                                                                                                                |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Any condition that, in the opinion of the Investigator or Sponsor, would interfere with the interpretation of study results.                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort A (2L Gastric, Gastro-esophageal-junction &#92;&#91;GEJ&#92;&#93;, Esophageal Adenocarcinoma &#92;&#91;EAC&#92;&#93;) Specific Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Received ≥ 2 prior systemic anticancer therapies for advanced or metastatic disease.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants at high risk for developing esophageal fistula by clinical assessment or imaging, such as prior history or associated symptoms of esophageal fistula or T4 classification assessed by endoscopic ultrasound (EUS).                                                                                                                                                                                                                                                                                                             |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort B (2L Esophageal Squamous Cell Carcinoma &#92;&#91;ESCC&#92;&#93;) - Specific Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Received ≥ 2 prior systemic anticancer therapies for advanced or metastatic disease.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants at high risk for developing esophageal fistula by clinical assessment or imaging, such as prior history or associated symptoms of esophageal fistula or T4 classification assessed by endoscopic ultrasound (EUS).                                                                                                                                                                                                                                                                                                             |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort C (1L Esophageal Squamous Cell Carcinoma &#92;&#91;ESCC&#92;&#93;) - Specific Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Received ≥ 1 prior systemic anticancer therapies for advanced or metastatic disease.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants who progressed during or within 6 months following the last dose of neoadjuvant, or perioperative therapy with curative intent.                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants at high risk for developing esophageal fistula by clinical assessment or imaging, such as prior history or associated symptoms of esophageal fistula or T4 classification assessed by endoscopic ultrasound (EUS).                                                                                                                                                                                                                                                                                                             |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Known dihydropyrimidine dehydrogenase deficiency or thymidine synthase gene polymorphism predisposing the participant to 5-FU toxicity.                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Known allergies to 5-FU or cisplatin.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Note&#58; Other protocol-specified inclusion/exclusion criteria apply.&#96; to &#96;Key Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * At least 1 measurable lesion based on RECIST v1.1 as determined by the Investigator.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Resolved acute effects of any prior therapy to baseline severity or Grade 1 in accordance with National Cancer Institute (NCI)-Common Terminology Criteria for Adverse Events (CTCAE) v5.0, except for adverse events (AEs) not constituting a safety risk per Investigator judgement.                                                                                                                                                                                                                                                      |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort A (2L Gastric, Gastro-esophageal-junction &#92;&#91;GEJ&#92;&#93;, Esophageal Adenocarcinoma &#92;&#91;EAC&#92;&#93;) Specific Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Histologically or cytologically documented unresectable, locally advanced or metastatic gastric, GEJ, or esophageal adenocarcinoma that is human epidermal growth factor receptor 2 (HER2) - negative and microsatellite stable (MSS)/proficient mismatch repair (pMMR).                                                                                                                                                                                                                                                                    |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Progressed during or after first line systemic therapy that includes a platinum and fluoropyrimidine doublet with or without anti-programmed death receptor 1 (PD-1)/programmed death ligand 1 (PD-L1)-directed therapy (that is, in the second line setting).                                                                                                                                                                                                                                                                              |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide tumor tissue samples (baseline and on-treatment) is required for enrollment.                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort B (2L Esophageal Squamous Cell Carcinoma &#92;&#91;ESCC&#92;&#93;) - Specific Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Histologically or cytologically documented unresectable, locally advanced or metastatic ESCC.                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Progressed during or after first line systemic therapy including a doublet of platinum and fluoropyrimidine or paclitaxel with or without anti-PD-1/PD-L1-directed therapy or anti-CTLA-4 and anti-PD-1/PD-L1-directed combination therapy.                                                                                                                                                                                                                                                                                                 |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide results from prior PD-L1 IHC assay score by FDA-approved or equivalent PD-L1 IHC diagnostic tests.                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide archival tumor tissue sample (baseline) is required for enrolment.                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort C (1L Esophageal Squamous Cell Carcinoma &#92;&#91;ESCC&#92;&#93;) - Specific Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Histologically or cytologically documented unresectable, locally advanced or metastatic ESCC.                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide baseline tumor tissue is required.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide results from prior PD-L1 IHC assay score by FDA-approved or equivalent PD-L1 IHC diagnostic tests.                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Calculated creatinine clearance ≥60 mL/min.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort D, Arms D1 and D2 (4L+ Colorectal Carcinoma &#92;&#91;CRC&#92;&#93;) - Specific Inclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Histologically and/or cytologically documented unresectable advanced or metastatic colorectal adenocarcinoma. RAS, BRAF, and microsatellite instability/mismatch repair status for each participant must be documented, according to country level guidelines.                                                                                                                                                                                                                                                                              |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants who have no available therapies with a proven clinical benefit available in the participant&#x27;s country per investigator. These therapies include the following&#58; fluoropyrimidine, oxaliplatin, irinotecan-based chemotherapy, anti-VEGF biological therapy (eg, bevacizumab, aflibercept, ramucirumab), an anti-EGFR therapy (eg, cetuximab, panitumumab) if RAS wildtype unless right-sided, either trifluridine/tipiracil, fruqintinib or regorafenib, and a BRAF inhibitor (ie, encorafenib) in BRAF V600E mutant). |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants who received oxaliplatin in the adjuvant setting and developed metastatic disease during or within 6 months of completing adjuvant therapy are considered eligible without receiving oxalipatin-based therapy in the metastatic setting.                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Consent to provide baseline tumor tissue sample is required for enrolment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Key Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * History of prior malignancy other than the cancer under study that is progressing or has required active treatment within the past 3 years.                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Symptomatic or untreated central nervous system metastases, including leptomeningeal metastases, requiring concurrent treatment, including but not limited to surgery, radiation, and/or corticosteroids.                                                                                                                                                                                                                                                                                                                                   |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Major surgery requiring general anesthesia within 28 days prior to the first dose of study treatment, still recovering from prior surgery, or with surgery scheduled during the study.                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Prior exposure to anti-C-C motif chemokine receptor 8 (CCR8) antibody.                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * History of Grade 4 allergic or anaphylactic reaction to any monoclonal antibody (mAb) therapy or any excipient in the study treatment.                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Active uncontrolled bacterial, fungal, or viral infection including hepatitis B virus (HBV), hepatitis C virus (HCV), known human immunodeficiency virus (HIV) or acquired immunodeficiency syndrome (AIDS)-related illness.                                                                                                                                                                                                                                                                                                                |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Any condition that, in the opinion of the Investigator or Sponsor, would interfere with the interpretation of study results.                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort A (2L Gastric, Gastro-esophageal-junction &#92;&#91;GEJ&#92;&#93;, Esophageal Adenocarcinoma &#92;&#91;EAC&#92;&#93;) Specific Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                 |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Received ≥ 2 prior systemic anticancer therapies for advanced or metastatic disease.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants at high risk for developing esophageal fistula by clinical assessment or imaging, such as prior history or associated symptoms of esophageal fistula or T4 classification assessed by endoscopic ultrasound (EUS).                                                                                                                                                                                                                                                                                                             |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort B (2L Esophageal Squamous Cell Carcinoma &#92;&#91;ESCC&#92;&#93;) - Specific Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Received ≥ 2 prior systemic anticancer therapies for advanced or metastatic disease.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants at high risk for developing esophageal fistula by clinical assessment or imaging, such as prior history or associated symptoms of esophageal fistula or T4 classification assessed by endoscopic ultrasound (EUS).                                                                                                                                                                                                                                                                                                             |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Cohort C (1L Esophageal Squamous Cell Carcinoma &#92;&#91;ESCC&#92;&#93;) - Specific Exclusion Criteria&#58;                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Received ≥ 1 prior systemic anticancer therapies for advanced or metastatic disease.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants who progressed during or within 6 months following the last dose of neoadjuvant, or perioperative therapy with curative intent.                                                                                                                                                                                                                                                                                                                                                                                                |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Participants at high risk for developing esophageal fistula by clinical assessment or imaging, such as prior history or associated symptoms of esophageal fistula or T4 classification assessed by endoscopic ultrasound (EUS).                                                                                                                                                                                                                                                                                                             |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Known dihydropyrimidine dehydrogenase deficiency or thymidine synthase gene polymorphism predisposing the participant to 5-FU toxicity.                                                                                                                                                                                                                                                                                                                                                                                                     |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | * Known allergies to 5-FU or cisplatin.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 2026-03-31 02&#58;31&#58;36 | -                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Note&#58; Other protocol-specified inclusion/exclusion criteria apply.&#96;                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2026-04-01 02&#58;42&#58;41 | **statusModule.lastUpdateSubmitDate**: 2026-03-25                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-03-27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-04-01 02&#58;42&#58;41 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-30                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-31                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-04-07 02&#58;32&#58;47 | **statusModule.statusVerifiedDate**: 2026-03                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-04-07 02&#58;32&#58;47 | **statusModule.lastUpdateSubmitDate**: 2026-03-27                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-04-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-04-07 02&#58;32&#58;47 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-31                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-04-07 02&#58;32&#58;47 | **contactsLocationsModule.locations.&#91;0&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                       | **contactsLocationsModule.locations.&#91;0&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2026-04-07 02&#58;32&#58;47 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;0&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)                                                                                                                                                                                                                                                                                                                   | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-05-26 02&#58;38&#58;39 | **referencesModule.references.&#91;0&#93;citation**: Wang X, Kapoor VN, Chin DJ, Klakamp SL, Baruffaldi F, Mohan JF, Haines R, Dulak A, Panduro M, Ren Y, Masia R, Hill JA, LaVallee TM, Rajasekaran N. CHS-114&#58; an afucosylated anti-CCR8 monoclonal antibody that selectively depletes intratumoral Treg cells and induces antitumor immune responses. Mol Cancer Ther. 2025 Dec 22. doi&#58; 10.1158/1535-7163.MCT-25-0367. Online ahead of print. | **referencesModule.references.&#91;0&#93;citation**: Wang X, Kapoor VN, Chin DJ, Klakamp SL, Baruffaldi F, Mohan JF, Haines R, Dulak A, Panduro M, Ren Y, Masia R, Hill JA, LaVallee TM, Rajasekaran N. CHS-114&#58; An Afucosylated Anti-CCR8 Monoclonal Antibody that Selectively Depletes Intratumoral Treg Cells and Induces Antitumor Immune Responses. Mol Cancer Ther. 2026 May 4;25(5)&#58;685-700. doi&#58; 10.1158/1535-7163.MCT-25-0367.                                                                                           |
| 2026-06-13 03&#58;52&#58;39 | **statusModule.statusVerifiedDate**: 2026-04                                                                                                                                                                                                                                                                                                                                                                                                              | **statusModule.statusVerifiedDate**: 2026-06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 2026-06-13 03&#58;52&#58;39 | **statusModule.lastUpdateSubmitDate**: 2026-04-03                                                                                                                                                                                                                                                                                                                                                                                                         | **statusModule.lastUpdateSubmitDate**: 2026-06-10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 2026-06-13 03&#58;52&#58;39 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-06                                                                                                                                                                                                                                                                                                                                                                                                | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 2026-06-13 03&#58;52&#58;39 | **contactsLocationsModule.locations.&#91;19&#93;status**: RECRUITING                                                                                                                                                                                                                                                                                                                                                                                      | **contactsLocationsModule.locations.&#91;19&#93;status**: WITHDRAWN                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2026-06-13 03&#58;52&#58;39 | **root&#91;&#x27;contactsLocationsModule&#x27;&#93;&#91;&#x27;locations&#x27;&#93;&#91;19&#93;&#91;&#x27;contacts&#x27;&#93;** (Removed)                                                                                                                                                                                                                                                                                                                  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
