---
title: "NCT07161414 Change History"
---

| Timestamp                   | Before                                                                      | After                                                               |
|:----------------------------|:----------------------------------------------------------------------------|:--------------------------------------------------------------------|
| 2026-02-24 00&#58;57&#58;05 | **statusModule.statusVerifiedDate**: 2025-12                                | **statusModule.statusVerifiedDate**: 2026-02                        |
| 2026-02-24 00&#58;57&#58;05 | **statusModule.lastUpdateSubmitDate**: 2025-12-18                           | **statusModule.lastUpdateSubmitDate**: 2026-02-20                   |
| 2026-02-24 00&#58;57&#58;05 | **statusModule.lastUpdatePostDateStruct.date**: 2025-12-24                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-23          |
| 2026-02-24 00&#58;57&#58;05 | **contactsLocationsModule.locations.&#91;8&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;8&#93;status**: SUSPENDED  |
| 2026-02-24 00&#58;57&#58;05 | **contactsLocationsModule.locations.&#91;9&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;9&#93;status**: SUSPENDED  |
| 2026-03-18 02&#58;24&#58;04 | **statusModule.statusVerifiedDate**: 2026-02                                | **statusModule.statusVerifiedDate**: 2026-03                        |
| 2026-03-18 02&#58;24&#58;04 | **statusModule.lastUpdateSubmitDate**: 2026-02-20                           | **statusModule.lastUpdateSubmitDate**: 2026-03-16                   |
| 2026-03-18 02&#58;24&#58;04 | **statusModule.lastUpdatePostDateStruct.date**: 2026-02-23                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-17          |
| 2026-03-18 02&#58;24&#58;04 | **contactsLocationsModule.locations.&#91;6&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;6&#93;status**: RECRUITING |
| 2026-03-18 02&#58;24&#58;04 | **contactsLocationsModule.locations.&#91;7&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;7&#93;status**: RECRUITING |
| 2026-03-18 02&#58;24&#58;04 | **contactsLocationsModule.locations.&#91;8&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;8&#93;status**: RECRUITING |
| 2026-04-10 02&#58;39&#58;09 | **statusModule.statusVerifiedDate**: 2026-03                                | **statusModule.statusVerifiedDate**: 2026-04                        |
| 2026-04-10 02&#58;39&#58;09 | **statusModule.lastUpdateSubmitDate**: 2026-03-16                           | **statusModule.lastUpdateSubmitDate**: 2026-04-08                   |
| 2026-04-10 02&#58;39&#58;09 | **statusModule.lastUpdatePostDateStruct.date**: 2026-03-17                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-09          |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.statusVerifiedDate**: 2026-04                                | **statusModule.statusVerifiedDate**: 2026-05                        |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdateSubmitDate**: 2026-04-08                           | **statusModule.lastUpdateSubmitDate**: 2026-05-07                   |
| 2026-05-26 02&#58;38&#58;40 | **statusModule.lastUpdatePostDateStruct.date**: 2026-04-09                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-08          |
| 2026-06-11 04&#58;04&#58;07 | **statusModule.statusVerifiedDate**: 2026-05                                | **statusModule.statusVerifiedDate**: 2026-06                        |
| 2026-06-11 04&#58;04&#58;07 | **statusModule.lastUpdateSubmitDate**: 2026-05-07                           | **statusModule.lastUpdateSubmitDate**: 2026-06-09                   |
| 2026-06-11 04&#58;04&#58;07 | **statusModule.lastUpdatePostDateStruct.date**: 2026-05-08                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-10          |
| 2026-06-11 04&#58;04&#58;07 | **contactsLocationsModule.locations.&#91;3&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;3&#93;status**: RECRUITING |
| 2026-06-11 04&#58;04&#58;07 | **contactsLocationsModule.locations.&#91;4&#93;status**: NOT_YET_RECRUITING | **contactsLocationsModule.locations.&#91;4&#93;status**: RECRUITING |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.statusVerifiedDate**: 2026-06                                | **statusModule.statusVerifiedDate**: 2026-07                        |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.lastUpdateSubmitDate**: 2026-06-09                           | **statusModule.lastUpdateSubmitDate**: 2026-07-08                   |
| 2026-07-28 00&#58;26&#58;05 | **statusModule.lastUpdatePostDateStruct.date**: 2026-06-10                  | **statusModule.lastUpdatePostDateStruct.date**: 2026-07-09          |
